from datetime import date

POGO_RELEASE_DATE: date = date(2016, 6, 5)
GYM_REWORK_DATE: date = date(2017, 6, 22)
RAID_RELEASE_DATE: date = date(2017, 6, 26)
LEGENDARY_RAID_RELEASE_DATE: date = date(2017, 7, 22)
QUESTS_RELEASE_DATE: date = date(2018, 3, 30)
FRIENDSHIPS_RELEASE_DATE: date = date(2018, 6, 21)

STANDARD_MEDALS = [
    "badge_travel_km",
    "badge_pokedex_entries",
    "badge_capture_total",
    "badge_evolved_total",
    "badge_hatched_total",
    "badge_pokestops_visited",
    "badge_unique_pokestops",
    "badge_big_magikarp",
    "badge_battle_attack_won",
    "badge_battle_training_won",
    "badge_small_rattata",
    "badge_pikachu",
    "badge_unown",
    "badge_pokedex_entries_gen2",
    "badge_raid_battle_won",
    "badge_legendary_battle_won",
    "badge_berries_fed",
    "badge_hours_defended",
    "badge_pokedex_entries_gen3",
    "badge_challenge_quests",
    "badge_max_level_friends",
    "badge_trading",
    "badge_trading_distance",
    "badge_pokedex_entries_gen4",
    "badge_great_league",
    "badge_ultra_league",
    "badge_master_league",
    "badge_photobomb",
    "badge_pokedex_entries_gen5",
    "badge_pokemon_purified",
    "badge_rocket_grunts_defeated",
    "badge_rocket_giovanni_defeated",
    "badge_buddy_best",
    "badge_pokedex_entries_gen6",
    "badge_7_day_streaks",
    "badge_unique_raid_bosses_defeated",
    "badge_raids_with_friends",
    "badge_pokemon_caught_at_your_lures",
    "badge_wayfarer",
    "badge_total_mega_evos",
    "badge_unique_mega_evos",
]

BATTLE_HUB_STATS = [
    "battle_hub_stats_wins",
    "battle_hub_stats_battles",
    "battle_hub_stats_stardust",
    "battle_hub_stats_streak",
]

UPDATE_FIELDS_BADGES = STANDARD_MEDALS + BATTLE_HUB_STATS

UPDATE_FIELDS_TYPES = [
    "badge_type_normal",
    "badge_type_fighting",
    "badge_type_flying",
    "badge_type_poison",
    "badge_type_ground",
    "badge_type_rock",
    "badge_type_bug",
    "badge_type_ghost",
    "badge_type_steel",
    "badge_type_fire",
    "badge_type_water",
    "badge_type_grass",
    "badge_type_electric",
    "badge_type_psychic",
    "badge_type_ice",
    "badge_type_dragon",
    "badge_type_dark",
    "badge_type_fairy",
]

UPDATE_SORTABLE_FIELDS = (
    [
        "total_xp",
        "pokedex_caught",
        "pokedex_seen",
        "gymbadges_gold",
    ]
    + UPDATE_FIELDS_BADGES
    + UPDATE_FIELDS_TYPES
)

UPDATE_NON_REVERSEABLE_FIELDS = (
    [
        "total_xp",
        "pokedex_caught",
        "pokedex_seen",
    ]
    + UPDATE_FIELDS_BADGES
    + UPDATE_FIELDS_TYPES
)

BADGES = [
    {
        "id": 1,
        "name": "badge_travel_km",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 10000,
    },
    {
        "id": 2,
        "name": "badge_pokedex_entries",
        "bronze": 5,
        "silver": 50,
        "gold": 100,
        "platinum": 151,
    },
    {
        "id": 3,
        "name": "badge_capture_total",
        "bronze": 30,
        "silver": 500,
        "gold": 2000,
        "platinum": 50000,
    },
    {
        "id": 5,
        "name": "badge_evolved_total",
        "bronze": 3,
        "silver": 20,
        "gold": 200,
        "platinum": 2000,
    },
    {
        "id": 6,
        "name": "badge_hatched_total",
        "bronze": 10,
        "silver": 100,
        "gold": 500,
        "platinum": 2500,
    },
    {
        "id": 8,
        "name": "badge_pokestops_visited",
        "bronze": 100,
        "silver": 1000,
        "gold": 2000,
        "platinum": 50000,
    },
    {
        "id": 9,
        "name": "badge_unique_pokestops",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 11,
        "name": "badge_big_magikarp",
        "bronze": 3,
        "silver": 50,
        "gold": 300,
        "platinum": 1000,
    },
    {
        "id": 13,
        "name": "badge_battle_attack_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 4000,
    },
    {
        "id": 14,
        "name": "badge_battle_training_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 36,
        "name": "badge_small_rattata",
        "bronze": 3,
        "silver": 50,
        "gold": 300,
        "platinum": 1000,
    },
    {
        "id": 37,
        "name": "badge_pikachu",
        "bronze": 3,
        "silver": 50,
        "gold": 300,
        "platinum": 1000,
    },
    {
        "id": 38,
        "name": "badge_unown",
        "bronze": 3,
        "silver": 10,
        "gold": 26,
        "platinum": 28,
    },
    {
        "id": 39,
        "name": "badge_pokedex_entries_gen2",
        "bronze": 3,
        "silver": 10,
        "gold": 26,
        "platinum": 100,
    },
    {
        "id": 40,
        "name": "badge_raid_battle_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 41,
        "name": "badge_legendary_battle_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 42,
        "name": "badge_berries_fed",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 15000,
    },
    {
        "id": 43,
        "name": "badge_hours_defended",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 15000,
    },
    {
        "id": 45,
        "name": "badge_pokedex_entries_gen3",
        "bronze": 5,
        "silver": 40,
        "gold": 90,
        "platinum": 135,
    },
    {
        "id": 46,
        "name": "badge_challenge_quests",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2500,
    },
    {
        "id": 48,
        "name": "badge_max_level_friends",
        "bronze": 1,
        "silver": 2,
        "gold": 3,
        "platinum": 20,
    },
    {
        "id": 49,
        "name": "badge_trading",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2500,
    },
    {
        "id": 50,
        "name": "badge_trading_distance",
        "bronze": 1000,
        "silver": 10000,
        "gold": 1000000,
        "platinum": 10000000,
    },
    {
        "id": 51,
        "name": "badge_pokedex_entries_gen4",
        "bronze": 5,
        "silver": 30,
        "gold": 80,
        "platinum": 107,
    },
    {
        "id": 52,
        "name": "badge_great_league",
        "bronze": 5,
        "silver": 50,
        "gold": 200,
        "platinum": 1000,
    },
    {
        "id": 53,
        "name": "badge_ultra_league",
        "bronze": 5,
        "silver": 50,
        "gold": 200,
        "platinum": 1000,
    },
    {
        "id": 54,
        "name": "badge_master_league",
        "bronze": 5,
        "silver": 50,
        "gold": 200,
        "platinum": 1000,
    },
    {
        "id": 55,
        "name": "badge_photobomb",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 400,
    },
    {
        "id": 56,
        "name": "badge_pokedex_entries_gen5",
        "bronze": 5,
        "silver": 50,
        "gold": 100,
        "platinum": 156,
    },
    {
        "id": 57,
        "name": "badge_pokemon_purified",
        "bronze": 5,
        "silver": 50,
        "gold": 500,
        "platinum": 1000,
    },
    {
        "id": 58,
        "name": "badge_rocket_grunts_defeated",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 59,
        "name": "badge_rocket_giovanni_defeated",
        "bronze": 1,
        "silver": 5,
        "gold": 20,
        "platinum": 50,
    },
    {
        "id": 60,
        "name": "badge_buddy_best",
        "bronze": 1,
        "silver": 10,
        "gold": 100,
        "platinum": 2000,
    },
    {
        "id": 61,
        "name": "badge_pokedex_entries_gen6",
        "bronze": 5,
        "silver": 25,
        "gold": 50,
        "platinum": 72,
    },
    {
        "id": 64,
        "name": "badge_7_day_streaks",
        "bronze": 1,
        "silver": 10,
        "gold": 50,
        "platinum": 100,
    },
    {
        "id": 65,
        "name": "badge_unique_raid_bosses_defeated",
        "bronze": 2,
        "silver": 10,
        "gold": 50,
        "platinum": 150,
    },
    {
        "id": 66,
        "name": "badge_raids_with_friends",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 67,
        "name": "badge_pokemon_caught_at_your_lures",
        "bronze": 5,
        "silver": 25,
        "gold": 500,
        "platinum": 2000,
    },
    {
        "id": 68,
        "name": "badge_wayfarer",
        "bronze": 50,
        "silver": 500,
        "gold": 1000,
        "platinum": 1500,
    },
    {
        "id": 69,
        "name": "badge_total_mega_evos",
        "bronze": 1,
        "silver": 50,
        "gold": 500,
        "platinum": 1000,
    },
    {
        "id": 70,
        "name": "badge_unique_mega_evos",
        "bronze": 1,
        "silver": 24,
        "gold": 36,
        "platinum": 46,
    },
    {
        "id": 18,
        "name": "badge_type_normal",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 19,
        "name": "badge_type_fighting",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 20,
        "name": "badge_type_flying",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 21,
        "name": "badge_type_poison",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 22,
        "name": "badge_type_ground",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 23,
        "name": "badge_type_rock",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 24,
        "name": "badge_type_bug",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 25,
        "name": "badge_type_ghost",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 26,
        "name": "badge_type_steel",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 27,
        "name": "badge_type_fire",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 28,
        "name": "badge_type_water",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 29,
        "name": "badge_type_grass",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 30,
        "name": "badge_type_electric",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 31,
        "name": "badge_type_psychic",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 32,
        "name": "badge_type_ice",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 33,
        "name": "badge_type_dragon",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 34,
        "name": "badge_type_dark",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 35,
        "name": "badge_type_fairy",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
]
