version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "dep: "
    labels:
      - "dependencies"
      - "pip"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: main
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "chore: "
    labels:
      - "dependencies"
