version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "dep: "
    labels:
      - "dependencies"
      - "pip"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "chore: "
    labels:
      - "dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "daily"
