version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    labels:
      - "dependencies"
      - "pip"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    labels:
      - "dependencies"
      - "npm"
