version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  target-branch: feature/django3majorrewrite
  reviewers:
  - jayturnr
  assignees:
  - jayturnr
  labels:
  - dependencies
  ignore:
  - dependency-name: django
    versions:
    - "> 2.1.11, < 3"
  - dependency-name: django-cookie-law
    versions:
    - "> 2.0.1"
  - dependency-name: django-modeladmin-reorder
    versions:
    - "> 0.3, < 0.4"
