version: 2
updates:
- package-ecosystem: pip
  directory: "/backend/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  target-branch: feature/django3majorrewrite
  reviewers:
  - jayturnr
  assignees:
  - jayturnr
  labels:
  - dependencies
