# Generated by Django 3.2.10 on 2021-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordcommunity',
            name='id',
            field=models.PositiveBigIntegerField(help_text='guild id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discordcommunity',
            name='preferred_locale',
            field=models.CharField(blank=True, choices=[('de-DE', 'German'), ('en-US', 'English'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('it-IT', 'Italian'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('nl-NL', 'Dutch'), ('nl-BE', 'Dutch, Belgium'), ('ro-RO', 'Romanian'), ('ru-RU', 'Russian'), ('pt-BR', 'Brazilian Portuguese'), ('th-TH', 'Thai'), ('zh-HK', 'Traditional Chinese')], default='en-us', help_text='The primary language of the community. This is used for all communications and leaderboard positions.', max_length=5, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='historicaldiscordcommunity',
            name='id',
            field=models.PositiveBigIntegerField(db_index=True, help_text='guild id'),
        ),
        migrations.AlterField(
            model_name='historicaldiscordcommunity',
            name='preferred_locale',
            field=models.CharField(blank=True, choices=[('de-DE', 'German'), ('en-US', 'English'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('it-IT', 'Italian'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('nl-NL', 'Dutch'), ('nl-BE', 'Dutch, Belgium'), ('ro-RO', 'Romanian'), ('ru-RU', 'Russian'), ('pt-BR', 'Brazilian Portuguese'), ('th-TH', 'Thai'), ('zh-HK', 'Traditional Chinese')], default='en-us', help_text='The primary language of the community. This is used for all communications and leaderboard positions.', max_length=5, null=True, verbose_name='Language'),
        ),
    ]
