# Generated by Django 3.2.10 on 2021-12-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
