# Generated by Django 3.2.10 on 2021-12-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0002_delete_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faction',
            options={'default_permissions': ('view',), 'verbose_name': 'Faction', 'verbose_name_plural': 'Factions'},
        ),
    ]
