# Generated by Django 2.2.27 on 2022-03-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordGuild",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("data", django.db.models.JSONField(blank=True, null=True)),
                ("cached_date", models.DateTimeField(auto_now_add=True)),
                ("has_access", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Discord Guild",
                "verbose_name_plural": "Discord Guilds",
            },
        ),
        migrations.CreateModel(
            name="DiscordUser",
            fields=[],
            options={
                "verbose_name": "Discord User",
                "verbose_name_plural": "Discord Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("socialaccount.socialaccount",),
        ),
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("data", django.db.models.JSONField(blank=True, null=True)),
                ("cached_date", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.DiscordGuild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Role",
                "verbose_name_plural": "Discord Roles",
                "ordering": ["guild__id", "-data__position"],
            },
        ),
        migrations.CreateModel(
            name="DiscordGuildMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("nick_override", models.CharField(blank=True, max_length=32, null=True)),
                ("data", django.db.models.JSONField(blank=True, null=True)),
                ("cached_date", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.DiscordGuild"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.DiscordUser"
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Member",
                "verbose_name_plural": "Discord Members",
                "unique_together": {("guild", "user")},
            },
        ),
        migrations.AddField(
            model_name="discordguild",
            name="members",
            field=models.ManyToManyField(
                through="core.DiscordGuildMembership", to="core.DiscordUser"
            ),
        ),
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("data", django.db.models.JSONField(blank=True, null=True)),
                ("cached_date", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="core.DiscordGuild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Channel",
                "verbose_name_plural": "Discord Channels",
            },
        ),
    ]
