# Generated by Django 3.0.7 on 2020-06-20 18:39

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanUser',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.HumanUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Service Account',
                'verbose_name_plural': 'Service Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.ServiceAccountManager()),
            ],
        ),
        migrations.AlterField(
            model_name='nickname',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HumanUser', verbose_name='User'),
        ),
    ]
