# Generated by Django 3.2.13 on 2022-05-28 08:19

from django.db import migrations


def migrate_guild_settings(apps, schema_editor):
    DiscordGuildSettings = apps.get_model("core", "DiscordGuildSettings")
    for guild_settings in DiscordGuildSettings.objects.all():
        guild_settings.language = guild_settings.language_old
        guild_settings.timezone = guild_settings.timezone_old
        guild_settings.renamer = guild_settings.renamer_old
        guild_settings.renamer_with_level = guild_settings.renamer_with_level_old
        guild_settings.renamer_with_level_format = guild_settings.renamer_with_level_format_old
        guild_settings.monthly_gains_channel = guild_settings.monthly_gains_channel_old
        guild_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_fields_to_DiscordGuild"),
    ]

    operations = [
        migrations.RunPython(migrate_guild_settings, migrations.RunPython.noop),
    ]
