# Generated by Django 2.1.3 on 2018-12-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discordguildmembership_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordguildmembership',
            options={'verbose_name': 'Discord Member', 'verbose_name_plural': 'Discord Members'},
        ),
    ]
