# Generated by Django 3.2.13 on 2022-05-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_guild_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordguildsettings',
            name='language_old',
        ),
        migrations.RemoveField(
            model_name='discordguildsettings',
            name='monthly_gains_channel_old',
        ),
        migrations.RemoveField(
            model_name='discordguildsettings',
            name='renamer_old',
        ),
        migrations.RemoveField(
            model_name='discordguildsettings',
            name='renamer_with_level_format_old',
        ),
        migrations.RemoveField(
            model_name='discordguildsettings',
            name='renamer_with_level_old',
        ),
        migrations.RemoveField(
            model_name='discordguildsettings',
            name='timezone_old',
        ),
    ]
