# Generated by Django 4.0.5 on 2022-06-01 23:16

from django.db import migrations


def populate_extra_fields(apps, schema_editor):
    DiscordGuild = apps.get_model("core", "DiscordGuild")
    for guild in DiscordGuild.objects.all():
        if guild.data:
            guild.name = guild.data.get("name")
            guild.owner_id = guild.data.get("owner_id")
            guild.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_discordguild_name_discordguild_owner_id"),
    ]

    operations = [migrations.RunPython(populate_extra_fields, reverse_code=migrations.RunPython.noop)]
