# Generated by Django 3.2.13 on 2022-05-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0008_add_restraints'),
        ('core', '0007_remove_guild_settings_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordGuildSettings',
        ),
    ]
