# Generated by Django 4.2 on 2023-04-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_new_columns_to_discord_guild_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguild",
            name="leaderboard_channel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to=models.Q(("data__type", 0)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.discordchannel",
            ),
        ),
    ]
