# Generated by Django 2.1.4 on 2018-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181218_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguildmembership',
            name='nick_override',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
