# Generated by Django 2.1.4 on 2019-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190205_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguild',
            name='settings_pokemongo_rename',
            field=models.BooleanField(default=True, help_text='This setting will rename a user to their Pokémon Go username whenever they join your server and when their name changes on here.', verbose_name='Rename users when they join.'),
        ),
        migrations.AlterField(
            model_name='discordguild',
            name='settings_pokemongo_rename_with_level',
            field=models.BooleanField(default=False, help_text='This setting will add a level to the end of their username on your server. Their name will update whenever they level up.', verbose_name='Rename users with their level indicator'),
        ),
    ]
