# Generated by Django 2.1.10 on 2019-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20190210_1954"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="settings_welcomer_message_existing",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discordguild",
            name="settings_welcomer_message_new",
            field=models.TextField(blank=True, null=True),
        ),
    ]
