# Generated by Django 2.1.11 on 2019-11-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20191107_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="settings_welcomer_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="discordguild",
            name="settings_welcome_channel",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"data__type": 0},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="welcome_channel",
                to="core.DiscordChannel",
            ),
        ),
        migrations.AlterField(
            model_name="discordguild",
            name="settings_xp_gains_channel",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"data__type": 0},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="xp_gains_channel",
                to="core.DiscordChannel",
            ),
        ),
    ]
