# Generated by Django 2.2.16 on 2020-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200901_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguildsettings',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('de-DE', 'German'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('it-IT', 'Italian'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('pt-BR', 'Brazilian Portuguese'), ('th-TH', 'Thai'), ('zh-HK', 'Traditional Chinese')], default='en-US', max_length=5),
        ),
    ]
