# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('website', '0001_initial'), ('website', '0002_auto_20171203_1508'), ('website', '0003_auto_20171206_1928'), ('website', '0004_auto_20171208_0229'), ('website', '0005_auto_20171209_1502'), ('website', '0006_auto_20171213_1441')]

    initial = True

    dependencies = [
        ('trainer', '0008_clear_default_start_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('invite_slug', models.SlugField(unique=True)),
                ('extra_data', models.TextField(blank=True)),
                ('team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction')),
                ('enhanced', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('long_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('username', models.SlugField(unique=True)),
                ('extra_data', models.TextField(blank=True)),
                ('team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction')),
                ('description', models.CharField(blank=True, max_length=140)),
                ('long_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('invite_slug', models.SlugField(max_length=100, unique=True)),
                ('extra_data', models.TextField(blank=True)),
                ('team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction')),
                ('description', models.CharField(blank=True, max_length=140)),
                ('long_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessengerGroup',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('extra_data', models.TextField(blank=True)),
                ('invite_slug', models.SlugField(max_length=100, unique=True)),
                ('team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction')),
                ('description', models.CharField(blank=True, max_length=140)),
                ('long_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
