# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('basecommunity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.BaseCommunity')),
                ('identifier', models.BigIntegerField()),
                ('json', models.TextField(blank=True)),
            ],
            bases=('website.basecommunity',),
        ),
    ]
