# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discord',
            old_name='json',
            new_name='extra_data',
        ),
        migrations.AddField(
            model_name='basecommunity',
            name='locations',
            field=models.ManyToManyField(to='cities_light.City'),
        ),
    ]
