# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171213_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord',
            name='invite_override_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discord',
            name='invite_override_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='invite_override_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='invite_override_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='invite_override_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='invite_override_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='invite_override_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='invite_override_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='username',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
