# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('website', '0003_migrate_discord_servers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecommunity',
            name='locations',
        ),
        migrations.AddField(
            model_name='basecommunity',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
