# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171206_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='discord',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discord',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
