# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('cities', '0010_adjust_unique_attributes'),
        ('website', '0003_auto_20171213_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='location_type',
        ),
        migrations.AddField(
            model_name='discord',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='discord',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='discord',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District'),
        ),
        migrations.AddField(
            model_name='discord',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region'),
        ),
        migrations.AddField(
            model_name='discord',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion'),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District'),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region'),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion'),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District'),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region'),
        ),
        migrations.AddField(
            model_name='messengergroup',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion'),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District'),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region'),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion'),
        ),
    ]
