# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171208_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord',
            name='invite_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='username',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='invite_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='invite_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
