# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171213_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discord',
            options={'verbose_name': 'Discord Server', 'verbose_name_plural': 'Discord Servers'},
        ),
        migrations.AlterModelOptions(
            name='facebookgroup',
            options={'verbose_name': 'Facebook Group', 'verbose_name_plural': 'Facebook Groups'},
        ),
        migrations.AlterModelOptions(
            name='messengergroup',
            options={'verbose_name': 'Facebook Messenger Group', 'verbose_name_plural': 'Facebook Messenger Groups'},
        ),
        migrations.AlterModelOptions(
            name='whatsapp',
            options={'verbose_name': 'WhatsApp Group', 'verbose_name_plural': 'WhatsApp Groups'},
        ),
        migrations.AlterField(
            model_name='discord',
            name='description',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='enhanced',
            field=models.BooleanField(default=False, verbose_name='Enhanced'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='description',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='description',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='description',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer.Faction', verbose_name='Team'),
        ),
    ]
