# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171201_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord',
            name='invite_slug',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basecommunity',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
