# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180103_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL, verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL, verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District', verbose_name='Districts'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='discord',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion', verbose_name='Subregions'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL, verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL, verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District', verbose_name='Districts'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion', verbose_name='Subregions'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL, verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL, verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District', verbose_name='Districts'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='messengergroup',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion', verbose_name='Subregions'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='cities',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL, verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='countries',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_COUNTRY_MODEL, verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cities.District', verbose_name='Districts'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities.Region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='subregions',
            field=models.ManyToManyField(blank=True, to='cities.Subregion', verbose_name='Subregions'),
        ),
    ]
