# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171209_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='locations',
        ),
    ]
