# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180104_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='subregions',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='team',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='subregions',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='team',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='subregions',
        ),
        migrations.RemoveField(
            model_name='messengergroup',
            name='team',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='subregions',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='team',
        ),
        migrations.DeleteModel(
            name='Discord',
        ),
        migrations.DeleteModel(
            name='FacebookGroup',
        ),
        migrations.DeleteModel(
            name='MessengerGroup',
        ),
        migrations.DeleteModel(
            name='WhatsApp',
        ),
    ]
