# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20171203_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('basecommunity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.BaseCommunity')),
                ('invite_slug', models.CharField(max_length=256)),
                ('extra_data', models.TextField(blank=True)),
            ],
            bases=('website.basecommunity',),
        ),
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('basecommunity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.BaseCommunity')),
                ('invite_slug', models.CharField(max_length=256)),
                ('extra_data', models.TextField(blank=True)),
            ],
            bases=('website.basecommunity',),
        ),
    ]
