# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_facebookgroup_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecommunity',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='discord',
            name='identifier',
        ),
    ]
