# Generated by Django 2.1.3 on 2018-12-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguild",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
