# Generated by Django 2.1.4 on 2018-12-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20181208_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguildchannel",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="core.DiscordGuild",
            ),
        ),
        migrations.AlterField(
            model_name="discordguildrole",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.DiscordGuild",
            ),
        ),
    ]
