# Generated by Django 2.1.10 on 2019-11-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20191024_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="options_xp_gains_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.DiscordChannel",
            ),
        ),
    ]
