# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:53
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faction_name', models.CharField(max_length=140)),
                ('faction_colour', models.IntegerField()),
                ('faction_image', models.ImageField(blank=True, null=True, upload_to=api.models.factionImagePath)),
                ('leader_name', models.CharField(max_length=140)),
            ],
        ),
    ]
