# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170821_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Levels',
            fields=[
                ('level', models.AutoField(primary_key=True, serialize=False)),
                ('min_total_xp', models.IntegerField()),
                ('relative_xp', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='factions',
            name='faction_image',
        ),
    ]
