# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170821_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('discord_id', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('has_cheated', models.BooleanField(default=False)),
                ('last_cheated', models.DateField(blank=True, null=True)),
                ('currently_cheats', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('real_name', models.CharField(blank=True, max_length=256, null=True)),
                ('statistics', models.BooleanField(default=True)),
                ('daily_goal', models.IntegerField(blank=True, null=True)),
                ('total_goal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='factions',
            name='faction_colour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factions',
            name='leader_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='trainer_levels',
            name='min_total_xp',
            field=models.IntegerField(blank=True),
        ),
    ]
