# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170821_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discordian',
            fields=[
                ('d_name', models.CharField(max_length=32)),
                ('d_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('d_discriminator', models.CharField(max_length=256)),
                ('d_avatar_url', models.URLField()),
                ('d_creation', models.DateTimeField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('real_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discordian_On_Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('ban', models.BooleanField(default=False)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Discordian')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(verbose_name='Total XP')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('s_name', models.CharField(max_length=256)),
                ('s_region', models.CharField(max_length=256)),
                ('s_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('s_icon', models.CharField(max_length=256)),
                ('bans_cheaters', models.BooleanField(default=True)),
                ('seg_cheaters', models.BooleanField(default=False)),
                ('bans_minors', models.BooleanField(default=False)),
                ('seg_minors', models.BooleanField(default=False)),
                ('s_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Discordian')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='real_name',
        ),
        migrations.AddField(
            model_name='trainers',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='discord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Discordian'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trainers', to_field='username'),
        ),
        migrations.AddField(
            model_name='discordian_on_servers',
            name='d_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Servers'),
        ),
    ]
