# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170821_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainers',
            new_name='Trainer',
        ),
    ]
