# Generated by Django 3.2.10 on 2021-12-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ['-post_dt'], 'verbose_name': 'Feed Post', 'verbose_name_plural': 'Feed Posts'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_verify', 'Can verify users'), ('can_ban', 'Can ban users'), ('can_unban', 'Can unban users'), ('can_view_private_profile', 'Can view private profiles'), ('can_view_public_profile', 'Can view public profiles')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
