# Generated by Django 3.0.7 on 2020-06-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0002_add_factions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainercode',
            options={'permissions': [('share_trainer_code_to_groups', "Trainer Code can be seen by users of groups they're in"), ('share_trainer_code_to_web', 'Trainer Code can be seen on the web, publicly'), ('share_trainer_code_to_api', 'Trainer Code can be on the API')], 'verbose_name': 'Trainer Code', 'verbose_name_plural': 'Trainer Codes'},
        ),
        migrations.RemoveField(
            model_name='trainercode',
            name='privacy_setting',
        ),
    ]
