# Generated by Django 3.0 on 2020-06-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trainerdex', '0002_auto_20200614_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_field', models.CharField(choices=[('Trainer.profile', 'Trainer'), ('Update.uuid', 'Update.uuid'), ('Update.trainer', 'Update.Trainer'), ('Update.update_time', 'Update.Time Updated'), ('Update.submission_date', 'Update.Submission Datetime'), ('Update.data_source', 'Update.Source'), ('Update.total_xp', 'Update.Total XP'), ('Update.pokedex_total_caught', 'Update.Unique Species Caught'), ('Update.pokedex_total_seen', 'Update.Unique Species Seen'), ('Update.pokedex_gen1', 'Update.Kanto'), ('Update.pokedex_gen2', 'Update.Johto'), ('Update.pokedex_gen3', 'Update.Hoenn'), ('Update.pokedex_gen4', 'Update.Sinnoh'), ('Update.pokedex_gen5', 'Update.Unova'), ('Update.pokedex_gen6', 'Update.Kalos'), ('Update.pokedex_gen7', 'Update.Alola'), ('Update.pokedex_gen8', 'Update.Galar'), ('Update.travel_km', 'Update.Jogger | Distance Walked'), ('Update.capture_total', 'Update.Collector | Pokémon Caught'), ('Update.evolved_total', 'Update.Scientist'), ('Update.hatched_total', 'Update.Breeder'), ('Update.pokestops_visited', 'Update.Backpacker | PokéStops Visited'), ('Update.big_magikarp', 'Update.Fisherman'), ('Update.battle_attack_won', 'Update.Battle Girl'), ('Update.battle_training_won', 'Update.Ace Trainer'), ('Update.small_rattata', 'Update.Youngster'), ('Update.pikachu', 'Update.Pikachu Fan'), ('Update.unown', 'Update.Unown'), ('Update.raid_battle_won', 'Update.Champion'), ('Update.legendary_battle_won', 'Update.Battle Legend'), ('Update.berries_fed', 'Update.Berry Master'), ('Update.hours_defended', 'Update.Gym Leader'), ('Update.challenge_quests', 'Update.Pokémon Ranger'), ('Update.max_level_friends', 'Update.Idol'), ('Update.trading', 'Update.Gentleman'), ('Update.trading_distance', 'Update.Pilot'), ('Update.great_league', 'Update.Great League Veteran'), ('Update.ultra_league', 'Update.Ultra League Veteran'), ('Update.master_league', 'Update.Master League Veteran'), ('Update.photobomb', 'Update.Cameraman'), ('Update.pokemon_purified', 'Update.Purifier'), ('Update.rocket_grunts_defeated', 'Update.Hero'), ('Update.buddy_best', 'Update.Best Buddy'), ('Update.wayfarer', 'Update.Wayfarer'), ('Update.type_normal', 'Update.Schoolkid'), ('Update.type_fighting', 'Update.Black Belt'), ('Update.type_flying', 'Update.Bird Keeper'), ('Update.type_poison', 'Update.Punk Girl'), ('Update.type_ground', 'Update.Ruin Maniac'), ('Update.type_rock', 'Update.Hiker'), ('Update.type_bug', 'Update.Bug Catcher'), ('Update.type_ghost', 'Update.Hex Maniac'), ('Update.type_steel', 'Update.Depot Agent'), ('Update.type_fire', 'Update.Kindler'), ('Update.type_water', 'Update.Swimmer'), ('Update.type_grass', 'Update.Gardener'), ('Update.type_electric', 'Update.Rocker'), ('Update.type_psychic', 'Update.Psychic'), ('Update.type_ice', 'Update.Skier'), ('Update.type_dragon', 'Update.Dragon Tamer'), ('Update.type_dark', 'Update.Delinquent'), ('Update.type_fairy', 'Update.Fairy Tale Girl'), ('Update.gymbadges_total', 'Update.Gym Badges'), ('Update.gymbadges_gold', 'Update.Gold Gym Badges'), ('Update.stardust', 'Update.Stardust')], max_length=200)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'trainerdex'), ('model__in', ['trainer', 'update'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='update',
            name='double_check_confirmation',
        ),
        migrations.AddField(
            model_name='update',
            name='buddy_best',
            field=models.PositiveIntegerField(blank=True, help_text='Have 100 Best Buddies.', null=True, verbose_name='Best Buddy'),
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trainerdex.Evidence')),
            ],
        ),
    ]
