# Generated by Django 3.0.7 on 2020-06-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200620_1839'),
        ('trainerdex', '0003_auto_20200615_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='content_field',
            field=models.CharField(choices=[('trainer.profile', 'Trainer'), ('update.uuid', 'Update.uuid'), ('update.trainer', 'Update.Trainer'), ('update.update_time', 'Update.Time Updated'), ('update.submission_date', 'Update.Submission Datetime'), ('update.data_source', 'Update.Source'), ('update.total_xp', 'Update.Total XP'), ('update.pokedex_total_caught', 'Update.Unique Species Caught'), ('update.pokedex_total_seen', 'Update.Unique Species Seen'), ('update.pokedex_gen1', 'Update.Kanto'), ('update.pokedex_gen2', 'Update.Johto'), ('update.pokedex_gen3', 'Update.Hoenn'), ('update.pokedex_gen4', 'Update.Sinnoh'), ('update.pokedex_gen5', 'Update.Unova'), ('update.pokedex_gen6', 'Update.Kalos'), ('update.pokedex_gen7', 'Update.Alola'), ('update.pokedex_gen8', 'Update.Galar'), ('update.travel_km', 'Update.Jogger | Distance Walked'), ('update.capture_total', 'Update.Collector | Pokémon Caught'), ('update.evolved_total', 'Update.Scientist'), ('update.hatched_total', 'Update.Breeder'), ('update.pokestops_visited', 'Update.Backpacker | PokéStops Visited'), ('update.big_magikarp', 'Update.Fisherman'), ('update.battle_attack_won', 'Update.Battle Girl'), ('update.battle_training_won', 'Update.Ace Trainer'), ('update.small_rattata', 'Update.Youngster'), ('update.pikachu', 'Update.Pikachu Fan'), ('update.unown', 'Update.Unown'), ('update.raid_battle_won', 'Update.Champion'), ('update.legendary_battle_won', 'Update.Battle Legend'), ('update.berries_fed', 'Update.Berry Master'), ('update.hours_defended', 'Update.Gym Leader'), ('update.challenge_quests', 'Update.Pokémon Ranger'), ('update.max_level_friends', 'Update.Idol'), ('update.trading', 'Update.Gentleman'), ('update.trading_distance', 'Update.Pilot'), ('update.great_league', 'Update.Great League Veteran'), ('update.ultra_league', 'Update.Ultra League Veteran'), ('update.master_league', 'Update.Master League Veteran'), ('update.photobomb', 'Update.Cameraman'), ('update.pokemon_purified', 'Update.Purifier'), ('update.rocket_grunts_defeated', 'Update.Hero'), ('update.buddy_best', 'Update.Best Buddy'), ('update.wayfarer', 'Update.Wayfarer'), ('update.type_normal', 'Update.Schoolkid'), ('update.type_fighting', 'Update.Black Belt'), ('update.type_flying', 'Update.Bird Keeper'), ('update.type_poison', 'Update.Punk Girl'), ('update.type_ground', 'Update.Ruin Maniac'), ('update.type_rock', 'Update.Hiker'), ('update.type_bug', 'Update.Bug Catcher'), ('update.type_ghost', 'Update.Hex Maniac'), ('update.type_steel', 'Update.Depot Agent'), ('update.type_fire', 'Update.Kindler'), ('update.type_water', 'Update.Swimmer'), ('update.type_grass', 'Update.Gardener'), ('update.type_electric', 'Update.Rocker'), ('update.type_psychic', 'Update.Psychic'), ('update.type_ice', 'Update.Skier'), ('update.type_dragon', 'Update.Dragon Tamer'), ('update.type_dark', 'Update.Delinquent'), ('update.type_fairy', 'Update.Fairy Tale Girl'), ('update.gymbadges_total', 'Update.Gym Badges'), ('update.gymbadges_gold', 'Update.Gold Gym Badges'), ('update.stardust', 'Update.Stardust')], max_length=200),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trainer', serialize=False, to='core.HumanUser', verbose_name='User'),
        ),
    ]
