# Generated by Django 3.0.7 on 2020-06-21 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0004_auto_20200620_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerCode',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trainer_code', serialize=False, to='trainerdex.Trainer', verbose_name='TrainerCode')),
                ('code', models.CharField(blank=True, help_text='Fancy sharing your trainer code?', max_length=15, null=True, validators=[django.core.validators.RegexValidator('(\\d{4}\\s?){3}', 'Trainer Code must be 12 digits long and contain only numbers and whitespace.', 'invalid'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(15)], verbose_name='Trainer Code')),
                ('privacy_setting', models.CharField(choices=[('600', 'Private'), ('640', 'Share with groups only'), ('604', 'Share with website only'), ('644', 'Share with groups and website')], default='640', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_code',
        ),
    ]
