# Generated by Django 3.0.7 on 2020-06-21 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0005_auto_20200621_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainercode',
            name='code',
            field=models.CharField(blank=True, help_text='Fancy sharing your trainer code?', max_length=15, null=True, validators=[django.core.validators.RegexValidator('(\\d{4}[\\s\\-]?){3}', 'Trainer Code must be 12 digits long and contain only numbers and whitespace.', 'invalid'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(15)], verbose_name='Trainer Code'),
        ),
        migrations.AlterField(
            model_name='trainercode',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trainer_code', serialize=False, to='trainerdex.Trainer', verbose_name='Trainer'),
        ),
    ]
