# Generated by Django 3.0.7 on 2020-07-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0005_add_data_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['slug'], 'verbose_name': 'Data Source', 'verbose_name_plural': 'Data Souces'},
        ),
        migrations.AlterModelOptions(
            name='presettargetgroup',
            options={'verbose_name': 'target group', 'verbose_name_plural': 'target groups'},
        ),
    ]
