# Generated by Django 3.0.7 on 2020-06-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trainerdex', '0006_auto_20200621_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='object_id',
        ),
        migrations.AddField(
            model_name='evidence',
            name='object_pk',
            field=models.CharField(default='1', max_length=36, verbose_name='Object PK'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidence',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'trainerdex'), ('model__in', ['trainer', 'update'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Model'),
        ),
    ]
