# Generated by Django 3.0.7 on 2020-06-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0008_auto_20200621_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('total_xp', 'Total XP'), ('pokedex_total_caught', 'Unique Species Caught'), ('pokedex_total_seen', 'Unique Species Seen'), ('pokedex_gen1', 'Kanto'), ('pokedex_gen2', 'Johto'), ('pokedex_gen3', 'Hoenn'), ('pokedex_gen4', 'Sinnoh'), ('pokedex_gen5', 'Unova'), ('pokedex_gen6', 'Kalos'), ('pokedex_gen7', 'Alola'), ('pokedex_gen8', 'Galar'), ('travel_km', 'Jogger | Distance Walked'), ('capture_total', 'Collector | Pokémon Caught'), ('evolved_total', 'Scientist'), ('hatched_total', 'Breeder'), ('pokestops_visited', 'Backpacker | PokéStops Visited'), ('big_magikarp', 'Fisherman'), ('battle_attack_won', 'Battle Girl'), ('battle_training_won', 'Ace Trainer'), ('small_rattata', 'Youngster'), ('pikachu', 'Pikachu Fan'), ('unown', 'Unown'), ('raid_battle_won', 'Champion'), ('legendary_battle_won', 'Battle Legend'), ('berries_fed', 'Berry Master'), ('hours_defended', 'Gym Leader'), ('challenge_quests', 'Pokémon Ranger'), ('max_level_friends', 'Idol'), ('trading', 'Gentleman'), ('trading_distance', 'Pilot'), ('great_league', 'Great League Veteran'), ('ultra_league', 'Ultra League Veteran'), ('master_league', 'Master League Veteran'), ('photobomb', 'Cameraman'), ('pokemon_purified', 'Purifier'), ('rocket_grunts_defeated', 'Hero'), ('buddy_best', 'Best Buddy'), ('wayfarer', 'Wayfarer'), ('type_normal', 'Schoolkid'), ('type_fighting', 'Black Belt'), ('type_flying', 'Bird Keeper'), ('type_poison', 'Punk Girl'), ('type_ground', 'Ruin Maniac'), ('type_rock', 'Hiker'), ('type_bug', 'Bug Catcher'), ('type_ghost', 'Hex Maniac'), ('type_steel', 'Depot Agent'), ('type_fire', 'Kindler'), ('type_water', 'Swimmer'), ('type_grass', 'Gardener'), ('type_electric', 'Rocker'), ('type_psychic', 'Psychic'), ('type_ice', 'Skier'), ('type_dragon', 'Dragon Tamer'), ('type_dark', 'Delinquent'), ('type_fairy', 'Fairy Tale Girl'), ('gymbadges_total', 'Gym Badges'), ('gymbadges_gold', 'Gold Gym Badges')], max_length=22)),
                ('_target', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Target (Preset)',
                'verbose_name_plural': 'Targets (Preset)',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='evidence',
            name='content_field',
            field=models.CharField(choices=[('trainer.profile', 'Trainer'), ('update.total_xp', 'Update.Total XP'), ('update.pokedex_total_caught', 'Update.Unique Species Caught'), ('update.pokedex_total_seen', 'Update.Unique Species Seen'), ('update.pokedex_gen1', 'Update.Kanto'), ('update.pokedex_gen2', 'Update.Johto'), ('update.pokedex_gen3', 'Update.Hoenn'), ('update.pokedex_gen4', 'Update.Sinnoh'), ('update.pokedex_gen5', 'Update.Unova'), ('update.pokedex_gen6', 'Update.Kalos'), ('update.pokedex_gen7', 'Update.Alola'), ('update.pokedex_gen8', 'Update.Galar'), ('update.travel_km', 'Update.Jogger | Distance Walked'), ('update.capture_total', 'Update.Collector | Pokémon Caught'), ('update.evolved_total', 'Update.Scientist'), ('update.hatched_total', 'Update.Breeder'), ('update.pokestops_visited', 'Update.Backpacker | PokéStops Visited'), ('update.big_magikarp', 'Update.Fisherman'), ('update.battle_attack_won', 'Update.Battle Girl'), ('update.battle_training_won', 'Update.Ace Trainer'), ('update.small_rattata', 'Update.Youngster'), ('update.pikachu', 'Update.Pikachu Fan'), ('update.unown', 'Update.Unown'), ('update.raid_battle_won', 'Update.Champion'), ('update.legendary_battle_won', 'Update.Battle Legend'), ('update.berries_fed', 'Update.Berry Master'), ('update.hours_defended', 'Update.Gym Leader'), ('update.challenge_quests', 'Update.Pokémon Ranger'), ('update.max_level_friends', 'Update.Idol'), ('update.trading', 'Update.Gentleman'), ('update.trading_distance', 'Update.Pilot'), ('update.great_league', 'Update.Great League Veteran'), ('update.ultra_league', 'Update.Ultra League Veteran'), ('update.master_league', 'Update.Master League Veteran'), ('update.photobomb', 'Update.Cameraman'), ('update.pokemon_purified', 'Update.Purifier'), ('update.rocket_grunts_defeated', 'Update.Hero'), ('update.buddy_best', 'Update.Best Buddy'), ('update.wayfarer', 'Update.Wayfarer'), ('update.type_normal', 'Update.Schoolkid'), ('update.type_fighting', 'Update.Black Belt'), ('update.type_flying', 'Update.Bird Keeper'), ('update.type_poison', 'Update.Punk Girl'), ('update.type_ground', 'Update.Ruin Maniac'), ('update.type_rock', 'Update.Hiker'), ('update.type_bug', 'Update.Bug Catcher'), ('update.type_ghost', 'Update.Hex Maniac'), ('update.type_steel', 'Update.Depot Agent'), ('update.type_fire', 'Update.Kindler'), ('update.type_water', 'Update.Swimmer'), ('update.type_grass', 'Update.Gardener'), ('update.type_electric', 'Update.Rocker'), ('update.type_psychic', 'Update.Psychic'), ('update.type_ice', 'Update.Skier'), ('update.type_dragon', 'Update.Dragon Tamer'), ('update.type_dark', 'Update.Delinquent'), ('update.type_fairy', 'Update.Fairy Tale Girl'), ('update.gymbadges_total', 'Update.Gym Badges'), ('update.gymbadges_gold', 'Update.Gold Gym Badges'), ('update.stardust', 'Update.Stardust')], max_length=29),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('stat', models.CharField(choices=[('total_xp', 'Total XP'), ('pokedex_total_caught', 'Unique Species Caught'), ('pokedex_total_seen', 'Unique Species Seen'), ('pokedex_gen1', 'Kanto'), ('pokedex_gen2', 'Johto'), ('pokedex_gen3', 'Hoenn'), ('pokedex_gen4', 'Sinnoh'), ('pokedex_gen5', 'Unova'), ('pokedex_gen6', 'Kalos'), ('pokedex_gen7', 'Alola'), ('pokedex_gen8', 'Galar'), ('travel_km', 'Jogger | Distance Walked'), ('capture_total', 'Collector | Pokémon Caught'), ('evolved_total', 'Scientist'), ('hatched_total', 'Breeder'), ('pokestops_visited', 'Backpacker | PokéStops Visited'), ('big_magikarp', 'Fisherman'), ('battle_attack_won', 'Battle Girl'), ('battle_training_won', 'Ace Trainer'), ('small_rattata', 'Youngster'), ('pikachu', 'Pikachu Fan'), ('unown', 'Unown'), ('raid_battle_won', 'Champion'), ('legendary_battle_won', 'Battle Legend'), ('berries_fed', 'Berry Master'), ('hours_defended', 'Gym Leader'), ('challenge_quests', 'Pokémon Ranger'), ('max_level_friends', 'Idol'), ('trading', 'Gentleman'), ('trading_distance', 'Pilot'), ('great_league', 'Great League Veteran'), ('ultra_league', 'Ultra League Veteran'), ('master_league', 'Master League Veteran'), ('photobomb', 'Cameraman'), ('pokemon_purified', 'Purifier'), ('rocket_grunts_defeated', 'Hero'), ('buddy_best', 'Best Buddy'), ('wayfarer', 'Wayfarer'), ('type_normal', 'Schoolkid'), ('type_fighting', 'Black Belt'), ('type_flying', 'Bird Keeper'), ('type_poison', 'Punk Girl'), ('type_ground', 'Ruin Maniac'), ('type_rock', 'Hiker'), ('type_bug', 'Bug Catcher'), ('type_ghost', 'Hex Maniac'), ('type_steel', 'Depot Agent'), ('type_fire', 'Kindler'), ('type_water', 'Swimmer'), ('type_grass', 'Gardener'), ('type_electric', 'Rocker'), ('type_psychic', 'Psychic'), ('type_ice', 'Skier'), ('type_dragon', 'Dragon Tamer'), ('type_dark', 'Delinquent'), ('type_fairy', 'Fairy Tale Girl'), ('gymbadges_total', 'Gym Badges'), ('gymbadges_gold', 'Gold Gym Badges')], max_length=22)),
                ('_target', models.CharField(max_length=16)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerdex.Trainer', verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresetTargetGroup',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('children', models.ManyToManyField(to='trainerdex.PresetTarget')),
            ],
            options={
                'verbose_name': 'Group of Targets',
                'verbose_name_plural': 'Groups of Targets',
            },
        ),
    ]
