from datetime import date, timedelta
from distutils.util import strtobool
from typing import Dict, List, Optional, Union

from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.utils.translation import pgettext as _


def strtoboolornone(value) -> Union[bool, None]:
    try:
        return strtobool(value)
    except (ValueError, AttributeError):
        return None


# Bans are supposed to last 6 months, the change was made on 2018-09-01.
# However, my code has been bugged and since I never checked in on cheaters, since they mostly left
# I never spotted the bug. Given the SARS-COVID-19 outbreak, I've decided to reduce punishment time
# within that time period to TWELVE weeks. I have also decided to extend the 6 month period to
# before 2018-09-01, since it's a little unfair.

COVID_START = date(2019, 12, 31)
COVID_END = date(2021, 12, 31)  # 2 years in generous, adjust to suit


def filter_leaderboard_qs(queryset, d: date = None):
    base_adjustments = (
        queryset.exclude(owner__is_active=False)
        .exclude(statistics=False)
        .exclude(update__isnull=True)
        .exclude(verified=False)
    )
    d = d or timezone.now().date()

    if COVID_START < d < COVID_START + timedelta(weeks=26):
        # exclude those who cheated within the past 26 weeks
        # if that date is before the start of the pandemic
        # exclude all those who cheated with the past 12 weeks
        return base_adjustments.exclude(
            last_cheated__gte=d - timedelta(weeks=26), last_cheated__lt=COVID_START
        ).exclude(last_cheated__gte=d - timedelta(weeks=12))
    elif COVID_START < d < COVID_END + timedelta(weeks=12):
        # exclude all those who cheated with the past 12 weeks
        # even thought the ban policy after COVID_END is 26 weeks, this code will only trigger
        # within the pandemic and 12 weeks after. This means we don't have to have SQL exceptions
        # for those who cheat just after the end of the pandemic
        return base_adjustments.exclude(last_cheated__gte=d - timedelta(weeks=12))
    else:
        # Everyone else, 26 weeks, dirty bugger
        return base_adjustments.exclude(last_cheated__gte=timedelta(weeks=26))


def filter_leaderboard_qs__update(queryset, d: date = None):
    base_adjustments = (
        queryset.exclude(trainer__owner__is_active=False)
        .exclude(trainer__statistics=False)
        .exclude(trainer__verified=False)
        .exclude(
            update_time__lt=(
                timezone.now() - relativedelta(months=3, hour=0, minute=0, second=0, microsecond=0)
            )
        )
    )
    d = d or timezone.now().date()

    if COVID_START < d < COVID_START + timedelta(weeks=26):
        # exclude those who cheated within the past 26 weeks
        # if that date is before the start of the pandemic
        # exclude all those who cheated with the past 12 weeks
        return base_adjustments.exclude(
            trainer__last_cheated__gte=d - timedelta(weeks=26),
            trainer__last_cheated__lt=COVID_START,
        ).exclude(trainer__last_cheated__gte=d - timedelta(weeks=12))
    elif COVID_START < d < COVID_END + timedelta(weeks=12):
        # exclude all those who cheated with the past 12 weeks
        # even thought the ban policy after COVID_END is 26 weeks, this code will only trigger
        # within the pandemic and 12 weeks after. This means we don't have to have SQL exceptions
        # for those who cheat just after the end of the pandemic
        return base_adjustments.exclude(trainer__last_cheated__gte=d - timedelta(weeks=12))
    else:
        # Everyone else, 26 weeks, dirty bugger
        return base_adjustments.exclude(trainer__last_cheated__gte=timedelta(weeks=26))


class Level:
    def __init__(
        self,
        level: int,
        total_xp: int,
        xp_required: Optional[int] = None,
        quest_requirements: Optional[List[Dict[str, str]]] = None,
    ) -> None:
        self.level = level
        self.total_xp = total_xp
        self.xp_required = xp_required
        self.quest_requirements = quest_requirements

    def requirements_to_reach(self) -> Dict[str, Union[int, Dict[str, str]]]:
        return {"total_xp": self.total_xp, "quests": self.quest_requirements}

    @property
    def needs_quests(self) -> bool:
        return self.quest_requirements is not None

    def __str__(self) -> str:
        level_term = _("profile_player_level", "Level")
        return f"{level_term} {self.level}"

    def id(self) -> int:
        return self.level


LEVELS: List[Level] = [
    Level(level=1, total_xp=0, xp_required=1000),
    Level(level=2, total_xp=1000, xp_required=2000),
    Level(level=3, total_xp=3000, xp_required=3000),
    Level(level=4, total_xp=6000, xp_required=4000),
    Level(level=5, total_xp=10_000, xp_required=5000),
    Level(level=6, total_xp=15_000, xp_required=6000),
    Level(level=7, total_xp=21_000, xp_required=7000),
    Level(level=8, total_xp=28_000, xp_required=8000),
    Level(level=9, total_xp=36_000, xp_required=9000),
    Level(level=10, total_xp=45_000, xp_required=10_000),
    Level(level=11, total_xp=55_000, xp_required=10_000),
    Level(level=12, total_xp=65_000, xp_required=10_000),
    Level(level=13, total_xp=75_000, xp_required=10_000),
    Level(level=14, total_xp=85_000, xp_required=15_000),
    Level(level=15, total_xp=100_000, xp_required=20_000),
    Level(level=16, total_xp=120_000, xp_required=20_000),
    Level(level=17, total_xp=140_000, xp_required=20_000),
    Level(level=18, total_xp=160_000, xp_required=25_000),
    Level(level=19, total_xp=185_000, xp_required=25_000),
    Level(level=20, total_xp=210_000, xp_required=50_000),
    Level(level=21, total_xp=260_000, xp_required=75_000),
    Level(level=22, total_xp=335_000, xp_required=100_000),
    Level(level=23, total_xp=435_000, xp_required=125_000),
    Level(level=24, total_xp=560_000, xp_required=150_000),
    Level(level=25, total_xp=710_000, xp_required=190_000),
    Level(level=26, total_xp=900_000, xp_required=200_000),
    Level(level=27, total_xp=1_100_000, xp_required=250_000),
    Level(level=28, total_xp=1_350_000, xp_required=300_000),
    Level(level=29, total_xp=1_650_000, xp_required=350_000),
    Level(level=30, total_xp=2_000_000, xp_required=500_000),
    Level(level=31, total_xp=2_500_000, xp_required=500_000),
    Level(level=32, total_xp=3_000_000, xp_required=750_000),
    Level(level=33, total_xp=3_750_000, xp_required=1_000_000),
    Level(level=34, total_xp=4_750_000, xp_required=1_250_000),
    Level(level=35, total_xp=6_000_000, xp_required=1_500_000),
    Level(level=36, total_xp=7_500_000, xp_required=2_000_000),
    Level(level=37, total_xp=9_500_000, xp_required=2_500_000),
    Level(level=38, total_xp=12_000_000, xp_required=3_000_000),
    Level(level=39, total_xp=15_000_000, xp_required=5_000_000),
    Level(level=40, total_xp=20_000_000, xp_required=6_000_000),
    Level(level=41, total_xp=26_000_000, xp_required=7_500_000),
    Level(level=42, total_xp=33_500_000, xp_required=9_000_000),
    Level(level=43, total_xp=42_500_000, xp_required=11_000_000),
    Level(level=44, total_xp=53_500_000, xp_required=13_000_000),
    Level(level=45, total_xp=66_500_000, xp_required=15_500_000),
    Level(level=46, total_xp=82_000_000, xp_required=18_000_000),
    Level(level=47, total_xp=100_000_000, xp_required=21_000_000),
    Level(level=48, total_xp=121_000_000, xp_required=25_000_000),
    Level(level=49, total_xp=146_000_000, xp_required=30_000_000),
    Level(level=50, total_xp=176_000_000, xp_required=None),
]


def get_possible_levels_from_total_xp(xp: int) -> List[Level]:
    if xp < LEVELS[40].total_xp:
        possible_levels = [
            x
            for x in filter(
                lambda x: x.total_xp <= xp
                and (x.total_xp + x.xp_required > xp if x.xp_required else True),
                LEVELS,
            )
        ]
    else:
        possible_levels = [
            x
            for x in filter(
                lambda x: 20_000_000 <= x.total_xp <= xp,
                LEVELS,
            )
        ]

    return possible_levels


def get_level(level: int) -> Level:
    if level <= len(LEVELS):
        return LEVELS[level - 1]
    else:
        raise ValueError


STANDARD_MEDALS = [
    "badge_travel_km",
    "badge_pokedex_entries",
    "badge_capture_total",
    "badge_evolved_total",
    "badge_hatched_total",
    "badge_pokestops_visited",
    "badge_unique_pokestops",
    "badge_big_magikarp",
    "badge_battle_attack_won",
    "badge_battle_training_won",
    "badge_small_rattata",
    "badge_pikachu",
    "badge_unown",
    "badge_pokedex_entries_gen2",
    "badge_raid_battle_won",
    "badge_legendary_battle_won",
    "badge_berries_fed",
    "badge_hours_defended",
    "badge_pokedex_entries_gen3",
    "badge_challenge_quests",
    "badge_max_level_friends",
    "badge_trading",
    "badge_trading_distance",
    "badge_pokedex_entries_gen4",
    "badge_great_league",
    "badge_ultra_league",
    "badge_master_league",
    "badge_photobomb",
    "badge_pokedex_entries_gen5",
    "badge_pokemon_purified",
    "badge_rocket_grunts_defeated",
    "badge_rocket_giovanni_defeated",
    "badge_buddy_best",
    "badge_pokedex_entries_gen6",
    "badge_7_day_streaks",
    "badge_unique_raid_bosses_defeated",
    "badge_raids_with_friends",
    "badge_pokemon_caught_at_your_lures",
    "badge_wayfarer",
    "badge_total_mega_evos",
    "badge_unique_mega_evos",
]

BATTLE_HUB_STATS = [
    "battle_hub_stats_wins",
    "battle_hub_stats_battles",
    "battle_hub_stats_stardust",
    "battle_hub_stats_streak",
]

UPDATE_FIELDS_BADGES = STANDARD_MEDALS + BATTLE_HUB_STATS

UPDATE_FIELDS_TYPES = [
    "badge_type_normal",
    "badge_type_fighting",
    "badge_type_flying",
    "badge_type_poison",
    "badge_type_ground",
    "badge_type_rock",
    "badge_type_bug",
    "badge_type_ghost",
    "badge_type_steel",
    "badge_type_fire",
    "badge_type_water",
    "badge_type_grass",
    "badge_type_electric",
    "badge_type_psychic",
    "badge_type_ice",
    "badge_type_dragon",
    "badge_type_dark",
    "badge_type_fairy",
]

UPDATE_SORTABLE_FIELDS = (
    [
        "total_xp",
        "pokedex_caught",
        "pokedex_seen",
        "gymbadges_gold",
    ]
    + UPDATE_FIELDS_BADGES
    + UPDATE_FIELDS_TYPES
)

UPDATE_NON_REVERSEABLE_FIELDS = (
    [
        "total_xp",
        "pokedex_caught",
        "pokedex_seen",
    ]
    + UPDATE_FIELDS_BADGES
    + UPDATE_FIELDS_TYPES
)

BADGES = [
    {
        "id": 1,
        "name": "badge_travel_km",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 10000,
    },
    {
        "id": 2,
        "name": "badge_pokedex_entries",
        "bronze": 5,
        "silver": 50,
        "gold": 100,
        "platinum": 151,
    },
    {
        "id": 3,
        "name": "badge_capture_total",
        "bronze": 30,
        "silver": 500,
        "gold": 2000,
        "platinum": 50000,
    },
    {
        "id": 5,
        "name": "badge_evolved_total",
        "bronze": 3,
        "silver": 20,
        "gold": 200,
        "platinum": 2000,
    },
    {
        "id": 6,
        "name": "badge_hatched_total",
        "bronze": 10,
        "silver": 100,
        "gold": 500,
        "platinum": 2500,
    },
    {
        "id": 8,
        "name": "badge_pokestops_visited",
        "bronze": 100,
        "silver": 1000,
        "gold": 2000,
        "platinum": 50000,
    },
    {
        "id": 9,
        "name": "badge_unique_pokestops",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 11,
        "name": "badge_big_magikarp",
        "bronze": 3,
        "silver": 50,
        "gold": 300,
        "platinum": 1000,
    },
    {
        "id": 13,
        "name": "badge_battle_attack_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 4000,
    },
    {
        "id": 14,
        "name": "badge_battle_training_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 36,
        "name": "badge_small_rattata",
        "bronze": 3,
        "silver": 50,
        "gold": 300,
        "platinum": 1000,
    },
    {
        "id": 37,
        "name": "badge_pikachu",
        "bronze": 3,
        "silver": 50,
        "gold": 300,
        "platinum": 1000,
    },
    {
        "id": 38,
        "name": "badge_unown",
        "bronze": 3,
        "silver": 10,
        "gold": 26,
        "platinum": 28,
    },
    {
        "id": 39,
        "name": "badge_pokedex_entries_gen2",
        "bronze": 3,
        "silver": 10,
        "gold": 26,
        "platinum": 100,
    },
    {
        "id": 40,
        "name": "badge_raid_battle_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 41,
        "name": "badge_legendary_battle_won",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 42,
        "name": "badge_berries_fed",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 15000,
    },
    {
        "id": 43,
        "name": "badge_hours_defended",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 15000,
    },
    {
        "id": 45,
        "name": "badge_pokedex_entries_gen3",
        "bronze": 5,
        "silver": 40,
        "gold": 90,
        "platinum": 135,
    },
    {
        "id": 46,
        "name": "badge_challenge_quests",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2500,
    },
    {
        "id": 48,
        "name": "badge_max_level_friends",
        "bronze": 1,
        "silver": 2,
        "gold": 3,
        "platinum": 20,
    },
    {
        "id": 49,
        "name": "badge_trading",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2500,
    },
    {
        "id": 50,
        "name": "badge_trading_distance",
        "bronze": 1000,
        "silver": 10000,
        "gold": 1000000,
        "platinum": 10000000,
    },
    {
        "id": 51,
        "name": "badge_pokedex_entries_gen4",
        "bronze": 5,
        "silver": 30,
        "gold": 80,
        "platinum": 107,
    },
    {
        "id": 52,
        "name": "badge_great_league",
        "bronze": 5,
        "silver": 50,
        "gold": 200,
        "platinum": 1000,
    },
    {
        "id": 53,
        "name": "badge_ultra_league",
        "bronze": 5,
        "silver": 50,
        "gold": 200,
        "platinum": 1000,
    },
    {
        "id": 54,
        "name": "badge_master_league",
        "bronze": 5,
        "silver": 50,
        "gold": 200,
        "platinum": 1000,
    },
    {
        "id": 55,
        "name": "badge_photobomb",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 400,
    },
    {
        "id": 56,
        "name": "badge_pokedex_entries_gen5",
        "bronze": 5,
        "silver": 50,
        "gold": 100,
        "platinum": 156,
    },
    {
        "id": 57,
        "name": "badge_pokemon_purified",
        "bronze": 5,
        "silver": 50,
        "gold": 500,
        "platinum": 1000,
    },
    {
        "id": 58,
        "name": "badge_rocket_grunts_defeated",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 59,
        "name": "badge_rocket_giovanni_defeated",
        "bronze": 1,
        "silver": 5,
        "gold": 20,
        "platinum": 50,
    },
    {
        "id": 60,
        "name": "badge_buddy_best",
        "bronze": 1,
        "silver": 10,
        "gold": 100,
        "platinum": 2000,
    },
    {
        "id": 61,
        "name": "badge_pokedex_entries_gen6",
        "bronze": 5,
        "silver": 25,
        "gold": 50,
        "platinum": 72,
    },
    {
        "id": 64,
        "name": "badge_7_day_streaks",
        "bronze": 1,
        "silver": 10,
        "gold": 50,
        "platinum": 100,
    },
    {
        "id": 65,
        "name": "badge_unique_raid_bosses_defeated",
        "bronze": 2,
        "silver": 10,
        "gold": 50,
        "platinum": 150,
    },
    {
        "id": 66,
        "name": "badge_raids_with_friends",
        "bronze": 10,
        "silver": 100,
        "gold": 1000,
        "platinum": 2000,
    },
    {
        "id": 67,
        "name": "badge_pokemon_caught_at_your_lures",
        "bronze": 5,
        "silver": 25,
        "gold": 500,
        "platinum": 2000,
    },
    {
        "id": 68,
        "name": "badge_wayfarer",
        "bronze": 50,
        "silver": 500,
        "gold": 1000,
        "platinum": 1500,
    },
    {
        "id": 69,
        "name": "badge_total_mega_evos",
        "bronze": 1,
        "silver": 50,
        "gold": 500,
        "platinum": 1000,
    },
    {
        "id": 70,
        "name": "badge_unique_mega_evos",
        "bronze": 1,
        "silver": 24,
        "gold": 36,
        "platinum": 46,
    },
    {
        "id": 18,
        "name": "badge_type_normal",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 19,
        "name": "badge_type_fighting",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 20,
        "name": "badge_type_flying",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 21,
        "name": "badge_type_poison",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 22,
        "name": "badge_type_ground",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 23,
        "name": "badge_type_rock",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 24,
        "name": "badge_type_bug",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 25,
        "name": "badge_type_ghost",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 26,
        "name": "badge_type_steel",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 27,
        "name": "badge_type_fire",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 28,
        "name": "badge_type_water",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 29,
        "name": "badge_type_grass",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 30,
        "name": "badge_type_electric",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 31,
        "name": "badge_type_psychic",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 32,
        "name": "badge_type_ice",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 33,
        "name": "badge_type_dragon",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 34,
        "name": "badge_type_dark",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
    {
        "id": 35,
        "name": "badge_type_fairy",
        "bronze": 10,
        "silver": 50,
        "gold": 200,
        "platinum": 2500,
    },
]


def circled_level(i: int) -> str:
    numbers = [
        9312,
        9313,
        9314,
        9315,
        9316,
        9317,
        9318,
        9319,
        9320,
        9321,
        9322,
        9323,
        9324,
        9325,
        9326,
        9327,
        9328,
        9329,
        9330,
        9331,
        12881,
        12882,
        12883,
        12884,
        12885,
        12886,
        12887,
        12888,
        12889,
        12890,
        12891,
        12892,
        12893,
        12894,
        12895,
        12977,
        12978,
        12979,
        12980,
        12981,
        12982,
        12983,
        12984,
        12985,
        12986,
        12987,
        12988,
        12989,
        12990,
        12991,
    ]

    if i <= 0:
        return ""
    try:
        return chr(numbers[i - 1])
    except IndexError:
        return ""


def get_country_info(country_code: str) -> Dict:
    data = [
        {
            "code": "AD",
            "emoji": "🇦🇩",
            "unicode": "U+1F1E6 U+1F1E9",
            "name": "Andorra",
            "title": "flag for Andorra",
        },
        {
            "code": "AE",
            "emoji": "🇦🇪",
            "unicode": "U+1F1E6 U+1F1EA",
            "name": "United Arab Emirates",
            "title": "flag for United Arab Emirates",
        },
        {
            "code": "AF",
            "emoji": "🇦🇫",
            "unicode": "U+1F1E6 U+1F1EB",
            "name": "Afghanistan",
            "title": "flag for Afghanistan",
        },
        {
            "code": "AG",
            "emoji": "🇦🇬",
            "unicode": "U+1F1E6 U+1F1EC",
            "name": "Antigua and Barbuda",
            "title": "flag for Antigua and Barbuda",
        },
        {
            "code": "AI",
            "emoji": "🇦🇮",
            "unicode": "U+1F1E6 U+1F1EE",
            "name": "Anguilla",
            "title": "flag for Anguilla",
        },
        {
            "code": "AL",
            "emoji": "🇦🇱",
            "unicode": "U+1F1E6 U+1F1F1",
            "name": "Albania",
            "title": "flag for Albania",
        },
        {
            "code": "AM",
            "emoji": "🇦🇲",
            "unicode": "U+1F1E6 U+1F1F2",
            "name": "Armenia",
            "title": "flag for Armenia",
        },
        {
            "code": "AO",
            "emoji": "🇦🇴",
            "unicode": "U+1F1E6 U+1F1F4",
            "name": "Angola",
            "title": "flag for Angola",
        },
        {
            "code": "AQ",
            "emoji": "🇦🇶",
            "unicode": "U+1F1E6 U+1F1F6",
            "name": "Antarctica",
            "title": "flag for Antarctica",
        },
        {
            "code": "AR",
            "emoji": "🇦🇷",
            "unicode": "U+1F1E6 U+1F1F7",
            "name": "Argentina",
            "title": "flag for Argentina",
        },
        {
            "code": "AS",
            "emoji": "🇦🇸",
            "unicode": "U+1F1E6 U+1F1F8",
            "name": "American Samoa",
            "title": "flag for American Samoa",
        },
        {
            "code": "AT",
            "emoji": "🇦🇹",
            "unicode": "U+1F1E6 U+1F1F9",
            "name": "Austria",
            "title": "flag for Austria",
        },
        {
            "code": "AU",
            "emoji": "🇦🇺",
            "unicode": "U+1F1E6 U+1F1FA",
            "name": "Australia",
            "title": "flag for Australia",
        },
        {
            "code": "AW",
            "emoji": "🇦🇼",
            "unicode": "U+1F1E6 U+1F1FC",
            "name": "Aruba",
            "title": "flag for Aruba",
        },
        {
            "code": "AX",
            "emoji": "🇦🇽",
            "unicode": "U+1F1E6 U+1F1FD",
            "name": "Åland Islands",
            "title": "flag for Åland Islands",
        },
        {
            "code": "AZ",
            "emoji": "🇦🇿",
            "unicode": "U+1F1E6 U+1F1FF",
            "name": "Azerbaijan",
            "title": "flag for Azerbaijan",
        },
        {
            "code": "BA",
            "emoji": "🇧🇦",
            "unicode": "U+1F1E7 U+1F1E6",
            "name": "Bosnia and Herzegovina",
            "title": "flag for Bosnia and Herzegovina",
        },
        {
            "code": "BB",
            "emoji": "🇧🇧",
            "unicode": "U+1F1E7 U+1F1E7",
            "name": "Barbados",
            "title": "flag for Barbados",
        },
        {
            "code": "BD",
            "emoji": "🇧🇩",
            "unicode": "U+1F1E7 U+1F1E9",
            "name": "Bangladesh",
            "title": "flag for Bangladesh",
        },
        {
            "code": "BE",
            "emoji": "🇧🇪",
            "unicode": "U+1F1E7 U+1F1EA",
            "name": "Belgium",
            "title": "flag for Belgium",
        },
        {
            "code": "BF",
            "emoji": "🇧🇫",
            "unicode": "U+1F1E7 U+1F1EB",
            "name": "Burkina Faso",
            "title": "flag for Burkina Faso",
        },
        {
            "code": "BG",
            "emoji": "🇧🇬",
            "unicode": "U+1F1E7 U+1F1EC",
            "name": "Bulgaria",
            "title": "flag for Bulgaria",
        },
        {
            "code": "BH",
            "emoji": "🇧🇭",
            "unicode": "U+1F1E7 U+1F1ED",
            "name": "Bahrain",
            "title": "flag for Bahrain",
        },
        {
            "code": "BI",
            "emoji": "🇧🇮",
            "unicode": "U+1F1E7 U+1F1EE",
            "name": "Burundi",
            "title": "flag for Burundi",
        },
        {
            "code": "BJ",
            "emoji": "🇧🇯",
            "unicode": "U+1F1E7 U+1F1EF",
            "name": "Benin",
            "title": "flag for Benin",
        },
        {
            "code": "BL",
            "emoji": "🇧🇱",
            "unicode": "U+1F1E7 U+1F1F1",
            "name": "Saint Barthélemy",
            "title": "flag for Saint Barthélemy",
        },
        {
            "code": "BM",
            "emoji": "🇧🇲",
            "unicode": "U+1F1E7 U+1F1F2",
            "name": "Bermuda",
            "title": "flag for Bermuda",
        },
        {
            "code": "BN",
            "emoji": "🇧🇳",
            "unicode": "U+1F1E7 U+1F1F3",
            "name": "Brunei Darussalam",
            "title": "flag for Brunei Darussalam",
        },
        {
            "code": "BO",
            "emoji": "🇧🇴",
            "unicode": "U+1F1E7 U+1F1F4",
            "name": "Bolivia",
            "title": "flag for Bolivia",
        },
        {
            "code": "BQ",
            "emoji": "🇧🇶",
            "unicode": "U+1F1E7 U+1F1F6",
            "name": "Bonaire, Sint Eustatius and Saba",
            "title": "flag for Bonaire, Sint Eustatius and Saba",
        },
        {
            "code": "BR",
            "emoji": "🇧🇷",
            "unicode": "U+1F1E7 U+1F1F7",
            "name": "Brazil",
            "title": "flag for Brazil",
        },
        {
            "code": "BS",
            "emoji": "🇧🇸",
            "unicode": "U+1F1E7 U+1F1F8",
            "name": "Bahamas",
            "title": "flag for Bahamas",
        },
        {
            "code": "BT",
            "emoji": "🇧🇹",
            "unicode": "U+1F1E7 U+1F1F9",
            "name": "Bhutan",
            "title": "flag for Bhutan",
        },
        {
            "code": "BV",
            "emoji": "🇧🇻",
            "unicode": "U+1F1E7 U+1F1FB",
            "name": "Bouvet Island",
            "title": "flag for Bouvet Island",
        },
        {
            "code": "BW",
            "emoji": "🇧🇼",
            "unicode": "U+1F1E7 U+1F1FC",
            "name": "Botswana",
            "title": "flag for Botswana",
        },
        {
            "code": "BY",
            "emoji": "🇧🇾",
            "unicode": "U+1F1E7 U+1F1FE",
            "name": "Belarus",
            "title": "flag for Belarus",
        },
        {
            "code": "BZ",
            "emoji": "🇧🇿",
            "unicode": "U+1F1E7 U+1F1FF",
            "name": "Belize",
            "title": "flag for Belize",
        },
        {
            "code": "CA",
            "emoji": "🇨🇦",
            "unicode": "U+1F1E8 U+1F1E6",
            "name": "Canada",
            "title": "flag for Canada",
        },
        {
            "code": "CC",
            "emoji": "🇨🇨",
            "unicode": "U+1F1E8 U+1F1E8",
            "name": "Cocos (Keeling) Islands",
            "title": "flag for Cocos (Keeling) Islands",
        },
        {
            "code": "CD",
            "emoji": "🇨🇩",
            "unicode": "U+1F1E8 U+1F1E9",
            "name": "Congo",
            "title": "flag for Congo",
        },
        {
            "code": "CF",
            "emoji": "🇨🇫",
            "unicode": "U+1F1E8 U+1F1EB",
            "name": "Central African Republic",
            "title": "flag for Central African Republic",
        },
        {
            "code": "CG",
            "emoji": "🇨🇬",
            "unicode": "U+1F1E8 U+1F1EC",
            "name": "Congo",
            "title": "flag for Congo",
        },
        {
            "code": "CH",
            "emoji": "🇨🇭",
            "unicode": "U+1F1E8 U+1F1ED",
            "name": "Switzerland",
            "title": "flag for Switzerland",
        },
        {
            "code": "CI",
            "emoji": "🇨🇮",
            "unicode": "U+1F1E8 U+1F1EE",
            "name": "Côte D'Ivoire",
            "title": "flag for Côte D'Ivoire",
        },
        {
            "code": "CK",
            "emoji": "🇨🇰",
            "unicode": "U+1F1E8 U+1F1F0",
            "name": "Cook Islands",
            "title": "flag for Cook Islands",
        },
        {
            "code": "CL",
            "emoji": "🇨🇱",
            "unicode": "U+1F1E8 U+1F1F1",
            "name": "Chile",
            "title": "flag for Chile",
        },
        {
            "code": "CM",
            "emoji": "🇨🇲",
            "unicode": "U+1F1E8 U+1F1F2",
            "name": "Cameroon",
            "title": "flag for Cameroon",
        },
        {
            "code": "CN",
            "emoji": "🇨🇳",
            "unicode": "U+1F1E8 U+1F1F3",
            "name": "China",
            "title": "flag for China",
        },
        {
            "code": "CO",
            "emoji": "🇨🇴",
            "unicode": "U+1F1E8 U+1F1F4",
            "name": "Colombia",
            "title": "flag for Colombia",
        },
        {
            "code": "CR",
            "emoji": "🇨🇷",
            "unicode": "U+1F1E8 U+1F1F7",
            "name": "Costa Rica",
            "title": "flag for Costa Rica",
        },
        {
            "code": "CU",
            "emoji": "🇨🇺",
            "unicode": "U+1F1E8 U+1F1FA",
            "name": "Cuba",
            "title": "flag for Cuba",
        },
        {
            "code": "CV",
            "emoji": "🇨🇻",
            "unicode": "U+1F1E8 U+1F1FB",
            "name": "Cape Verde",
            "title": "flag for Cape Verde",
        },
        {
            "code": "CW",
            "emoji": "🇨🇼",
            "unicode": "U+1F1E8 U+1F1FC",
            "name": "Curaçao",
            "title": "flag for Curaçao",
        },
        {
            "code": "CX",
            "emoji": "🇨🇽",
            "unicode": "U+1F1E8 U+1F1FD",
            "name": "Christmas Island",
            "title": "flag for Christmas Island",
        },
        {
            "code": "CY",
            "emoji": "🇨🇾",
            "unicode": "U+1F1E8 U+1F1FE",
            "name": "Cyprus",
            "title": "flag for Cyprus",
        },
        {
            "code": "CZ",
            "emoji": "🇨🇿",
            "unicode": "U+1F1E8 U+1F1FF",
            "name": "Czech Republic",
            "title": "flag for Czech Republic",
        },
        {
            "code": "DE",
            "emoji": "🇩🇪",
            "unicode": "U+1F1E9 U+1F1EA",
            "name": "Germany",
            "title": "flag for Germany",
        },
        {
            "code": "DJ",
            "emoji": "🇩🇯",
            "unicode": "U+1F1E9 U+1F1EF",
            "name": "Djibouti",
            "title": "flag for Djibouti",
        },
        {
            "code": "DK",
            "emoji": "🇩🇰",
            "unicode": "U+1F1E9 U+1F1F0",
            "name": "Denmark",
            "title": "flag for Denmark",
        },
        {
            "code": "DM",
            "emoji": "🇩🇲",
            "unicode": "U+1F1E9 U+1F1F2",
            "name": "Dominica",
            "title": "flag for Dominica",
        },
        {
            "code": "DO",
            "emoji": "🇩🇴",
            "unicode": "U+1F1E9 U+1F1F4",
            "name": "Dominican Republic",
            "title": "flag for Dominican Republic",
        },
        {
            "code": "DZ",
            "emoji": "🇩🇿",
            "unicode": "U+1F1E9 U+1F1FF",
            "name": "Algeria",
            "title": "flag for Algeria",
        },
        {
            "code": "EC",
            "emoji": "🇪🇨",
            "unicode": "U+1F1EA U+1F1E8",
            "name": "Ecuador",
            "title": "flag for Ecuador",
        },
        {
            "code": "EE",
            "emoji": "🇪🇪",
            "unicode": "U+1F1EA U+1F1EA",
            "name": "Estonia",
            "title": "flag for Estonia",
        },
        {
            "code": "EG",
            "emoji": "🇪🇬",
            "unicode": "U+1F1EA U+1F1EC",
            "name": "Egypt",
            "title": "flag for Egypt",
        },
        {
            "code": "EH",
            "emoji": "🇪🇭",
            "unicode": "U+1F1EA U+1F1ED",
            "name": "Western Sahara",
            "title": "flag for Western Sahara",
        },
        {
            "code": "ER",
            "emoji": "🇪🇷",
            "unicode": "U+1F1EA U+1F1F7",
            "name": "Eritrea",
            "title": "flag for Eritrea",
        },
        {
            "code": "ES",
            "emoji": "🇪🇸",
            "unicode": "U+1F1EA U+1F1F8",
            "name": "Spain",
            "title": "flag for Spain",
        },
        {
            "code": "ET",
            "emoji": "🇪🇹",
            "unicode": "U+1F1EA U+1F1F9",
            "name": "Ethiopia",
            "title": "flag for Ethiopia",
        },
        {
            "code": "EU",
            "emoji": "🇪🇺",
            "unicode": "U+1F1EA U+1F1FA",
            "name": "European Union",
            "title": "flag for European Union",
        },
        {
            "code": "FI",
            "emoji": "🇫🇮",
            "unicode": "U+1F1EB U+1F1EE",
            "name": "Finland",
            "title": "flag for Finland",
        },
        {
            "code": "FJ",
            "emoji": "🇫🇯",
            "unicode": "U+1F1EB U+1F1EF",
            "name": "Fiji",
            "title": "flag for Fiji",
        },
        {
            "code": "FK",
            "emoji": "🇫🇰",
            "unicode": "U+1F1EB U+1F1F0",
            "name": "Falkland Islands (Malvinas)",
            "title": "flag for Falkland Islands (Malvinas)",
        },
        {
            "code": "FM",
            "emoji": "🇫🇲",
            "unicode": "U+1F1EB U+1F1F2",
            "name": "Micronesia",
            "title": "flag for Micronesia",
        },
        {
            "code": "FO",
            "emoji": "🇫🇴",
            "unicode": "U+1F1EB U+1F1F4",
            "name": "Faroe Islands",
            "title": "flag for Faroe Islands",
        },
        {
            "code": "FR",
            "emoji": "🇫🇷",
            "unicode": "U+1F1EB U+1F1F7",
            "name": "France",
            "title": "flag for France",
        },
        {
            "code": "GA",
            "emoji": "🇬🇦",
            "unicode": "U+1F1EC U+1F1E6",
            "name": "Gabon",
            "title": "flag for Gabon",
        },
        {
            "code": "GB",
            "emoji": "🇬🇧",
            "unicode": "U+1F1EC U+1F1E7",
            "name": "United Kingdom",
            "title": "flag for United Kingdom",
        },
        {
            "code": "GD",
            "emoji": "🇬🇩",
            "unicode": "U+1F1EC U+1F1E9",
            "name": "Grenada",
            "title": "flag for Grenada",
        },
        {
            "code": "GE",
            "emoji": "🇬🇪",
            "unicode": "U+1F1EC U+1F1EA",
            "name": "Georgia",
            "title": "flag for Georgia",
        },
        {
            "code": "GF",
            "emoji": "🇬🇫",
            "unicode": "U+1F1EC U+1F1EB",
            "name": "French Guiana",
            "title": "flag for French Guiana",
        },
        {
            "code": "GG",
            "emoji": "🇬🇬",
            "unicode": "U+1F1EC U+1F1EC",
            "name": "Guernsey",
            "title": "flag for Guernsey",
        },
        {
            "code": "GH",
            "emoji": "🇬🇭",
            "unicode": "U+1F1EC U+1F1ED",
            "name": "Ghana",
            "title": "flag for Ghana",
        },
        {
            "code": "GI",
            "emoji": "🇬🇮",
            "unicode": "U+1F1EC U+1F1EE",
            "name": "Gibraltar",
            "title": "flag for Gibraltar",
        },
        {
            "code": "GL",
            "emoji": "🇬🇱",
            "unicode": "U+1F1EC U+1F1F1",
            "name": "Greenland",
            "title": "flag for Greenland",
        },
        {
            "code": "GM",
            "emoji": "🇬🇲",
            "unicode": "U+1F1EC U+1F1F2",
            "name": "Gambia",
            "title": "flag for Gambia",
        },
        {
            "code": "GN",
            "emoji": "🇬🇳",
            "unicode": "U+1F1EC U+1F1F3",
            "name": "Guinea",
            "title": "flag for Guinea",
        },
        {
            "code": "GP",
            "emoji": "🇬🇵",
            "unicode": "U+1F1EC U+1F1F5",
            "name": "Guadeloupe",
            "title": "flag for Guadeloupe",
        },
        {
            "code": "GQ",
            "emoji": "🇬🇶",
            "unicode": "U+1F1EC U+1F1F6",
            "name": "Equatorial Guinea",
            "title": "flag for Equatorial Guinea",
        },
        {
            "code": "GR",
            "emoji": "🇬🇷",
            "unicode": "U+1F1EC U+1F1F7",
            "name": "Greece",
            "title": "flag for Greece",
        },
        {
            "code": "GS",
            "emoji": "🇬🇸",
            "unicode": "U+1F1EC U+1F1F8",
            "name": "South Georgia",
            "title": "flag for South Georgia",
        },
        {
            "code": "GT",
            "emoji": "🇬🇹",
            "unicode": "U+1F1EC U+1F1F9",
            "name": "Guatemala",
            "title": "flag for Guatemala",
        },
        {
            "code": "GU",
            "emoji": "🇬🇺",
            "unicode": "U+1F1EC U+1F1FA",
            "name": "Guam",
            "title": "flag for Guam",
        },
        {
            "code": "GW",
            "emoji": "🇬🇼",
            "unicode": "U+1F1EC U+1F1FC",
            "name": "Guinea-Bissau",
            "title": "flag for Guinea-Bissau",
        },
        {
            "code": "GY",
            "emoji": "🇬🇾",
            "unicode": "U+1F1EC U+1F1FE",
            "name": "Guyana",
            "title": "flag for Guyana",
        },
        {
            "code": "HK",
            "emoji": "🇭🇰",
            "unicode": "U+1F1ED U+1F1F0",
            "name": "Hong Kong",
            "title": "flag for Hong Kong",
        },
        {
            "code": "HM",
            "emoji": "🇭🇲",
            "unicode": "U+1F1ED U+1F1F2",
            "name": "Heard Island and Mcdonald Islands",
            "title": "flag for Heard Island and Mcdonald Islands",
        },
        {
            "code": "HN",
            "emoji": "🇭🇳",
            "unicode": "U+1F1ED U+1F1F3",
            "name": "Honduras",
            "title": "flag for Honduras",
        },
        {
            "code": "HR",
            "emoji": "🇭🇷",
            "unicode": "U+1F1ED U+1F1F7",
            "name": "Croatia",
            "title": "flag for Croatia",
        },
        {
            "code": "HT",
            "emoji": "🇭🇹",
            "unicode": "U+1F1ED U+1F1F9",
            "name": "Haiti",
            "title": "flag for Haiti",
        },
        {
            "code": "HU",
            "emoji": "🇭🇺",
            "unicode": "U+1F1ED U+1F1FA",
            "name": "Hungary",
            "title": "flag for Hungary",
        },
        {
            "code": "ID",
            "emoji": "🇮🇩",
            "unicode": "U+1F1EE U+1F1E9",
            "name": "Indonesia",
            "title": "flag for Indonesia",
        },
        {
            "code": "IE",
            "emoji": "🇮🇪",
            "unicode": "U+1F1EE U+1F1EA",
            "name": "Ireland",
            "title": "flag for Ireland",
        },
        {
            "code": "IL",
            "emoji": "🇮🇱",
            "unicode": "U+1F1EE U+1F1F1",
            "name": "Israel",
            "title": "flag for Israel",
        },
        {
            "code": "IM",
            "emoji": "🇮🇲",
            "unicode": "U+1F1EE U+1F1F2",
            "name": "Isle of Man",
            "title": "flag for Isle of Man",
        },
        {
            "code": "IN",
            "emoji": "🇮🇳",
            "unicode": "U+1F1EE U+1F1F3",
            "name": "India",
            "title": "flag for India",
        },
        {
            "code": "IO",
            "emoji": "🇮🇴",
            "unicode": "U+1F1EE U+1F1F4",
            "name": "British Indian Ocean Territory",
            "title": "flag for British Indian Ocean Territory",
        },
        {
            "code": "IQ",
            "emoji": "🇮🇶",
            "unicode": "U+1F1EE U+1F1F6",
            "name": "Iraq",
            "title": "flag for Iraq",
        },
        {
            "code": "IR",
            "emoji": "🇮🇷",
            "unicode": "U+1F1EE U+1F1F7",
            "name": "Iran",
            "title": "flag for Iran",
        },
        {
            "code": "IS",
            "emoji": "🇮🇸",
            "unicode": "U+1F1EE U+1F1F8",
            "name": "Iceland",
            "title": "flag for Iceland",
        },
        {
            "code": "IT",
            "emoji": "🇮🇹",
            "unicode": "U+1F1EE U+1F1F9",
            "name": "Italy",
            "title": "flag for Italy",
        },
        {
            "code": "JE",
            "emoji": "🇯🇪",
            "unicode": "U+1F1EF U+1F1EA",
            "name": "Jersey",
            "title": "flag for Jersey",
        },
        {
            "code": "JM",
            "emoji": "🇯🇲",
            "unicode": "U+1F1EF U+1F1F2",
            "name": "Jamaica",
            "title": "flag for Jamaica",
        },
        {
            "code": "JO",
            "emoji": "🇯🇴",
            "unicode": "U+1F1EF U+1F1F4",
            "name": "Jordan",
            "title": "flag for Jordan",
        },
        {
            "code": "JP",
            "emoji": "🇯🇵",
            "unicode": "U+1F1EF U+1F1F5",
            "name": "Japan",
            "title": "flag for Japan",
        },
        {
            "code": "KE",
            "emoji": "🇰🇪",
            "unicode": "U+1F1F0 U+1F1EA",
            "name": "Kenya",
            "title": "flag for Kenya",
        },
        {
            "code": "KG",
            "emoji": "🇰🇬",
            "unicode": "U+1F1F0 U+1F1EC",
            "name": "Kyrgyzstan",
            "title": "flag for Kyrgyzstan",
        },
        {
            "code": "KH",
            "emoji": "🇰🇭",
            "unicode": "U+1F1F0 U+1F1ED",
            "name": "Cambodia",
            "title": "flag for Cambodia",
        },
        {
            "code": "KI",
            "emoji": "🇰🇮",
            "unicode": "U+1F1F0 U+1F1EE",
            "name": "Kiribati",
            "title": "flag for Kiribati",
        },
        {
            "code": "KM",
            "emoji": "🇰🇲",
            "unicode": "U+1F1F0 U+1F1F2",
            "name": "Comoros",
            "title": "flag for Comoros",
        },
        {
            "code": "KN",
            "emoji": "🇰🇳",
            "unicode": "U+1F1F0 U+1F1F3",
            "name": "Saint Kitts and Nevis",
            "title": "flag for Saint Kitts and Nevis",
        },
        {
            "code": "KP",
            "emoji": "🇰🇵",
            "unicode": "U+1F1F0 U+1F1F5",
            "name": "North Korea",
            "title": "flag for North Korea",
        },
        {
            "code": "KR",
            "emoji": "🇰🇷",
            "unicode": "U+1F1F0 U+1F1F7",
            "name": "South Korea",
            "title": "flag for South Korea",
        },
        {
            "code": "KW",
            "emoji": "🇰🇼",
            "unicode": "U+1F1F0 U+1F1FC",
            "name": "Kuwait",
            "title": "flag for Kuwait",
        },
        {
            "code": "KY",
            "emoji": "🇰🇾",
            "unicode": "U+1F1F0 U+1F1FE",
            "name": "Cayman Islands",
            "title": "flag for Cayman Islands",
        },
        {
            "code": "KZ",
            "emoji": "🇰🇿",
            "unicode": "U+1F1F0 U+1F1FF",
            "name": "Kazakhstan",
            "title": "flag for Kazakhstan",
        },
        {
            "code": "LA",
            "emoji": "🇱🇦",
            "unicode": "U+1F1F1 U+1F1E6",
            "name": "Lao People's Democratic Republic",
            "title": "flag for Lao People's Democratic Republic",
        },
        {
            "code": "LB",
            "emoji": "🇱🇧",
            "unicode": "U+1F1F1 U+1F1E7",
            "name": "Lebanon",
            "title": "flag for Lebanon",
        },
        {
            "code": "LC",
            "emoji": "🇱🇨",
            "unicode": "U+1F1F1 U+1F1E8",
            "name": "Saint Lucia",
            "title": "flag for Saint Lucia",
        },
        {
            "code": "LI",
            "emoji": "🇱🇮",
            "unicode": "U+1F1F1 U+1F1EE",
            "name": "Liechtenstein",
            "title": "flag for Liechtenstein",
        },
        {
            "code": "LK",
            "emoji": "🇱🇰",
            "unicode": "U+1F1F1 U+1F1F0",
            "name": "Sri Lanka",
            "title": "flag for Sri Lanka",
        },
        {
            "code": "LR",
            "emoji": "🇱🇷",
            "unicode": "U+1F1F1 U+1F1F7",
            "name": "Liberia",
            "title": "flag for Liberia",
        },
        {
            "code": "LS",
            "emoji": "🇱🇸",
            "unicode": "U+1F1F1 U+1F1F8",
            "name": "Lesotho",
            "title": "flag for Lesotho",
        },
        {
            "code": "LT",
            "emoji": "🇱🇹",
            "unicode": "U+1F1F1 U+1F1F9",
            "name": "Lithuania",
            "title": "flag for Lithuania",
        },
        {
            "code": "LU",
            "emoji": "🇱🇺",
            "unicode": "U+1F1F1 U+1F1FA",
            "name": "Luxembourg",
            "title": "flag for Luxembourg",
        },
        {
            "code": "LV",
            "emoji": "🇱🇻",
            "unicode": "U+1F1F1 U+1F1FB",
            "name": "Latvia",
            "title": "flag for Latvia",
        },
        {
            "code": "LY",
            "emoji": "🇱🇾",
            "unicode": "U+1F1F1 U+1F1FE",
            "name": "Libya",
            "title": "flag for Libya",
        },
        {
            "code": "MA",
            "emoji": "🇲🇦",
            "unicode": "U+1F1F2 U+1F1E6",
            "name": "Morocco",
            "title": "flag for Morocco",
        },
        {
            "code": "MC",
            "emoji": "🇲🇨",
            "unicode": "U+1F1F2 U+1F1E8",
            "name": "Monaco",
            "title": "flag for Monaco",
        },
        {
            "code": "MD",
            "emoji": "🇲🇩",
            "unicode": "U+1F1F2 U+1F1E9",
            "name": "Moldova",
            "title": "flag for Moldova",
        },
        {
            "code": "ME",
            "emoji": "🇲🇪",
            "unicode": "U+1F1F2 U+1F1EA",
            "name": "Montenegro",
            "title": "flag for Montenegro",
        },
        {
            "code": "MF",
            "emoji": "🇲🇫",
            "unicode": "U+1F1F2 U+1F1EB",
            "name": "Saint Martin (French Part)",
            "title": "flag for Saint Martin (French Part)",
        },
        {
            "code": "MG",
            "emoji": "🇲🇬",
            "unicode": "U+1F1F2 U+1F1EC",
            "name": "Madagascar",
            "title": "flag for Madagascar",
        },
        {
            "code": "MH",
            "emoji": "🇲🇭",
            "unicode": "U+1F1F2 U+1F1ED",
            "name": "Marshall Islands",
            "title": "flag for Marshall Islands",
        },
        {
            "code": "MK",
            "emoji": "🇲🇰",
            "unicode": "U+1F1F2 U+1F1F0",
            "name": "Macedonia",
            "title": "flag for Macedonia",
        },
        {
            "code": "ML",
            "emoji": "🇲🇱",
            "unicode": "U+1F1F2 U+1F1F1",
            "name": "Mali",
            "title": "flag for Mali",
        },
        {
            "code": "MM",
            "emoji": "🇲🇲",
            "unicode": "U+1F1F2 U+1F1F2",
            "name": "Myanmar",
            "title": "flag for Myanmar",
        },
        {
            "code": "MN",
            "emoji": "🇲🇳",
            "unicode": "U+1F1F2 U+1F1F3",
            "name": "Mongolia",
            "title": "flag for Mongolia",
        },
        {
            "code": "MO",
            "emoji": "🇲🇴",
            "unicode": "U+1F1F2 U+1F1F4",
            "name": "Macao",
            "title": "flag for Macao",
        },
        {
            "code": "MP",
            "emoji": "🇲🇵",
            "unicode": "U+1F1F2 U+1F1F5",
            "name": "Northern Mariana Islands",
            "title": "flag for Northern Mariana Islands",
        },
        {
            "code": "MQ",
            "emoji": "🇲🇶",
            "unicode": "U+1F1F2 U+1F1F6",
            "name": "Martinique",
            "title": "flag for Martinique",
        },
        {
            "code": "MR",
            "emoji": "🇲🇷",
            "unicode": "U+1F1F2 U+1F1F7",
            "name": "Mauritania",
            "title": "flag for Mauritania",
        },
        {
            "code": "MS",
            "emoji": "🇲🇸",
            "unicode": "U+1F1F2 U+1F1F8",
            "name": "Montserrat",
            "title": "flag for Montserrat",
        },
        {
            "code": "MT",
            "emoji": "🇲🇹",
            "unicode": "U+1F1F2 U+1F1F9",
            "name": "Malta",
            "title": "flag for Malta",
        },
        {
            "code": "MU",
            "emoji": "🇲🇺",
            "unicode": "U+1F1F2 U+1F1FA",
            "name": "Mauritius",
            "title": "flag for Mauritius",
        },
        {
            "code": "MV",
            "emoji": "🇲🇻",
            "unicode": "U+1F1F2 U+1F1FB",
            "name": "Maldives",
            "title": "flag for Maldives",
        },
        {
            "code": "MW",
            "emoji": "🇲🇼",
            "unicode": "U+1F1F2 U+1F1FC",
            "name": "Malawi",
            "title": "flag for Malawi",
        },
        {
            "code": "MX",
            "emoji": "🇲🇽",
            "unicode": "U+1F1F2 U+1F1FD",
            "name": "Mexico",
            "title": "flag for Mexico",
        },
        {
            "code": "MY",
            "emoji": "🇲🇾",
            "unicode": "U+1F1F2 U+1F1FE",
            "name": "Malaysia",
            "title": "flag for Malaysia",
        },
        {
            "code": "MZ",
            "emoji": "🇲🇿",
            "unicode": "U+1F1F2 U+1F1FF",
            "name": "Mozambique",
            "title": "flag for Mozambique",
        },
        {
            "code": "NA",
            "emoji": "🇳🇦",
            "unicode": "U+1F1F3 U+1F1E6",
            "name": "Namibia",
            "title": "flag for Namibia",
        },
        {
            "code": "NC",
            "emoji": "🇳🇨",
            "unicode": "U+1F1F3 U+1F1E8",
            "name": "New Caledonia",
            "title": "flag for New Caledonia",
        },
        {
            "code": "NE",
            "emoji": "🇳🇪",
            "unicode": "U+1F1F3 U+1F1EA",
            "name": "Niger",
            "title": "flag for Niger",
        },
        {
            "code": "NF",
            "emoji": "🇳🇫",
            "unicode": "U+1F1F3 U+1F1EB",
            "name": "Norfolk Island",
            "title": "flag for Norfolk Island",
        },
        {
            "code": "NG",
            "emoji": "🇳🇬",
            "unicode": "U+1F1F3 U+1F1EC",
            "name": "Nigeria",
            "title": "flag for Nigeria",
        },
        {
            "code": "NI",
            "emoji": "🇳🇮",
            "unicode": "U+1F1F3 U+1F1EE",
            "name": "Nicaragua",
            "title": "flag for Nicaragua",
        },
        {
            "code": "NL",
            "emoji": "🇳🇱",
            "unicode": "U+1F1F3 U+1F1F1",
            "name": "Netherlands",
            "title": "flag for Netherlands",
        },
        {
            "code": "NO",
            "emoji": "🇳🇴",
            "unicode": "U+1F1F3 U+1F1F4",
            "name": "Norway",
            "title": "flag for Norway",
        },
        {
            "code": "NP",
            "emoji": "🇳🇵",
            "unicode": "U+1F1F3 U+1F1F5",
            "name": "Nepal",
            "title": "flag for Nepal",
        },
        {
            "code": "NR",
            "emoji": "🇳🇷",
            "unicode": "U+1F1F3 U+1F1F7",
            "name": "Nauru",
            "title": "flag for Nauru",
        },
        {
            "code": "NU",
            "emoji": "🇳🇺",
            "unicode": "U+1F1F3 U+1F1FA",
            "name": "Niue",
            "title": "flag for Niue",
        },
        {
            "code": "NZ",
            "emoji": "🇳🇿",
            "unicode": "U+1F1F3 U+1F1FF",
            "name": "New Zealand",
            "title": "flag for New Zealand",
        },
        {
            "code": "OM",
            "emoji": "🇴🇲",
            "unicode": "U+1F1F4 U+1F1F2",
            "name": "Oman",
            "title": "flag for Oman",
        },
        {
            "code": "PA",
            "emoji": "🇵🇦",
            "unicode": "U+1F1F5 U+1F1E6",
            "name": "Panama",
            "title": "flag for Panama",
        },
        {
            "code": "PE",
            "emoji": "🇵🇪",
            "unicode": "U+1F1F5 U+1F1EA",
            "name": "Peru",
            "title": "flag for Peru",
        },
        {
            "code": "PF",
            "emoji": "🇵🇫",
            "unicode": "U+1F1F5 U+1F1EB",
            "name": "French Polynesia",
            "title": "flag for French Polynesia",
        },
        {
            "code": "PG",
            "emoji": "🇵🇬",
            "unicode": "U+1F1F5 U+1F1EC",
            "name": "Papua New Guinea",
            "title": "flag for Papua New Guinea",
        },
        {
            "code": "PH",
            "emoji": "🇵🇭",
            "unicode": "U+1F1F5 U+1F1ED",
            "name": "Philippines",
            "title": "flag for Philippines",
        },
        {
            "code": "PK",
            "emoji": "🇵🇰",
            "unicode": "U+1F1F5 U+1F1F0",
            "name": "Pakistan",
            "title": "flag for Pakistan",
        },
        {
            "code": "PL",
            "emoji": "🇵🇱",
            "unicode": "U+1F1F5 U+1F1F1",
            "name": "Poland",
            "title": "flag for Poland",
        },
        {
            "code": "PM",
            "emoji": "🇵🇲",
            "unicode": "U+1F1F5 U+1F1F2",
            "name": "Saint Pierre and Miquelon",
            "title": "flag for Saint Pierre and Miquelon",
        },
        {
            "code": "PN",
            "emoji": "🇵🇳",
            "unicode": "U+1F1F5 U+1F1F3",
            "name": "Pitcairn",
            "title": "flag for Pitcairn",
        },
        {
            "code": "PR",
            "emoji": "🇵🇷",
            "unicode": "U+1F1F5 U+1F1F7",
            "name": "Puerto Rico",
            "title": "flag for Puerto Rico",
        },
        {
            "code": "PS",
            "emoji": "🇵🇸",
            "unicode": "U+1F1F5 U+1F1F8",
            "name": "Palestinian Territory",
            "title": "flag for Palestinian Territory",
        },
        {
            "code": "PT",
            "emoji": "🇵🇹",
            "unicode": "U+1F1F5 U+1F1F9",
            "name": "Portugal",
            "title": "flag for Portugal",
        },
        {
            "code": "PW",
            "emoji": "🇵🇼",
            "unicode": "U+1F1F5 U+1F1FC",
            "name": "Palau",
            "title": "flag for Palau",
        },
        {
            "code": "PY",
            "emoji": "🇵🇾",
            "unicode": "U+1F1F5 U+1F1FE",
            "name": "Paraguay",
            "title": "flag for Paraguay",
        },
        {
            "code": "QA",
            "emoji": "🇶🇦",
            "unicode": "U+1F1F6 U+1F1E6",
            "name": "Qatar",
            "title": "flag for Qatar",
        },
        {
            "code": "RE",
            "emoji": "🇷🇪",
            "unicode": "U+1F1F7 U+1F1EA",
            "name": "Réunion",
            "title": "flag for Réunion",
        },
        {
            "code": "RO",
            "emoji": "🇷🇴",
            "unicode": "U+1F1F7 U+1F1F4",
            "name": "Romania",
            "title": "flag for Romania",
        },
        {
            "code": "RS",
            "emoji": "🇷🇸",
            "unicode": "U+1F1F7 U+1F1F8",
            "name": "Serbia",
            "title": "flag for Serbia",
        },
        {
            "code": "RU",
            "emoji": "🇷🇺",
            "unicode": "U+1F1F7 U+1F1FA",
            "name": "Russia",
            "title": "flag for Russia",
        },
        {
            "code": "RW",
            "emoji": "🇷🇼",
            "unicode": "U+1F1F7 U+1F1FC",
            "name": "Rwanda",
            "title": "flag for Rwanda",
        },
        {
            "code": "SA",
            "emoji": "🇸🇦",
            "unicode": "U+1F1F8 U+1F1E6",
            "name": "Saudi Arabia",
            "title": "flag for Saudi Arabia",
        },
        {
            "code": "SB",
            "emoji": "🇸🇧",
            "unicode": "U+1F1F8 U+1F1E7",
            "name": "Solomon Islands",
            "title": "flag for Solomon Islands",
        },
        {
            "code": "SC",
            "emoji": "🇸🇨",
            "unicode": "U+1F1F8 U+1F1E8",
            "name": "Seychelles",
            "title": "flag for Seychelles",
        },
        {
            "code": "SD",
            "emoji": "🇸🇩",
            "unicode": "U+1F1F8 U+1F1E9",
            "name": "Sudan",
            "title": "flag for Sudan",
        },
        {
            "code": "SE",
            "emoji": "🇸🇪",
            "unicode": "U+1F1F8 U+1F1EA",
            "name": "Sweden",
            "title": "flag for Sweden",
        },
        {
            "code": "SG",
            "emoji": "🇸🇬",
            "unicode": "U+1F1F8 U+1F1EC",
            "name": "Singapore",
            "title": "flag for Singapore",
        },
        {
            "code": "SH",
            "emoji": "🇸🇭",
            "unicode": "U+1F1F8 U+1F1ED",
            "name": "Saint Helena, Ascension and Tristan Da Cunha",
            "title": "flag for Saint Helena, Ascension and Tristan Da Cunha",
        },
        {
            "code": "SI",
            "emoji": "🇸🇮",
            "unicode": "U+1F1F8 U+1F1EE",
            "name": "Slovenia",
            "title": "flag for Slovenia",
        },
        {
            "code": "SJ",
            "emoji": "🇸🇯",
            "unicode": "U+1F1F8 U+1F1EF",
            "name": "Svalbard and Jan Mayen",
            "title": "flag for Svalbard and Jan Mayen",
        },
        {
            "code": "SK",
            "emoji": "🇸🇰",
            "unicode": "U+1F1F8 U+1F1F0",
            "name": "Slovakia",
            "title": "flag for Slovakia",
        },
        {
            "code": "SL",
            "emoji": "🇸🇱",
            "unicode": "U+1F1F8 U+1F1F1",
            "name": "Sierra Leone",
            "title": "flag for Sierra Leone",
        },
        {
            "code": "SM",
            "emoji": "🇸🇲",
            "unicode": "U+1F1F8 U+1F1F2",
            "name": "San Marino",
            "title": "flag for San Marino",
        },
        {
            "code": "SN",
            "emoji": "🇸🇳",
            "unicode": "U+1F1F8 U+1F1F3",
            "name": "Senegal",
            "title": "flag for Senegal",
        },
        {
            "code": "SO",
            "emoji": "🇸🇴",
            "unicode": "U+1F1F8 U+1F1F4",
            "name": "Somalia",
            "title": "flag for Somalia",
        },
        {
            "code": "SR",
            "emoji": "🇸🇷",
            "unicode": "U+1F1F8 U+1F1F7",
            "name": "Suriname",
            "title": "flag for Suriname",
        },
        {
            "code": "SS",
            "emoji": "🇸🇸",
            "unicode": "U+1F1F8 U+1F1F8",
            "name": "South Sudan",
            "title": "flag for South Sudan",
        },
        {
            "code": "ST",
            "emoji": "🇸🇹",
            "unicode": "U+1F1F8 U+1F1F9",
            "name": "Sao Tome and Principe",
            "title": "flag for Sao Tome and Principe",
        },
        {
            "code": "SV",
            "emoji": "🇸🇻",
            "unicode": "U+1F1F8 U+1F1FB",
            "name": "El Salvador",
            "title": "flag for El Salvador",
        },
        {
            "code": "SX",
            "emoji": "🇸🇽",
            "unicode": "U+1F1F8 U+1F1FD",
            "name": "Sint Maarten (Dutch Part)",
            "title": "flag for Sint Maarten (Dutch Part)",
        },
        {
            "code": "SY",
            "emoji": "🇸🇾",
            "unicode": "U+1F1F8 U+1F1FE",
            "name": "Syrian Arab Republic",
            "title": "flag for Syrian Arab Republic",
        },
        {
            "code": "SZ",
            "emoji": "🇸🇿",
            "unicode": "U+1F1F8 U+1F1FF",
            "name": "Swaziland",
            "title": "flag for Swaziland",
        },
        {
            "code": "TC",
            "emoji": "🇹🇨",
            "unicode": "U+1F1F9 U+1F1E8",
            "name": "Turks and Caicos Islands",
            "title": "flag for Turks and Caicos Islands",
        },
        {
            "code": "TD",
            "emoji": "🇹🇩",
            "unicode": "U+1F1F9 U+1F1E9",
            "name": "Chad",
            "title": "flag for Chad",
        },
        {
            "code": "TF",
            "emoji": "🇹🇫",
            "unicode": "U+1F1F9 U+1F1EB",
            "name": "French Southern Territories",
            "title": "flag for French Southern Territories",
        },
        {
            "code": "TG",
            "emoji": "🇹🇬",
            "unicode": "U+1F1F9 U+1F1EC",
            "name": "Togo",
            "title": "flag for Togo",
        },
        {
            "code": "TH",
            "emoji": "🇹🇭",
            "unicode": "U+1F1F9 U+1F1ED",
            "name": "Thailand",
            "title": "flag for Thailand",
        },
        {
            "code": "TJ",
            "emoji": "🇹🇯",
            "unicode": "U+1F1F9 U+1F1EF",
            "name": "Tajikistan",
            "title": "flag for Tajikistan",
        },
        {
            "code": "TK",
            "emoji": "🇹🇰",
            "unicode": "U+1F1F9 U+1F1F0",
            "name": "Tokelau",
            "title": "flag for Tokelau",
        },
        {
            "code": "TL",
            "emoji": "🇹🇱",
            "unicode": "U+1F1F9 U+1F1F1",
            "name": "Timor-Leste",
            "title": "flag for Timor-Leste",
        },
        {
            "code": "TM",
            "emoji": "🇹🇲",
            "unicode": "U+1F1F9 U+1F1F2",
            "name": "Turkmenistan",
            "title": "flag for Turkmenistan",
        },
        {
            "code": "TN",
            "emoji": "🇹🇳",
            "unicode": "U+1F1F9 U+1F1F3",
            "name": "Tunisia",
            "title": "flag for Tunisia",
        },
        {
            "code": "TO",
            "emoji": "🇹🇴",
            "unicode": "U+1F1F9 U+1F1F4",
            "name": "Tonga",
            "title": "flag for Tonga",
        },
        {
            "code": "TR",
            "emoji": "🇹🇷",
            "unicode": "U+1F1F9 U+1F1F7",
            "name": "Turkey",
            "title": "flag for Turkey",
        },
        {
            "code": "TT",
            "emoji": "🇹🇹",
            "unicode": "U+1F1F9 U+1F1F9",
            "name": "Trinidad and Tobago",
            "title": "flag for Trinidad and Tobago",
        },
        {
            "code": "TV",
            "emoji": "🇹🇻",
            "unicode": "U+1F1F9 U+1F1FB",
            "name": "Tuvalu",
            "title": "flag for Tuvalu",
        },
        {
            "code": "TW",
            "emoji": "🇹🇼",
            "unicode": "U+1F1F9 U+1F1FC",
            "name": "Taiwan",
            "title": "flag for Taiwan",
        },
        {
            "code": "TZ",
            "emoji": "🇹🇿",
            "unicode": "U+1F1F9 U+1F1FF",
            "name": "Tanzania",
            "title": "flag for Tanzania",
        },
        {
            "code": "UA",
            "emoji": "🇺🇦",
            "unicode": "U+1F1FA U+1F1E6",
            "name": "Ukraine",
            "title": "flag for Ukraine",
        },
        {
            "code": "UG",
            "emoji": "🇺🇬",
            "unicode": "U+1F1FA U+1F1EC",
            "name": "Uganda",
            "title": "flag for Uganda",
        },
        {
            "code": "UM",
            "emoji": "🇺🇲",
            "unicode": "U+1F1FA U+1F1F2",
            "name": "United States Minor Outlying Islands",
            "title": "flag for United States Minor Outlying Islands",
        },
        {
            "code": "US",
            "emoji": "🇺🇸",
            "unicode": "U+1F1FA U+1F1F8",
            "name": "United States",
            "title": "flag for United States",
        },
        {
            "code": "UY",
            "emoji": "🇺🇾",
            "unicode": "U+1F1FA U+1F1FE",
            "name": "Uruguay",
            "title": "flag for Uruguay",
        },
        {
            "code": "UZ",
            "emoji": "🇺🇿",
            "unicode": "U+1F1FA U+1F1FF",
            "name": "Uzbekistan",
            "title": "flag for Uzbekistan",
        },
        {
            "code": "VA",
            "emoji": "🇻🇦",
            "unicode": "U+1F1FB U+1F1E6",
            "name": "Vatican City",
            "title": "flag for Vatican City",
        },
        {
            "code": "VC",
            "emoji": "🇻🇨",
            "unicode": "U+1F1FB U+1F1E8",
            "name": "Saint Vincent and The Grenadines",
            "title": "flag for Saint Vincent and The Grenadines",
        },
        {
            "code": "VE",
            "emoji": "🇻🇪",
            "unicode": "U+1F1FB U+1F1EA",
            "name": "Venezuela",
            "title": "flag for Venezuela",
        },
        {
            "code": "VG",
            "emoji": "🇻🇬",
            "unicode": "U+1F1FB U+1F1EC",
            "name": "Virgin Islands, British",
            "title": "flag for Virgin Islands, British",
        },
        {
            "code": "VI",
            "emoji": "🇻🇮",
            "unicode": "U+1F1FB U+1F1EE",
            "name": "Virgin Islands, U.S.",
            "title": "flag for Virgin Islands, U.S.",
        },
        {
            "code": "VN",
            "emoji": "🇻🇳",
            "unicode": "U+1F1FB U+1F1F3",
            "name": "Viet Nam",
            "title": "flag for Viet Nam",
        },
        {
            "code": "VU",
            "emoji": "🇻🇺",
            "unicode": "U+1F1FB U+1F1FA",
            "name": "Vanuatu",
            "title": "flag for Vanuatu",
        },
        {
            "code": "WF",
            "emoji": "🇼🇫",
            "unicode": "U+1F1FC U+1F1EB",
            "name": "Wallis and Futuna",
            "title": "flag for Wallis and Futuna",
        },
        {
            "code": "WS",
            "emoji": "🇼🇸",
            "unicode": "U+1F1FC U+1F1F8",
            "name": "Samoa",
            "title": "flag for Samoa",
        },
        {
            "code": "YE",
            "emoji": "🇾🇪",
            "unicode": "U+1F1FE U+1F1EA",
            "name": "Yemen",
            "title": "flag for Yemen",
        },
        {
            "code": "YT",
            "emoji": "🇾🇹",
            "unicode": "U+1F1FE U+1F1F9",
            "name": "Mayotte",
            "title": "flag for Mayotte",
        },
        {
            "code": "ZA",
            "emoji": "🇿🇦",
            "unicode": "U+1F1FF U+1F1E6",
            "name": "South Africa",
            "title": "flag for South Africa",
        },
        {
            "code": "ZM",
            "emoji": "🇿🇲",
            "unicode": "U+1F1FF U+1F1F2",
            "name": "Zambia",
            "title": "flag for Zambia",
        },
        {
            "code": "ZW",
            "emoji": "🇿🇼",
            "unicode": "U+1F1FF U+1F1FC",
            "name": "Zimbabwe",
            "title": "flag for Zimbabwe",
        },
    ]
    return [x for x in data if x["code"] == country_code][0]


def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i : i + n]
