# Generated by Django 3.2.12 on 2022-04-10 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemongo", "0005_add_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="_nickname",
            field=models.CharField(
                db_collation="case_insensitive",
                help_text="A local cached version of a trainers nickname.",
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{3,15}$", "Only letters and numbers are allowed.", "invalid"
                    )
                ],
                verbose_name="Nickname",
            ),
        ),
    ]
