# Generated by Django 2.1.3 on 2018-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0005_auto_20181205_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembershipdiscord',
            name='auto_import',
            field=models.BooleanField(default=True, help_text='This is currently not automatic.\nThere is no automatic removal.'),
        ),
    ]
