# Generated by Django 3.2.12 on 2022-04-10 08:20

from django.db import migrations


def cache_nicknames(apps, schema_editor):
    Trainer = apps.get_model("pokemongo", "Trainer")
    for trainer in Trainer.objects.select_related("owner").all():
        trainer._nickname = trainer.owner.username
        trainer.save(update_fields=["_nickname"])


class Migration(migrations.Migration):
    dependencies = [
        ("pokemongo", "0006_add_nickname_field_to_profile_for_caching"),
    ]

    operations = [
        migrations.RunPython(cache_nicknames, reverse_code=migrations.RunPython.noop),
    ]
