# Generated by Django 2.1.3 on 2018-12-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0007_auto_20181206_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="handle",
            field=models.SlugField(unique=True),
        ),
    ]
