# Generated by Django 4.0.4 on 2022-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0008_add_restraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255),
        ),
    ]
