# Generated by Django 3.2.12 on 2022-04-10 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0008_add_restraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Level'),
        ),
    ]
