# Generated by Django 2.1.3 on 2018-12-08 11:10

from django.db import migrations, models
import pokemongo.models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0009_auto_20181208_0155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="This should be your TOTAL XP screenshot.",
                upload_to=pokemongo.models.VerificationUpdateImagePath,
                verbose_name="Screenshot",
            ),
        ),
    ]
