# Generated by Django 2.1.3 on 2018-12-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0009_auto_20181208_0155"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="badge_great_league",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="update",
            name="badge_master_league",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="update",
            name="badge_ultra_league",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
