# Generated by Django 3.2.12 on 2022-04-10 09:52

from datetime import date
from django.db import migrations

from pokemongo.shortcuts import LEVELS, Level


def populate_levels(apps, schema_editor):
    Update = apps.get_model("pokemongo", "Update")
    for i in range(0, 40):
        l: Level = LEVELS[i]
        print(f"Setting levels {l.level}")
        Update.objects.filter(
            total_xp__gte=l.total_xp, total_xp__lt=l.total_xp + l.xp_required
        ).update(level=l.level)

    print("Setting legacy level 40s")
    Update.objects.filter(
        total_xp__gte=20_000_000, update_time__date__lte=date(2020, 11, 30)
    ).update(level=40)


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0009_add_levels"),
    ]

    operations = [
        migrations.RunPython(populate_levels, reverse_code=migrations.RunPython.noop),
    ]
