# Generated by Django 2.1.3 on 2018-12-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0011_auto_20181208_1340"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentBattleRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="This field can be blank if the match is in the future or hasn't been decided on when it'll happen.",
                        null=True,
                        verbose_name="Match Time",
                    ),
                ),
                (
                    "winner",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (-1, "Pending Results"),
                            (0, "tournament challenger"),
                            (1, "tournament opponent"),
                        ],
                        help_text="This field can be blank if the match is in the future or hasn't been decided on when it'll happen.",
                        null=True,
                    ),
                ),
                (
                    "challenger",
                    models.ForeignKey(
                        help_text="For knockout tournaments, I would recommend this to be the left/top Trainer.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_battles_as_challenger",
                        to="pokemongo.Trainer",
                        verbose_name="tournament challenger",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pokemongo.Community",
                        verbose_name="tournament host",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        help_text="For knockout tournaments, I would recommend this to be the right/bottom Trainer.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_battles_as_opponent",
                        to="pokemongo.Trainer",
                        verbose_name="tournament opponent",
                    ),
                ),
            ],
        ),
    ]
