# Generated by Django 4.0.6 on 2022-07-30 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemongo", "0012_rm_saved_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="trainer_level",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="Trainer Level",
            ),
        ),
        migrations.RunSQL(
            """UPDATE pokemongo_update
SET trainer_level = (
    CASE
          WHEN total_xp < 1000 THEN 1
          WHEN total_xp < 3000 THEN 2
          WHEN total_xp < 6000 THEN 3
          WHEN total_xp < 10000 THEN 4
          WHEN total_xp < 15000 THEN 5
          WHEN total_xp < 21000 THEN 6
          WHEN total_xp < 28000 THEN 7
          WHEN total_xp < 36000 THEN 8
          WHEN total_xp < 45000 THEN 9
          WHEN total_xp < 55000 THEN 10
          WHEN total_xp < 65000 THEN 11
          WHEN total_xp < 75000 THEN 12
          WHEN total_xp < 85000 THEN 13
          WHEN total_xp < 100000 THEN 14
          WHEN total_xp < 120000 THEN 15
          WHEN total_xp < 140000 THEN 16
          WHEN total_xp < 160000 THEN 17
          WHEN total_xp < 185000 THEN 18
          WHEN total_xp < 210000 THEN 19
          WHEN total_xp < 260000 THEN 20
          WHEN total_xp < 335000 THEN 21
          WHEN total_xp < 435000 THEN 22
          WHEN total_xp < 560000 THEN 23
          WHEN total_xp < 710000 THEN 24
          WHEN total_xp < 900000 THEN 25
          WHEN total_xp < 1100000 THEN 26
          WHEN total_xp < 1350000 THEN 27
          WHEN total_xp < 1650000 THEN 28
          WHEN total_xp < 2000000 THEN 29
          WHEN total_xp < 2500000 THEN 30
          WHEN total_xp < 3000000 THEN 31
          WHEN total_xp < 3750000 THEN 32
          WHEN total_xp < 4750000 THEN 33
          WHEN total_xp < 6000000 THEN 34
          WHEN total_xp < 7500000 THEN 35
          WHEN total_xp < 9500000 THEN 36
          WHEN total_xp < 12000000 THEN 37
          WHEN total_xp < 15000000 THEN 38
          WHEN total_xp < 20000000 THEN 39
          WHEN total_xp < 26000000 THEN 40
          ELSE NULL
    END
)
WHERE total_xp IS NOT NULL AND update_time >= '2020-11-30';"""
        ),
        migrations.RunSQL(
            """UPDATE pokemongo_update
SET trainer_level = (
    CASE
          WHEN total_xp < 1000 THEN 1
          WHEN total_xp < 3000 THEN 2
          WHEN total_xp < 6000 THEN 3
          WHEN total_xp < 10000 THEN 4
          WHEN total_xp < 15000 THEN 5
          WHEN total_xp < 21000 THEN 6
          WHEN total_xp < 28000 THEN 7
          WHEN total_xp < 36000 THEN 8
          WHEN total_xp < 45000 THEN 9
          WHEN total_xp < 55000 THEN 10
          WHEN total_xp < 65000 THEN 11
          WHEN total_xp < 75000 THEN 12
          WHEN total_xp < 85000 THEN 13
          WHEN total_xp < 100000 THEN 14
          WHEN total_xp < 120000 THEN 15
          WHEN total_xp < 140000 THEN 16
          WHEN total_xp < 160000 THEN 17
          WHEN total_xp < 185000 THEN 18
          WHEN total_xp < 210000 THEN 19
          WHEN total_xp < 260000 THEN 20
          WHEN total_xp < 335000 THEN 21
          WHEN total_xp < 435000 THEN 22
          WHEN total_xp < 560000 THEN 23
          WHEN total_xp < 710000 THEN 24
          WHEN total_xp < 900000 THEN 25
          WHEN total_xp < 1100000 THEN 26
          WHEN total_xp < 1350000 THEN 27
          WHEN total_xp < 1650000 THEN 28
          WHEN total_xp < 2000000 THEN 29
          WHEN total_xp < 2500000 THEN 30
          WHEN total_xp < 3000000 THEN 31
          WHEN total_xp < 3750000 THEN 32
          WHEN total_xp < 4750000 THEN 33
          WHEN total_xp < 6000000 THEN 34
          WHEN total_xp < 7500000 THEN 35
          WHEN total_xp < 9500000 THEN 36
          WHEN total_xp < 12000000 THEN 37
          WHEN total_xp < 15000000 THEN 38
          WHEN total_xp < 20000000 THEN 39
          ELSE 40
    END
)
WHERE total_xp IS NOT NULL AND update_time < '2020-11-30';"""
        ),
    ]
