# Generated by Django 2.1.3 on 2018-12-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0013_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainer",
            options={"verbose_name": "Trainer", "verbose_name_plural": "Trainers"},
        ),
        migrations.RemoveField(
            model_name="trainer",
            name="username",
        ),
        migrations.AlterModelTable(
            name="trainer",
            table=None,
        ),
    ]
