# Generated by Django 4.1 on 2022-09-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemongo", "0013_add_trainer_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="gym_gold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the List button under the Gym Badges category on your profile in game, and then counting how many are gold.",
                null=True,
                verbose_name="Gold Gym Badges",
            ),
        ),
    ]
