# Generated by Django 4.1 on 2022-09-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0014_rm_gym_validation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="update",
            name="double_check_confirmation",
        ),
    ]
