# Generated by Django 2.1.3 on 2018-12-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0010_auto_20181208_1110'),
        ('pokemongo', '0015_auto_20181208_1446'),
    ]

    operations = [
    ]
