# Generated by Django 4.1 on 2022-09-12 11:56

from decimal import Decimal

import django.core.validators
from django.db import migrations

import pokemongo.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0015_rm_double_check_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="battle_attack_won",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Win 4000 Gym battles.",
                null=True,
                verbose_name="Battle Girl",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_battles",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Battles",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_stardust",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Stardust Earned",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_streak",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Longest Streak",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_wins",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Wins",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_training_won",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Train 2000 times.", null=True, verbose_name="Ace Trainer"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="berries_fed",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Feed 15000 Berries at Gyms.",
                null=True,
                verbose_name="Berry Master",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="big_magikarp",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Catch 1000 big Magikarp.", null=True, verbose_name="Fisher"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="buddy_best",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Have 200 Best Buddies.",
                null=True,
                verbose_name="Best Buddy",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="capture_total",
            field=pokemongo.fields.BigIntegerStatistic(
                blank=True,
                help_text="Catch 50000 Pokémon.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Collector",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="challenge_quests",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Complete 2500 Field Research tasks.",
                null=True,
                verbose_name="Pokémon Ranger",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="evolved_total",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Evolve 2000 Pokémon.", null=True, verbose_name="Scientist"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="great_league",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Win 1000 Trainer Battles in the Great League.",
                null=True,
                verbose_name="Great League Veteran",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="gym_gold",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the List button under the Gym Badges category on your profile in game, and then counting how many are gold.",
                null=True,
                verbose_name="Gold Gym Badges",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="hatched_total",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Hatch 2500 eggs.", null=True, verbose_name="Breeder"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="hours_defended",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Defend Gyms for 15000 hours.",
                null=True,
                verbose_name="Gym Leader",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="legendary_battle_won",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Win 2000 Legendary raids.",
                null=True,
                verbose_name="Battle Legend",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="master_league",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Win 1000 Trainer Battles in the Master League.",
                null=True,
                verbose_name="Master League Veteran",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="max_level_friends",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Become Best Friends with 20 Trainers.",
                null=True,
                verbose_name="Idol",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="mini_collection",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Complete Collection Challenges.",
                null=True,
                verbose_name="Elite Collector",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="mvt",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Made the Raid Battle Trainer Achievements screen 200 times.",
                null=True,
                verbose_name="Raid Expert",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="photobomb",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Have 400 surprise encounters in GO Snapshot.",
                null=True,
                verbose_name="Cameraman",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pikachu",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Catch 1000 Pikachu.", null=True, verbose_name="Pikachu Fan"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_caught",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the POKÉDEX button in your game. It should then be listed at the top of the screen.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Unique Species Caught",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 151 Kanto region Pokémon in the Pokédex.",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(151),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Kanto",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen2",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 100 Pokémon first discovered in the Johto region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Johto",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen3",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 135 Pokémon first discovered in the Hoenn region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(135)],
                verbose_name="Hoenn",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen4",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 107 Pokémon first discovered in the Sinnoh region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(107)],
                verbose_name="Sinnoh",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen5",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 156 Pokémon first discovered in the Unova region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(156)],
                verbose_name="Unova",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen6",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 72 Pokémon first discovered in the Kalos region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(72)],
                verbose_name="Kalos",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen7",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 50 Pokémon first discovered in the Alola region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(88)],
                verbose_name="Alola",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_entries_gen8",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 50 Pokémon first discovered in the Alola region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(89)],
                verbose_name="Galar",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_seen",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="You can find this by clicking the POKÉDEX button in your game. It should then be listed at the top of the screen.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Unique Species Seen",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokemon_caught_at_your_lures",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Use a Lure Module to help another Trainer catch a Pokémon.",
                null=True,
                verbose_name="Picnicker",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokemon_purified",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Purify 1000 Shadow Pokémon.",
                null=True,
                verbose_name="Purifier",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokestops_visited",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Visit 50000 PokéStops.",
                null=True,
                verbose_name="Backpacker",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="raid_battle_won",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Win 2000 raids.", null=True, verbose_name="Champion"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="raids_with_friends",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Win 2000 raids with a friend.",
                null=True,
                verbose_name="Rising Star Duo",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="rocket_giovanni_defeated",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Defeat the Team GO Rocket Boss 50 times. ",
                null=True,
                verbose_name="Ultra Hero",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="rocket_grunts_defeated",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Defeat 2000 Team GO Rocket Grunts.",
                null=True,
                verbose_name="Hero",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="seven_day_streaks",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Achieve a Pokémon catch streak or PokéStop spin streak of seven days 100 times.",
                null=True,
                verbose_name="Triathlete",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="small_rattata",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 1000 tiny Rattata.",
                null=True,
                verbose_name="Youngster",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="total_mega_evos",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Mega Evolve a Pokémon 1000 times.",
                null=True,
                verbose_name="Successor",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="total_xp",
            field=pokemongo.fields.BigIntegerStatistic(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(100)],
                verbose_name="Total XP",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="trading",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Trade 2500 Pokémon.", null=True, verbose_name="Gentleman"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="trading_distance",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Earn 10000000 km across the distance of all Pokémon trades.",
                null=True,
                verbose_name="Pilot",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="trainers_referred",
            field=pokemongo.fields.IntegerStatistic(
                blank=True, help_text="Refer 20 Trainers", null=True, verbose_name="Friend Finder"
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="travel_km",
            field=pokemongo.fields.DecimalStatistic(
                blank=True,
                decimal_places=2,
                help_text="Walk 10,000 km.",
                max_digits=16,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Jogger",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_bug",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Bug-type Pokémon.",
                null=True,
                verbose_name="Bug Catcher",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_dark",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Dark-type Pokémon.",
                null=True,
                verbose_name="Delinquent",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_dragon",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Dragon-type Pokémon.",
                null=True,
                verbose_name="Dragon Tamer",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_electric",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Electric-type Pokémon.",
                null=True,
                verbose_name="Rocker",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_fairy",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Fairy-type Pokémon.",
                null=True,
                verbose_name="Fairy Tale Girl",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_fighting",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Fighting-type Pokémon.",
                null=True,
                verbose_name="Black Belt",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_fire",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Fire-type Pokémon.",
                null=True,
                verbose_name="Kindler",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_flying",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Flying-type Pokémon.",
                null=True,
                verbose_name="Bird Keeper",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_ghost",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Ghost-type Pokémon.",
                null=True,
                verbose_name="Hex Maniac",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_grass",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Grass-type Pokémon.",
                null=True,
                verbose_name="Gardener",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_ground",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Ground-type Pokémon.",
                null=True,
                verbose_name="Ruin Maniac",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_ice",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Ice-type Pokémon.",
                null=True,
                verbose_name="Skier",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_normal",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Normal-type Pokémon.",
                null=True,
                verbose_name="Schoolkid",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_poison",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Poison-type Pokémon.",
                null=True,
                verbose_name="Punk Girl",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_psychic",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Psychic-type Pokémon.",
                null=True,
                verbose_name="Psychic",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_rock",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Rock-type Pokémon.",
                null=True,
                verbose_name="Hiker",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_steel",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Steel-type Pokémon.",
                null=True,
                verbose_name="Rail Staff",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="type_water",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 200 Water-type Pokémon.",
                null=True,
                verbose_name="Swimmer",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="ultra_league",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Win 1000 Trainer Battles in the Ultra League.",
                null=True,
                verbose_name="Ultra League Veteran",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="unique_mega_evos",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Mega Evolve 46 different species of Pokémon.",
                null=True,
                verbose_name="Mega Evolution Guru",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="unique_pokestops",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Visit 2000 unique PokéStops.",
                null=True,
                verbose_name="Sightseer",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="unique_raid_bosses_defeated",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Defeat 150 different species of Pokémon in raids.",
                null=True,
                verbose_name="Rising Star",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="unown",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 28 Unown.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(28)],
                verbose_name="Unown",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="wayfarer",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Earn 1500 Wayfarer Agreements",
                null=True,
                verbose_name="Wayfarer",
            ),
        ),
    ]
