# Generated by Django 4.1 on 2022-09-12 12:27

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0016_alter_update_battle_attack_won_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainer",
            old_name="country_iso",
            new_name="country",
        ),
        migrations.AlterField(
            model_name="trainer",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Where are you based?",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
    ]
