# Generated by Django 2.1.4 on 2018-12-24 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0017_auto_20181213_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen4',
            field=models.PositiveIntegerField(blank=True, help_text='Register 80 Pokémon first discovered in the Sinnoh region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(61)], verbose_name='Sinnoh'),
        ),
    ]
