# Generated by Django 4.1.7 on 2023-04-01 18:30

import django.core.validators
from django.db import migrations
import pokemongo.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pokemongo", "0017_alter_trainer_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="butterfly_collector",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Collect Vivillon from all over the world.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(18)],
                verbose_name="Vivillon Collector",
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="capture_large_pokemon",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 100 XXL Pokémon.",
                null=True,
                verbose_name="Jumbo Pokémon Collector",
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="capture_small_pokemon",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Catch 100 XXS Pokémon.",
                null=True,
                verbose_name="Tiny Pokémon Collector",
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="pokedex_entries_gen8a",
            field=pokemongo.fields.IntegerStatistic(
                blank=True,
                help_text="Register 5 Pokémon first discovered in the Hisui region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(7)],
                verbose_name="Hisui",
            ),
        ),
    ]
