# Generated by Django 4.2 on 2023-04-11 21:35

import django.core.validators
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemongo", "0018_add_stats"),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        migrations.AlterField(
            model_name="nickname",
            name="nickname",
            field=models.CharField(
                db_collation="case_insensitive",
                db_index=True,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{3,15}$",
                        "Only letters and numbers are allowed.",
                        "invalid",
                    )
                ],
                verbose_name="Nickname",
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="_nickname",
            field=models.CharField(
                db_collation="case_insensitive",
                db_index=True,
                editable=False,
                help_text="A local cached version of a trainers nickname.",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{3,15}$",
                        "Only letters and numbers are allowed.",
                        "invalid",
                    )
                ],
                verbose_name="Nickname",
            ),
        ),
    ]
