# Generated by Django 2.1.4 on 2019-01-30 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0018_auto_20181224_2312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="badge_pokedex_entries_gen4",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Register 80 Pokémon first discovered in the Sinnoh region to the Pokédex.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(62)],
                verbose_name="Sinnoh",
            ),
        ),
    ]
