# Generated by Django 2.1.4 on 2019-02-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0021_gen4mammoswine'),
        ('pokemongo', '0024_auto_20190210_2133'),
    ]

    operations = [
    ]
