# Generated by Django 2.2.15 on 2020-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0033_auto_20200829_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='badge_battle_attack_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1,000 Gym battles.', null=True, verbose_name='Battle Girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_battle_training_won',
            field=models.PositiveIntegerField(blank=True, help_text='Train 1,000 times.', null=True, verbose_name='Ace Trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_berries_fed',
            field=models.PositiveIntegerField(blank=True, help_text='Feed 1,000 Berries at Gyms.', null=True, verbose_name='Berry Master'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_capture_total',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 2,000 Pokémon.', null=True, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_challenge_quests',
            field=models.PositiveIntegerField(blank=True, help_text='Complete 1,000 Field Research tasks.', null=True, verbose_name='Pokémon Ranger'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_hours_defended',
            field=models.PositiveIntegerField(blank=True, help_text='Defend Gyms for 1,000 hours.', null=True, verbose_name='Gym Leader'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_legendary_battle_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1,000 Legendary raids.', null=True, verbose_name='Battle Legend'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_photobomb',
            field=models.PositiveIntegerField(blank=True, help_text='Have 200 surprise encounters in GO Snapshot.', null=True, verbose_name='Cameraman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokestops_visited',
            field=models.PositiveIntegerField(blank=True, help_text='Visit 2,000 PokéStops.', null=True, verbose_name='Backpacker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_raid_battle_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1,000 raids.', null=True, verbose_name='Champion'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_rocket_grunts_defeated',
            field=models.PositiveIntegerField(blank=True, help_text='Defeat 1,000 Team GO Rocket Grunts.', null=True, verbose_name='Hero'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_trading',
            field=models.PositiveIntegerField(blank=True, help_text='Trade 1,000 Pokémon.', null=True, verbose_name='Gentleman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_trading_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Earn 1,000,000 km across the distance of all Pokémon trades.', null=True, verbose_name='Pilot'),
        ),
    ]
