# Generated by Django 2.2.16 on 2020-09-12 00:00

from django.db import migrations, models
import pokemongo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0038_auto_20200829_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('de-DE', 'German'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('it-IT', 'Italian'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('pt-BR', 'Brazilian Portuguese'), ('th-TH', 'Thai'), ('zh-HK', 'Traditional Chinese')], default='en-US', max_length=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='statistics',
            field=models.BooleanField(default=True, help_text='Would you like to be shown on the leaderboard? Ticking this box gives us permission to process your data.', verbose_name='Stats'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='verification',
            field=models.ImageField(blank=True, upload_to=pokemongo.models.VerificationImagePath, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_battle_attack_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1000 Gym battles.', null=True, verbose_name='Battle Girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_battle_training_won',
            field=models.PositiveIntegerField(blank=True, help_text='Train 1000 times.', null=True, verbose_name='Ace Trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_berries_fed',
            field=models.PositiveIntegerField(blank=True, help_text='Feed 1000 Berries at Gyms.', null=True, verbose_name='Berry Master'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_capture_total',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 2000 Pokémon.', null=True, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_challenge_quests',
            field=models.PositiveIntegerField(blank=True, help_text='Complete 1000 Field Research tasks.', null=True, verbose_name='Pokémon Ranger'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_hours_defended',
            field=models.PositiveIntegerField(blank=True, help_text='Defend Gyms for 1000 hours.', null=True, verbose_name='Gym Leader'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_legendary_battle_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1000 Legendary raids.', null=True, verbose_name='Battle Legend'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokestops_visited',
            field=models.PositiveIntegerField(blank=True, help_text='Visit 2000 PokéStops.', null=True, verbose_name='Backpacker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_raid_battle_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1000 raids.', null=True, verbose_name='Champion'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_rocket_giovanni_defeated',
            field=models.PositiveIntegerField(blank=True, help_text='Defeat the Team GO Rocket Boss 20 times. ', null=True, verbose_name='Ultra Hero'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_rocket_grunts_defeated',
            field=models.PositiveIntegerField(blank=True, help_text='Defeat 1000 Team GO Rocket Grunts.', null=True, verbose_name='Hero'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_trading',
            field=models.PositiveIntegerField(blank=True, help_text='Trade 1000 Pokémon.', null=True, verbose_name='Gentleman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_trading_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Earn 1000000 km across the distance of all Pokémon trades.', null=True, verbose_name='Pilot'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_travel_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Walk 1,000 km.', max_digits=16, null=True, verbose_name='Jogger'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_steel',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Steel-type Pokémon', null=True, verbose_name='Rail Staff'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_unique_mega_evos',
            field=models.PositiveIntegerField(blank=True, help_text='Mega Evolve 36 different species of Pokémon.', null=True, verbose_name='Mega Evolution Guru'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_wayfarer',
            field=models.PositiveIntegerField(blank=True, help_text='Earn 1000 Wayfarer Agreements', null=True, verbose_name='Wayfarer'),
        ),
    ]
