# Generated by Django 2.2.16 on 2020-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0039_auto_20200912_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='battle_hub_stats_battles',
            field=models.PositiveIntegerField(blank=True, help_text='PVP Battles. Can be found in the Battle Hub.', null=True, verbose_name='Battles'),
        ),
        migrations.AddField(
            model_name='update',
            name='battle_hub_stats_stardust',
            field=models.PositiveIntegerField(blank=True, help_text='PVP Stardust Earned. Can be found in the Battle Hub.', null=True, verbose_name='Stardust Earned'),
        ),
        migrations.AddField(
            model_name='update',
            name='battle_hub_stats_streak',
            field=models.PositiveIntegerField(blank=True, help_text='PVP Longest Streak. Can be found in the Battle Hub.', null=True, verbose_name='Longest Streak'),
        ),
        migrations.AddField(
            model_name='update',
            name='battle_hub_stats_wins',
            field=models.PositiveIntegerField(blank=True, help_text='PVP Wins. Can be found in the Battle Hub.', null=True, verbose_name='Wins'),
        ),
    ]
