# Generated by Django 2.2.17 on 2020-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0040_auto_20201120_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='badge_type_bug',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Bug-type Pokémon.', null=True, verbose_name='Bug Catcher'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_dark',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Dark-type Pokémon.', null=True, verbose_name='Delinquent'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_dragon',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Dragon-type Pokémon.', null=True, verbose_name='Dragon Tamer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_electric',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Electric-type Pokémon.', null=True, verbose_name='Rocker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_fairy',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Fairy-type Pokémon.', null=True, verbose_name='Fairy Tale Girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_fighting',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Fighting-type Pokémon.', null=True, verbose_name='Black Belt'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_fire',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Fire-type Pokémon.', null=True, verbose_name='Kindler'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_flying',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Flying-type Pokémon.', null=True, verbose_name='Bird Keeper'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_ghost',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Ghost-type Pokémon.', null=True, verbose_name='Hex Maniac'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_grass',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Grass-type Pokémon.', null=True, verbose_name='Gardener'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_ground',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Ground-type Pokémon.', null=True, verbose_name='Ruin Maniac'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_ice',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Ice-type Pokémon.', null=True, verbose_name='Skier'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_normal',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Normal-type Pokémon.', null=True, verbose_name='Schoolkid'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_poison',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Poison-type Pokémon.', null=True, verbose_name='Punk Girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_psychic',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Psychic-type Pokémon.', null=True, verbose_name='Psychic'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_rock',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Rock-type Pokémon.', null=True, verbose_name='Hiker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_steel',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Steel-type Pokémon.', null=True, verbose_name='Rail Staff'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_type_water',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 200 Water-type Pokémon.', null=True, verbose_name='Swimmer'),
        ),
    ]
