# Generated by Django 2.2.18.dev20201210010402 on 2020-12-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0046_add_rsduo'),
        ('pokemongo', '0046_auto_20201127_0144'),
    ]

    operations = [
    ]
