# Generated by Django 2.2.18.dev20201210025334 on 2020-12-10 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0047_merge_20201210_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen5',
            field=models.PositiveIntegerField(blank=True, help_text='Register 156 Pokémon first discovered in the Unova region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(156)], verbose_name='Unova'),
        ),
    ]
