# Generated by Django 2.2.27 on 2022-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0053_auto_20211204_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="country_iso",
            field=models.CharField(
                blank=True,
                help_text="Where are you based?",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
    ]
