# Generated by Django 2.2.27 on 2022-03-16 19:00

from django.db import migrations


def fill_country(apps, schema_editor):
    Trainer = apps.get_model("pokemongo", "Trainer")
    for trainer in Trainer.objects.order_by("id").all():
        if trainer.leaderboard_country:
            print("setting country for {} to {}".format(trainer, trainer.leaderboard_country.code))
            trainer.country_iso = trainer.leaderboard_country.code
            trainer.save(update_fields=["country_iso"])
        else:
            print("not setting country for {}".format(trainer))


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0054_add_temp_country_field"),
    ]

    operations = [
        migrations.RunPython(fill_country, migrations.RunPython.noop),
    ]
