# Generated by Django 2.2.27 on 2022-03-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0055_fill_temp_country_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='leaderboard_country',
        ),
    ]
