# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import trainer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discord_Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('ban', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discord_Servers',
            fields=[
                ('s_name', models.CharField(max_length=256)),
                ('s_region', models.CharField(max_length=256)),
                ('s_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('s_icon', models.CharField(max_length=256)),
                ('bans_cheaters', models.BooleanField(default=True)),
                ('seg_cheaters', models.BooleanField(default=False)),
                ('bans_minors', models.BooleanField(default=False)),
                ('seg_minors', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discord_Users',
            fields=[
                ('d_name', models.CharField(max_length=32)),
                ('d_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('d_discriminator', models.CharField(max_length=256)),
                ('d_avatar_url', models.URLField()),
                ('d_creation', models.DateTimeField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('real_name', models.CharField(blank=True, max_length=256, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.Directory_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('xp', models.IntegerField(verbose_name='Total XP')),
                ('dex_caught', models.IntegerField(blank=True, null=True)),
                ('dex_seen', models.IntegerField(blank=True, null=True)),
                ('walk_dist', models.IntegerField(blank=True, null=True)),
                ('gen_1_dex', models.IntegerField(blank=True, null=True)),
                ('pkmn_caught', models.IntegerField(blank=True, null=True)),
                ('pkmn_evolved', models.IntegerField(blank=True, null=True)),
                ('pkstops_spun', models.IntegerField(blank=True, null=True)),
                ('battles_won', models.IntegerField(blank=True, null=True)),
                ('gen_2_dex', models.IntegerField(blank=True, null=True)),
                ('berry_fed', models.IntegerField(blank=True, null=True)),
                ('gym_defended', models.IntegerField(blank=True, null=True)),
                ('eggs_hatched', models.IntegerField(blank=True, null=True)),
                ('big_magikarp', models.IntegerField(blank=True, null=True)),
                ('legacy_gym_trained', models.IntegerField(blank=True, null=True)),
                ('tiny_rattata', models.IntegerField(blank=True, null=True)),
                ('pikachu_caught', models.IntegerField(blank=True, null=True)),
                ('unown_alphabet', models.IntegerField(blank=True, null=True)),
                ('raids_completed', models.IntegerField(blank=True, null=True)),
                ('pkmn_normal', models.IntegerField(blank=True, null=True)),
                ('pkmn_flying', models.IntegerField(blank=True, null=True)),
                ('pkmn_poison', models.IntegerField(blank=True, null=True)),
                ('pkmn_ground', models.IntegerField(blank=True, null=True)),
                ('pkmn_rock', models.IntegerField(blank=True, null=True)),
                ('pkmn_bug', models.IntegerField(blank=True, null=True)),
                ('pkmn_steel', models.IntegerField(blank=True, null=True)),
                ('pkmn_fire', models.IntegerField(blank=True, null=True)),
                ('pkmn_water', models.IntegerField(blank=True, null=True)),
                ('pkmn_grass', models.IntegerField(blank=True, null=True)),
                ('pkmn_electric', models.IntegerField(blank=True, null=True)),
                ('pkmn_psychic', models.IntegerField(blank=True, null=True)),
                ('pkmn_dark', models.IntegerField(blank=True, null=True)),
                ('pkmn_fairy', models.IntegerField(blank=True, null=True)),
                ('pkmn_fighting', models.IntegerField(blank=True, null=True)),
                ('pkmn_ghost', models.IntegerField(blank=True, null=True)),
                ('pkmn_ice', models.IntegerField(blank=True, null=True)),
                ('pkmn_dragon', models.IntegerField(blank=True, null=True)),
                ('gym_badges', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(max_length=140)),
                ('faction_colour', models.IntegerField(blank=True, null=True)),
                ('faction_image', models.ImageField(blank=True, null=True, upload_to=trainer.models.factionImagePath)),
                ('leader_name', models.CharField(blank=True, max_length=140, null=True)),
                ('leader_image', models.ImageField(blank=True, null=True, upload_to=trainer.models.leaderImagePath)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('has_cheated', models.BooleanField(default=False)),
                ('last_cheated', models.DateField(blank=True, null=True)),
                ('currently_cheats', models.BooleanField(default=False)),
                ('statistics', models.BooleanField(default=True)),
                ('daily_goal', models.IntegerField(blank=True, null=True)),
                ('total_goal', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.Directory_Users')),
                ('discord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.Discord_Users')),
                ('faction', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Factions')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Levels',
            fields=[
                ('level', models.AutoField(primary_key=True, serialize=False)),
                ('min_total_xp', models.IntegerField(blank=True)),
                ('relative_xp', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='discord_servers',
            name='s_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.Discord_Users'),
        ),
        migrations.AddField(
            model_name='discord_relations',
            name='d_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Discord_Users'),
        ),
        migrations.AddField(
            model_name='discord_relations',
            name='d_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Discord_Servers'),
        ),
    ]
