# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'get_latest_by': 'datetime', 'ordering': ['datetime']},
        ),
    ]
