# Generated by Django 2.1.2 on 2018-11-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_squashed_0080_auto_20181017_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factionleader',
            name='faction',
        ),
        migrations.DeleteModel(
            name='FactionLeader',
        ),
    ]
