# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 14:15
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0002_auto_20170906_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discord_relation',
            old_name='d_server',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='discord_relation',
            old_name='d_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='discord_server',
            old_name='s_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='discord_server',
            old_name='s_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='discord_server',
            old_name='s_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='discord_server',
            old_name='s_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='discord_server',
            old_name='s_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='discord_user',
            old_name='d_avatar_url',
            new_name='avatar_url',
        ),
        migrations.RenameField(
            model_name='discord_user',
            old_name='d_creation',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='discord_user',
            old_name='d_discriminator',
            new_name='discriminator',
        ),
        migrations.RenameField(
            model_name='discord_user',
            old_name='d_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='discord_user',
            old_name='d_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='faction',
            old_name='faction_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='faction',
            old_name='faction_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='discord_user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='discord_user',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='faction_colour',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='account',
        ),
        migrations.AddField(
            model_name='faction',
            name='colour',
            field=colorful.fields.RGBColorField(blank=True, default='#929292', null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='ekpogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainer',
            name='prefered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discord_user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Faction'),
        ),
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=16, null=True),
        ),
        migrations.DeleteModel(
            name='Directory_Users',
        ),
    ]
