# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20170919_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'get_latest_by': 'datetime', 'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='seg_cheaters',
            field=models.BooleanField(default=False, verbose_name='segregates cheaters'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='seg_minors',
            field=models.BooleanField(default=False, verbose_name='segregates minors'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='currently_cheats',
            field=models.BooleanField(default=False, verbose_name='known spoofer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='has_cheated',
            field=models.BooleanField(default=False, verbose_name='known to have spoofed'),
        ),
        migrations.AlterField(
            model_name='update',
            name='battles_won',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='battle girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='berry_fed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='berry master'),
        ),
        migrations.AlterField(
            model_name='update',
            name='big_magikarp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fisherman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='seen'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_seen',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='eggs_hatched',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='breeder'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_1_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kanto'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_2_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='johto'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gym_defended',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='gym leader'),
        ),
        migrations.AlterField(
            model_name='update',
            name='legacy_gym_trained',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ace trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pikachu_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pikachu fan'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_bug',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='bug catcher'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='collector'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_dark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='delinquent'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_dragon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dragon tamer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_electric',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='rocker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_evolved',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='scientist'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fairy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fairy tale girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fighting',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='black belt'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fire',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kindler'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_flying',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='bird keeper'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_ghost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hex maniac'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_grass',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='gardener'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_ground',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ruin maniac'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_ice',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='skier'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_normal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='schoolkid'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_poison',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='punk girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_psychic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='psychic'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_rock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hiker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_steel',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='depot agent'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_water',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='swimmer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkstops_spun',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='backpacker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='raids_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='champion'),
        ),
        migrations.AlterField(
            model_name='update',
            name='tiny_rattata',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='youngster'),
        ),
        migrations.AlterField(
            model_name='update',
            name='unown_alphabet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='unown'),
        ),
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=16, null=True, verbose_name='jogger'),
        ),
    ]
