# Generated by Django 2.1.3 on 2018-11-04 14:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20181104_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date you created your Pokémon Go account.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2016, 7, 5))], verbose_name='Start Date'),
        ),
    ]
