# Generated by Django 2.1.3 on 2018-11-04 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_fix_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen3',
            field=models.PositiveIntegerField(blank=True, help_text='Register 90 Pokémon first discovered in the Hoenn region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(130)], verbose_name='Hoenn'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen4',
            field=models.PositiveIntegerField(blank=True, help_text='Register 80 Pokémon first discovered in the Sinnoh region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(32)], verbose_name='Sinnoh'),
        ),
    ]
