# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20170921_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='gen_3_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hoenn'),
        ),
        migrations.AddField(
            model_name='update',
            name='go_fest_2017',
            field=models.BooleanField(default=False, verbose_name='Pokémon GO Fest Chicago'),
        ),
        migrations.AddField(
            model_name='update',
            name='outbreak_2017',
            field=models.BooleanField(default=False, verbose_name='Pikachu Outbreak 2017'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_amstelveen',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Amstelveen, The Netherlands'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_barcelona',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Barcelona, Spain'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_copenhagen',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Copenhagen, Denmark'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_oberhausen',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Oberhausen, Germany'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_paris',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Paris, France'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_prague',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Prague, Czechia'),
        ),
        migrations.AddField(
            model_name='update',
            name='safari_zone_2017_stockholm',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Stockholm, Sweden'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='jogger'),
        ),
    ]
