# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 20:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('trainer', '0004_rename_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=140)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=50)),
                ('reportee', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Trainer_Level',
        ),
        migrations.RemoveField(
            model_name='discordmember',
            name='ban',
        ),
        migrations.RemoveField(
            model_name='discordmember',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='join_date',
        ),
        migrations.AddField(
            model_name='discordmember',
            name='join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discordserver',
            name='members',
            field=models.ManyToManyField(related_name='discord_members', through='trainer.DiscordMember', to='trainer.DiscordUser'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discriminator',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Faction', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='prefered',
            field=models.BooleanField(default=True, verbose_name='main profile'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 7, 13), null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='network',
            name='banned_users',
            field=models.ManyToManyField(related_name='banned_network_members', through='trainer.Ban', to='trainer.DiscordUser'),
        ),
        migrations.AddField(
            model_name='network',
            name='discord_servers',
            field=models.ManyToManyField(related_name='network_discord', to='trainer.DiscordServer'),
        ),
        migrations.AddField(
            model_name='network',
            name='members',
            field=models.ManyToManyField(related_name='network_members', through='trainer.NetworkMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='network',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ban',
            name='discord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.DiscordServer'),
        ),
        migrations.AddField(
            model_name='ban',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.Network'),
        ),
        migrations.AddField(
            model_name='ban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.DiscordUser'),
        ),
    ]
