# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20171015_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='go_fest_2017',
        ),
        migrations.RemoveField(
            model_name='update',
            name='outbreak_2017',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_amstelveen',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_barcelona',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_copenhagen',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_oberhausen',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_paris',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_prague',
        ),
        migrations.RemoveField(
            model_name='update',
            name='safari_zone_2017_stockholm',
        ),
        migrations.AddField(
            model_name='trainer',
            name='go_fest_2017',
            field=models.BooleanField(default=False, verbose_name='Pokémon GO Fest Chicago'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='outbreak_2017',
            field=models.BooleanField(default=False, verbose_name='Pikachu Outbreak 2017'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_amstelveen',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Amstelveen, The Netherlands'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_barcelona',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Barcelona, Spain'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_copenhagen',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Copenhagen, Denmark'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_oberhausen',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Oberhausen, Germany'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_paris',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Paris, France'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_prague',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Prague, Czechia'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='safari_zone_2017_stockholm',
            field=models.BooleanField(default=False, verbose_name='Safari Zone - Stockholm, Sweden'),
        ),
    ]
