# Generated by Django 2.1.3 on 2018-11-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_IncreasePokedexBadges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityleague',
            name='memberships_discord',
        ),
        migrations.RemoveField(
            model_name='communityleague',
            name='memberships_personal',
        ),
        migrations.RemoveField(
            model_name='communityleaguemembershipdiscord',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='communityleaguemembershipdiscord',
            name='league',
        ),
        migrations.RemoveField(
            model_name='communityleaguemembershippersonal',
            name='league',
        ),
        migrations.RemoveField(
            model_name='communityleaguemembershippersonal',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainerreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='trainerreport',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='CommunityLeague',
        ),
        migrations.DeleteModel(
            name='CommunityLeagueMembershipDiscord',
        ),
        migrations.DeleteModel(
            name='CommunityLeagueMembershipPersonal',
        ),
        migrations.DeleteModel(
            name='DiscordGuild',
        ),
        migrations.DeleteModel(
            name='TrainerReport',
        ),
    ]
