# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20171015_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='leg_raids_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='battle legend'),
        ),
    ]
