# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20170908_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
