# Generated by Django 2.1.3 on 2018-11-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20181123_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='thesilphroad_username',
        ),
    ]
