# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20170913_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='leader_image',
            field=models.ImageField(blank=True, null=True, upload_to=trainer.models.factionImagePath),
        ),
    ]
