# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_update_leg_raids_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
