# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 19:43
from __future__ import unicode_literals

from django.db import migrations
from datetime import date

def clear_default_start_date(apps, schema_editor):
    Trainer = apps.get_model('trainer', 'Trainer')
    for trainer in Trainer.objects.all():
        if trainer.start_date == date(2016,7,13):
            trainer.start_date = None
            trainer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20171107_1943'),
    ]
    
    operations=[
        migrations.RunPython(clear_default_start_date),
    ]