# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20170913_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
