# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_clear_default_start_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='leader_image',
            field=models.ImageField(blank=True, null=True, upload_to=trainer.models.leaderImagePath),
        ),
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
