# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 19:43
from __future__ import unicode_literals

from django.db import migrations
from datetime import date

def migrate_discord_users(apps, schema_editor):
    DiscordUser = apps.get_model('trainer', 'DiscordUser')
    AuthUser = apps.get_model('socialaccount', 'SocialAccount')
    for user in DiscordUser.objects.all():
        extra_data = {}
        extra_data['username'] = user.name
        extra_data['id'] = user.id
        extra_data['discriminator'] = user.discriminator
        if user.avatar_url.startswith('https://cdn.discordapp.com/avatars'):
            extra_data['avatar'] = user.avatar_url.replace('https://cdn.discordapp.com/avatars/{}/'.format(user.id), '').split('.')[0]
            
        AuthUser.objects.create(user=user.account, uid=user.id, provider='discord', date_joined=user.creation, extra_data=extra_data)

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_clear_default_start_dates'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]
    
    operations=[
        migrations.RunPython(migrate_discord_users),
    ]