# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_migrate_discord_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='ban',
            name='network',
        ),
        migrations.RemoveField(
            model_name='ban',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discordmember',
            name='server',
        ),
        migrations.RemoveField(
            model_name='discordmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='network',
            name='banned_users',
        ),
        migrations.RemoveField(
            model_name='network',
            name='discord_servers',
        ),
        migrations.RemoveField(
            model_name='network',
            name='members',
        ),
        migrations.RemoveField(
            model_name='network',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='networkmember',
            name='network',
        ),
        migrations.RemoveField(
            model_name='networkmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='members',
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
        migrations.DeleteModel(
            name='DiscordMember',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NetworkMember',
        ),
    ]
