# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20171107_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='account',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='owner',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
    ]
