# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_auto_20171107_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Faction', verbose_name='team'),
        ),
    ]
