# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0011_rename_servers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='ban',
            name='network',
        ),
        migrations.RemoveField(
            model_name='ban',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discordmember',
            name='server',
        ),
        migrations.RemoveField(
            model_name='discordmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='account',
        ),
        migrations.RemoveField(
            model_name='network',
            name='banned_users',
        ),
        migrations.RemoveField(
            model_name='network',
            name='discord_servers',
        ),
        migrations.RemoveField(
            model_name='network',
            name='members',
        ),
        migrations.RemoveField(
            model_name='network',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='networkmember',
            name='network',
        ),
        migrations.RemoveField(
            model_name='networkmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='account',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='discordguild',
            name='members',
        ),
        migrations.RemoveField(
            model_name='discordguild',
            name='owner',
        ),
        migrations.AddField(
            model_name='discordguild',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Faction', verbose_name='team'),
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
        migrations.DeleteModel(
            name='DiscordMember',
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NetworkMember',
        ),
    ]
