# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import trainer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_auto_20171209_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'get_latest_by': 'update_time', 'ordering': ['-update_time']},
        ),
        migrations.RenameField(
            model_name='update',
            old_name='datetime',
            new_name='update_time',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[trainer.validators.validate_startdate]),
        ),
    ]
