# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20171109_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='account',
            new_name='owner',
        ),
    ]
