# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20171212_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedprofile',
            name='prefered_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_profiles', to='trainer.Trainer'),
        ),
    ]
