# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def prefered_forward(apps, schema_editor):
    Trainer = apps.get_model('trainer', 'Trainer')
    User = apps.get_model('trainer', 'ExtendedProfile')
    for trainer in Trainer.objects.all():
        if trainer.owner is not None and trainer.prefered is True:
            print("Setting default trainer for {x.owner.username} to {x.username}".format(trainer))
            user = User.objects.get(user=trainer.owner)
            user.prefered_profile = trainer
            user.save()

def prefered_backward(apps, schema_editor):
    print("Data about prefered profile is lost, sorry.")

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20171212_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedprofile',
            name='prefered_profile',
            field=models.ForeignKey(blank=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_profiles', to='trainer.Trainer'),
        ),
        migrations.RunPython(prefered_forward, prefered_backward),
        migrations.RemoveField(
            model_name='trainer',
            name='prefered',
        ),

    ]
