# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models

def prefered_forward(apps, schema_editor):
    Trainer = apps.get_model('trainer', 'Trainer')
    User = apps.get_model('trainer', 'ExtendedProfile')
    for trainer in Trainer.objects.all():
        if trainer.owner is not None and trainer.prefered is True:
            print("Setting default trainer for {x.owner.username} to {x.username}".format(x=trainer))
            user = User.objects.get(user=trainer.owner)
            user.prefered_profile = trainer
            user.save()

def prefered_backward(apps, schema_editor):
    print("Data about prefered profile is lost, sorry.")

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_auto_20171214_0214'),
    ]

    operations = [
        migrations.RunPython(prefered_forward, prefered_backward),
    ]
