# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_trainer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
