# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_move_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='prefered',
        ),
    ]
