# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_remove_discord_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
