# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='meta_time_created',
            field=models.DateTimeField(null=True),
        ),
    ]
