# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 01:04
from __future__ import unicode_literals

from django.db import migrations

def autofill_time(apps, schema_editor):
    MyModel = apps.get_model('trainer', 'Update')
    for row in MyModel.objects.all():
        row.meta_time_created = row.update_time
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0019_update_meta_time_created'),
    ]

    operations = [
        migrations.RunPython(autofill_time, reverse_code=migrations.RunPython.noop),
    ]
