# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0020_generate_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
