# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 16:54
from __future__ import unicode_literals

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0021_auto_20171218_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='prefered',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(on=('owner',)),
        ),
        migrations.DeleteModel(
            name='ExtendedProfile',
        ),
    ]
