# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0022_auto_20171219_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='dex_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_seen',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='seen'),
        ),
    ]
