# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 00:29
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trainer.models
import trainer.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0023_auto_20180102_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faction',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['username'], 'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'get_latest_by': 'update_time', 'ordering': ['-update_time'], 'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AlterField(
            model_name='faction',
            name='colour',
            field=colorful.fields.RGBColorField(blank=True, default='#929292', null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=trainer.models.factionImagePath, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='leader_image',
            field=models.ImageField(blank=True, null=True, upload_to=trainer.models.leaderImagePath, verbose_name='Leader (Image)'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='leader_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='currently_cheats',
            field=models.BooleanField(default=False, verbose_name='Cheater'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='daily_goal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rate Goal'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Faction', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='has_cheated',
            field=models.BooleanField(default=False, verbose_name='Historic Cheater'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_cheated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Cheated'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[trainer.validators.StartDateValidator], verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='statistics',
            field=models.BooleanField(default=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='total_goal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reach Goal'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='update',
            name='battles_won',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Battles Won'),
        ),
        migrations.AlterField(
            model_name='update',
            name='berry_fed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Berries Fed'),
        ),
        migrations.AlterField(
            model_name='update',
            name='big_magikarp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Big Magikarp'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Species Caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_seen',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Species Seen'),
        ),
        migrations.AlterField(
            model_name='update',
            name='eggs_hatched',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Eggs Hatched'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_1_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kanto Pokédex'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_2_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Johto Pokédex'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_3_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hoenn Pokédex'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gym_badges',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Gym Badges'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gym_defended',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gyms Defended (Hours)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='leg_raids_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Raids Completed (Level 5)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='legacy_gym_trained',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ace Trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='meta_time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Created'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pikachu_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pikachu Caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_bug',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bug'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pokémon Caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_dark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dark'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_dragon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dragon'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_electric',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Electric'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_evolved',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pokémon Evolved'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fairy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fary'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fighting',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fighting'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fire',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fire'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_flying',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Flying'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_ghost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ghost'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_grass',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Grass'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_ground',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ground'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_ice',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ice'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_normal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Normal'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_poison',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Poison'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_psychic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pychic'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_rock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rock'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_steel',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Steel'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_water',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Water'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkstops_spun',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pokéstops Spun'),
        ),
        migrations.AlterField(
            model_name='update',
            name='raids_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Raids Completed (Levels 1-4)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='tiny_rattata',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiny Rattata'),
        ),
        migrations.AlterField(
            model_name='update',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='unown_alphabet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unown'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Updated'),
        ),
        migrations.AlterField(
            model_name='update',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Distance Walked'),
        ),
        migrations.AlterField(
            model_name='update',
            name='xp',
            field=models.PositiveIntegerField(verbose_name='XP'),
        ),
    ]
