# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0024_auto_20180103_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='meta_source',
            field=models.CharField(choices=[('?', 'undefined'), ('cs_social_twitter', 'Twitter'), ('cs_social_facebook', 'Facebook'), ('ts_social_discord', 'Official Discord Bot'), ('web_quick', 'Quick Update'), ('web_detailed', 'Detailed Update')], default='?', max_length=256),
        ),
    ]
