# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_auto_20180105_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playzonesdetailcity',
            options={'verbose_name': 'Play Zone - City-wide', 'verbose_name_plural': 'Play Zones - City-wide'},
        ),
        migrations.AlterModelOptions(
            name='playzonesdetailcountry',
            options={'verbose_name': 'Play Zone - National', 'verbose_name_plural': 'Play Zones - National'},
        ),
        migrations.AlterModelOptions(
            name='playzonesdetailregion',
            options={'verbose_name': 'Play Zone - Regional', 'verbose_name_plural': 'Play Zones - Regional'},
        ),
        migrations.AlterModelOptions(
            name='playzonesdetailsubregion',
            options={'verbose_name': 'Play Zone - Subregional', 'verbose_name_plural': 'Play Zones - Subregional'},
        ),
        migrations.AlterField(
            model_name='playzonesdetailcity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailcity',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailcountry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_COUNTRY_MODEL, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailcountry',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailregion',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailregion',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailsubregion',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Subregion', verbose_name='Subregion'),
        ),
        migrations.AlterField(
            model_name='playzonesdetailsubregion',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer', verbose_name='Trainer'),
        ),
    ]
