# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 23:50
from __future__ import unicode_literals
from datetime import date

from django.db import migrations

def set_twitter_users(apps, schema_editor):
    Update = apps.get_model('trainer', 'Update')
    for row in Update.objects.filter(trainer__pk__in=[188,284,285,396,528]):
        row.meta_source = 'cs_social_twitter'
        row.save()
    for row in Update.objects.filter(trainer__pk=401, update_time__lt=date(2017,12,26)):
        row.meta_source = 'cs_social_twitter'
        row.save()
    for row in Update.objects.exclude(trainer__pk__in=[188,284,285,396,401,528]).filter(update_time__lt=date(2017,12,22)):
        row.meta_source = 'ts_social_discord'
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0029_trainerreport'),
    ]

    operations = [
        migrations.RunPython(set_twitter_users, reverse_code=migrations.RunPython.noop),
    ]
