# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0030_auto_20180105_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='update',
            name='meta_source',
            field=models.CharField(choices=[('?', 'undefined'), ('cs_social_twitter', 'Twitter'), ('cs_social_facebook', 'Facebook'), ('ts_social_discord', 'Official Discord Bot'), ('web_quick', 'Quick Update'), ('ts_registration', 'Registration'), ('ss_registration', 'Registration Screenshot'), ('ss_generic', 'Generic Screenshot')], default='?', max_length=256, verbose_name='Source'),
        ),
    ]
