# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0031_auto_20180115_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
