# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0035_auto_20180121_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='meta_source',
            field=models.CharField(choices=[('?', 'undefined'), ('cs_social_twitter', 'Twitter'), ('cs_social_facebook', 'Facebook'), ('ts_social_discord', 'Official Discord Bot'), ('web_quick', 'Quick Update'), ('web_detailed', 'Detailed Update'), ('ts_registration', 'Registration'), ('ss_registration', 'Registration Screenshot'), ('ss_generic', 'Generic Screenshot'), ('cs_social_youtube', 'YouTube')], default='?', max_length=256, verbose_name='Source'),
        ),
    ]
