# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0036_auto_20180221_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='event_10b',
            field=models.BooleanField(default=True),
        ),
    ]
