# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0037_trainer_event_10b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='event_10b',
            field=models.BooleanField(default=False),
        ),
    ]
