# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0038_auto_20180222_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='meta_source',
            field=models.CharField(choices=[('?', 'undefined'), ('cs_social_twitter', 'Twitter (Found)'), ('cs_social_facebook', 'Facebook (Found)'), ('cs_social_youtube', 'YouTube (Found)'), ('ts_social_discord', 'Discord (Bot)'), ('ts_social_twitter', 'Twitter (Bot)'), ('web_quick', 'Quick Update (Web)'), ('web_detailed', 'Detailed Update (Web)'), ('ts_registration', 'Registration'), ('ss_registration', 'Registration w/ Screenshot'), ('ss_generic', 'Generic Screenshot'), ('ss_ocr', 'OCR Screenshot')], default='?', max_length=256, verbose_name='Source'),
        ),
    ]
