# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 11:12
from __future__ import unicode_literals

from django.db import migrations

def rename_trainers(apps, schema_editor):
    Trainer = apps.get_model('trainer', 'Trainer')
    for trainer in Trainer.objects.all():
        if trainer.owner and (trainer.prefered==True or len(trainer.owner.profiles.all())==1) and trainer.username != trainer.owner.username:
            trainer.owner.username = trainer.username
            trainer.owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0040_auto_20180312_1957'),
    ]

    operations = [
        migrations.RunPython(rename_trainers, reverse_code=migrations.RunPython.noop),
    ]
