# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0042_trainer_event_1k_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='event_1k_users',
            field=models.BooleanField(default=False),
        ),
    ]
