# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 13:50
from __future__ import unicode_literals

from django.db import migrations

def prepare_one_trainer_per_user(apps, schema_editor):
    Trainer = apps.get_model('trainer', 'Trainer')
    User = apps.get_model('auth', 'user')
    for trainer in Trainer.objects.all():
        if trainer.owner and len(list(trainer.owner.profiles.all())) == 1:
            trainer.prefered = True
            trainer.save()
        if not trainer.owner or not trainer.prefered:
            NewUser = User.objects.create(username=trainer.username)
            NewUser.save()
            trainer.owner = NewUser
            trainer.prefered = True
            trainer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0043_auto_20180318_1736'),
    ]

    operations = [
        migrations.RunPython(prepare_one_trainer_per_user, reverse_code=migrations.RunPython.noop),
    ]
