# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0044_auto_20180322_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='prefered',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
