# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0047_auto_20180328_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='mew_encountered',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mew'),
        ),
        migrations.AddField(
            model_name='update',
            name='quests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quests'),
        ),
    ]
