# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0048_auto_20180328_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playzonesdetailcity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailcity',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailcountry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailcountry',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailregion',
            name='location',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailregion',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailsubregion',
            name='location',
        ),
        migrations.RemoveField(
            model_name='playzonesdetailsubregion',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='PlayZonesDetailCity',
        ),
        migrations.DeleteModel(
            name='PlayZonesDetailCountry',
        ),
        migrations.DeleteModel(
            name='PlayZonesDetailRegion',
        ),
        migrations.DeleteModel(
            name='PlayZonesDetailSubregion',
        ),
    ]
