# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0049_auto_20180402_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='verification',
            field=models.ImageField(blank=True, null=True, upload_to=trainer.models.VerificationImagePath, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='update',
            name='battles_won',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Battle Girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='berry_fed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Berry Master'),
        ),
        migrations.AlterField(
            model_name='update',
            name='big_magikarp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fisherman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='eggs_hatched',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Breeder'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_1_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kanto'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_2_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Johto'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gen_3_dex',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hoenn'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gym_defended',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gym Leader'),
        ),
        migrations.AlterField(
            model_name='update',
            name='image_proof',
            field=models.ImageField(blank=True, null=True, upload_to=trainer.models.VerificationUpdateImagePath, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='update',
            name='leg_raids_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Battle Legend'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pikachu_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pikachu Fan'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_evolved',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Scientist'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkmn_fairy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fairy'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pkstops_spun',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Backpacker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='quests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pokémon Ranger'),
        ),
        migrations.AlterField(
            model_name='update',
            name='raids_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Champion'),
        ),
        migrations.AlterField(
            model_name='update',
            name='tiny_rattata',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Youngster'),
        ),
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Jogger'),
        ),
    ]
