# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0050_auto_20180413_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='leaderboard_city',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='leaderboard_subregion',
        ),
        migrations.RemoveField(
            model_name='update',
            name='mew_encountered',
        ),
        migrations.AddField(
            model_name='trainer',
            name='go_fest_2018',
            field=models.BooleanField(default=False, verbose_name='Pokémon GO Fest 2018'),
        ),
        migrations.AddField(
            model_name='update',
            name='max_friends',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BADGE_MAX_LEVEL_FRIENDS'),
        ),
        migrations.AddField(
            model_name='update',
            name='trading',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BADGE_TRADING'),
        ),
        migrations.AddField(
            model_name='update',
            name='trading_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BADGE_TRADING_DISTANCE'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='go_fest_2017',
            field=models.BooleanField(default=False, verbose_name='Pokémon GO Fest 2017'),
        ),
        migrations.AlterField(
            model_name='update',
            name='meta_source',
            field=models.CharField(choices=[('?', None), ('cs_social_twitter', 'Twitter (Found)'), ('cs_social_facebook', 'Facebook (Found)'), ('cs_social_youtube', 'YouTube (Found)'), ('cs_?', 'Sourced Elsewhere'), ('ts_social_discord', 'Discord'), ('ts_social_twitter', 'Twitter'), ('ts_direct', 'Directly told (via text)'), ('web_quick', 'Quick Update (Web)'), ('web_detailed', 'Detailed Update (Web)'), ('ts_registration', 'Registration'), ('ss_registration', 'Registration w/ Screenshot'), ('ss_generic', 'Generic Screenshot'), ('ss_ocr', 'OCR Screenshot')], default='?', max_length=256, verbose_name='Source'),
        ),
    ]
