# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0051_auto_20180619_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='max_friends',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idol'),
        ),
        migrations.AlterField(
            model_name='update',
            name='trading',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gentleman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='trading_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pilot'),
        ),
    ]
