# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import trainer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0053_auto_20180709_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_code',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[trainer.validators.TrainerCodeValidator], verbose_name='Trainer Code'),
        ),
    ]
