# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0057_auto_20180722_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='special_weekend_2018',
            field=models.BooleanField(default=False, verbose_name='Pokémon GO Special Weekend'),
        ),
    ]
