# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 18:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import trainer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0058_trainer_special_weekend_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='badge_safari_zone_europe_2017_09_16',
            field=models.BooleanField(default=False, help_text='Europe, September 16, 2017', verbose_name='GO Safari Zone - Europe 2017'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_safari_zone_europe_2017_10_07',
            field=models.BooleanField(default=False, help_text='Europe, October 7, 2017', verbose_name='GO Safari Zone - Europe 2017'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_safari_zone_europe_2017_10_14',
            field=models.BooleanField(default=False, help_text='Europe, October 14, 2017', verbose_name='GO Safari Zone - Europe 2017'),
        ),
        migrations.AlterField(
            model_name='privateleague',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt-br', 'Brazilian Portuguese'), ('zh-hant', 'Traditional Chinese')], max_length=7),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(help_text='Your Trainer Nickname exactly as is in game. You are free to change capitalisation but removal or addition of digits may prevent other Trainers with similar usernames from using this service and is against the Terms of Service.', max_length=15, unique=True, validators=[trainer.validators.PokemonGoUsernameValidator], verbose_name='Nickname'),
        ),
    ]
