# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 18:10
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

def forward(apps, schema_editor):
    MyModel = apps.get_model('trainer', 'Trainer')
    for trainer in MyModel.objects.filter(
        Q(safari_zone_2017_oberhausen = True) |
        Q(safari_zone_2017_paris = True) |
        Q(safari_zone_2017_barcelona = True) |
        Q(safari_zone_2017_copenhagen = True) |
        Q(safari_zone_2017_prague = True) |
        Q(safari_zone_2017_stockholm = True) |
        Q(safari_zone_2017_amstelveen = True)
    ):
        if trainer.safari_zone_2017_oberhausen or trainer.safari_zone_2017_paris or trainer.safari_zone_2017_barcelona:
            trainer.badge_safari_zone_europe_2017_09_16 = True
        if trainer.safari_zone_2017_copenhagen or trainer.safari_zone_2017_prague:
            trainer.badge_safari_zone_europe_2017_10_07 = True
        if trainer.safari_zone_2017_stockholm or trainer.safari_zone_2017_amstelveen:
            trainer.badge_safari_zone_europe_2017_10_14 = True
        trainer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0059_auto_20180728_1809'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
