# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0060_auto_20180728_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_amstelveen',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_barcelona',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_copenhagen',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_oberhausen',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_paris',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_prague',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='safari_zone_2017_stockholm',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='go_fest_2017',
            field=models.BooleanField(default=False, help_text='Chicago, July 22, 2017', verbose_name='Pokémon GO Fest 2017'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='go_fest_2018',
            field=models.BooleanField(default=False, help_text='Chicago, July 14-15, 2018', verbose_name='Pokémon GO Fest 2018'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='outbreak_2017',
            field=models.BooleanField(default=False, help_text='Yokohama, August 2017', verbose_name='Pokémon GO STADIUM'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='special_weekend_2018',
            field=models.BooleanField(default=False, help_text='Japan, July 26-29, 2018', verbose_name='Pokémon GO Special Weekend'),
        ),
    ]
