# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0061_auto_20180728_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='special_weekend_2018',
            new_name='badge_apac_partner_july_2018',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='go_fest_2017',
            new_name='badge_chicago_fest_july_2017',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='go_fest_2018',
            new_name='badge_chicago_fest_july_2018',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='outbreak_2017',
            new_name='badge_pikachu_outbreak_yokohama_2017',
        ),
    ]
