# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 18:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations
import trainer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0062_auto_20180728_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, help_text='Your Trainer Nickname exactly as is in game. You are free to change capitalisation but removal or addition of digits may prevent other Trainers with similar usernames from using this service and is against the Terms of Service.', max_length=15, unique=True, validators=[trainer.validators.PokemonGoUsernameValidator], verbose_name='Nickname'),
        ),
    ]
