# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 19:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0063_auto_20180728_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='thesilphroad_username',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, help_text='The username you use on The Silph Road, if different from your Trainer Nickname.', max_length=30, null=True, verbose_name='The Silph Road Username'),
        ),
    ]
