# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0064_trainer_thesilphroad_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(db_index=True, max_length=240)),
                ('icon', models.ImageField(upload_to='spon/')),
                ('members', models.ManyToManyField(to='trainer.Trainer')),
            ],
        ),
    ]
