# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0065_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='members',
            field=models.ManyToManyField(related_name='sponsorships', to='trainer.Trainer'),
        ),
    ]
