# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0067_auto_20180804_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='currently_cheats',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='has_cheated',
        ),
    ]
