# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0068_auto_20180809_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateLeague',
            new_name='CommunityLeague',
        ),
        migrations.RenameModel(
            old_name='PrivateLeagueMembershipDiscord',
            new_name='CommunityLeagueMembershipDiscord',
        ),
        migrations.RenameModel(
            old_name='PrivateLeagueMembershipPersonal',
            new_name='CommunityLeagueMembershipPersonal',
        ),
        migrations.AlterModelOptions(
            name='communityleague',
            options={'verbose_name': 'Community League', 'verbose_name_plural': 'Community Leagues'},
        ),
        migrations.AlterModelOptions(
            name='communityleaguemembershipdiscord',
            options={'verbose_name': 'Community League Discord Connection', 'verbose_name_plural': 'Community League Discord Connections'},
        ),
        migrations.AlterModelOptions(
            name='communityleaguemembershippersonal',
            options={'verbose_name': 'Community League Membership', 'verbose_name_plural': 'Community League Memberships'},
        ),
        migrations.AlterModelOptions(
            name='discordguild',
            options={'verbose_name': 'Discord Guild', 'verbose_name_plural': 'Discord Guilds'},
        ),
        migrations.AlterModelOptions(
            name='sponsorship',
            options={'verbose_name': 'Special Relationship (Sponsorship)', 'verbose_name_plural': 'Special Relationships (Sponsorships)'},
        ),
    ]
