# Generated by Django 2.1 on 2018-08-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0068_auto_20180809_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='leaderboard_country',
            field=models.ForeignKey(blank=True, help_text='Where are you based?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_trainers_country', to=settings.CITIES_COUNTRY_MODEL, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='leaderboard_region',
            field=models.ForeignKey(blank=True, help_text='Where are you based?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_trainers_region', to='cities.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='verification',
            field=models.ImageField(blank=True, default='', upload_to=trainer.models.VerificationImagePath, verbose_name='Username / Level / Team Screenshot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='update',
            name='image_proof',
            field=models.ImageField(blank=True, default='', upload_to=trainer.models.VerificationUpdateImagePath, verbose_name='Total XP Screenshot'),
            preserve_default=False,
        ),
    ]
