# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0069_auto_20180809_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='badge_apac_partner_july_2018',
            new_name='badge_apac_partner_july_2018_japan',
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_apac_partner_july_2018_south_korea',
            field=models.BooleanField(default=False, help_text='South Korea, July 29, 2018', verbose_name='Pokémon GO Special Weekend'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_cheated',
            field=models.DateField(blank=True, help_text='When did this Trainer last cheat?', null=True, verbose_name='Last Cheated'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_caught',
            field=models.PositiveIntegerField(blank=True, help_text='In your Pokédex, how many differnt species have you caught? It should say at the top.', null=True, verbose_name='Caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='dex_seen',
            field=models.PositiveIntegerField(blank=True, help_text='In your Pokédex, how many differnt species have you seen? It should say at the top.', null=True, verbose_name='Seen'),
        ),
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Walk 1000 km', max_digits=16, null=True, verbose_name='Jogger'),
        ),
        migrations.AlterField(
            model_name='update',
            name='xp',
            field=models.PositiveIntegerField(help_text='Your Total XP can be found at the bottom of your Pokémon Go profile', verbose_name='Total XP'),
        ),
    ]
