# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0070_auto_20180809_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='walk_dist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Walk 1,000 km', max_digits=16, null=True, verbose_name='Jogger'),
        ),
    ]
