# Generated by Django 2.1 on 2018-08-13 01:21

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0071_auto_20180810_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='badge_pikachu_outbreak_yokohama_2017',
            field=models.BooleanField(default=False, help_text='Yokohama, August 2017', verbose_name='Pikachu Outbreak 2017'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='thesilphroad_username',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, help_text='The username you use on The Silph Road, if different from your Trainer Nickname.', max_length=30, null=True, verbose_name='TheSilphRoad Trainer Name'),
        ),
    ]
