# Generated by Django 2.1 on 2018-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0072_auto_20180813_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='gen_3_dex',
            field=models.PositiveIntegerField(blank=True, help_text='Register 90 Pokémon first discovered in the Hoenn region to the Pokédex.', null=True, verbose_name='Hoenn'),
        ),
    ]
