# Generated by Django 2.1 on 2018-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0073_auto_20180815_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_1_sep_2018_kurihama',
            field=models.BooleanField(default=False, help_text='Yokosuka, Sep 1, 2018-KURIHAMA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_1_sep_2018_mikasa',
            field=models.BooleanField(default=False, help_text='Yokosuka, Sep 1, 2018-MIKASA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_1_sep_2018_verny',
            field=models.BooleanField(default=False, help_text='Yokosuka, Sep 1, 2018-VERNY', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_29_aug_2018_kurihama',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 29, 2018-KURIHAM', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_29_aug_2018_mikasa',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 29, 2018-MIKASA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_29_aug_2018_verny',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 29, 2018-VERNY', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_2_sep_2018_kurihama',
            field=models.BooleanField(default=False, help_text='Yokosuka, Sep 2, 2018-KURIHAMA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_2_sep_2018_mikasa',
            field=models.BooleanField(default=False, help_text='Yokosuka, Sep 2, 2018-MIKASA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_2_sep_2018_verny',
            field=models.BooleanField(default=False, help_text='Yokosuka, Sep 2, 2018-VERNY', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_30_aug_2018_kurihama',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 30, 2018-KURIHAMA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_30_aug_2018_mikasa',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 30, 2018-MIKASA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_30_aug_2018_verny',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 30, 2018-VERNY', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_31_aug_2018_kurihama',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 31, 2018-KURIHAMA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_31_aug_2018_mikasa',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 31, 2018-MIKASA', verbose_name='Pokémon GO Safari Zone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='badge_yokosuka_31_aug_2018_verny',
            field=models.BooleanField(default=False, help_text='Yokosuka, Aug 31, 2018-VERNY', verbose_name='Pokémon GO Safari Zone'),
        ),
    ]
