# Generated by Django 2.1 on 2018-08-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0074_auto_20180817_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionLeader',
            fields=[
                ('faction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leader', serialize=False, to='trainer.Faction', verbose_name='Team')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name (English)')),
                ('name_de', models.CharField(max_length=50, verbose_name='Name (German)')),
                ('name_es', models.CharField(max_length=50, verbose_name='Name (Spanish)')),
                ('name_fr', models.CharField(max_length=50, verbose_name='Name (French)')),
                ('name_it', models.CharField(max_length=50, verbose_name='Name (Italian)')),
                ('name_ja', models.CharField(max_length=50, verbose_name='Name (Japanese)')),
                ('name_ko', models.CharField(max_length=50, verbose_name='Name (Korean)')),
                ('name_pt_BR', models.CharField(max_length=50, verbose_name='Name (Brazilian Portuguese)')),
                ('name_zh_Hant', models.CharField(max_length=50, verbose_name='Name (Traditional Chinese)')),
            ],
        ),
        migrations.RemoveField(
            model_name='faction',
            name='leader_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='name',
        ),
        migrations.AddField(
            model_name='faction',
            name='name_de',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (German)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_en',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_es',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (Spanish)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_fr',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (French)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_it',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (Italian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_ja',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (Japanese)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_ko',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (Korean)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_pt_BR',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (Brazilian Portuguese)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='name_zh_Hant',
            field=models.CharField(default='def', max_length=50, verbose_name='Name (Traditional Chinese)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='slug',
            field=models.SlugField(default='sug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communityleague',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt-br', 'Brazilian Portuguese'), ('zh-hant', 'Traditional Chinese')], max_length=7),
        ),
    ]
