# Generated by Django 2.1 on 2018-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0076_auto_20180820_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='stardust',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stardust'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gym_badges',
            field=models.PositiveIntegerField(blank=True, help_text='Your gym badges map. Total number of gold, silver, bronze and blank combined. (This information is currently not used)', null=True, verbose_name='Gym Badges'),
        ),
    ]
