# Generated by Django 2.1.2 on 2018-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0077_auto_20180824_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='gen_4_dex',
            field=models.PositiveIntegerField(blank=True, help_text='Register 0 Pokémon first discovered in the Sinnoh region to the Pokédex.', null=True, verbose_name='Sinnoh'),
        ),
    ]
