# Generated by Django 2.1.2 on 2018-10-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0078_update_gen_4_dex'),
    ]

    operations = [
		migrations.RenameField('update', 'xp', 'total_xp'),
		migrations.RenameField('update', 'dex_caught', 'pokedex_caught'),
		migrations.RenameField('update', 'dex_seen', 'pokedex_seen'),
		migrations.RenameField('update', 'gym_badges', 'gymbadges_total'),
		migrations.RenameField('update', 'walk_dist', 'badge_travel_km'),
		migrations.RenameField('update', 'gen_1_dex', 'badge_pokedex_entries'),
		migrations.RenameField('update', 'pkmn_caught', 'badge_capture_total'),
		migrations.RenameField('update', 'pkmn_evolved', 'badge_evolved_total'),
		migrations.RenameField('update', 'eggs_hatched', 'badge_hatched_total'),
		migrations.RenameField('update', 'pkstops_spun', 'badge_pokestops_visited'),
		migrations.RenameField('update', 'battles_won', 'badge_battle_attack_won'),
		migrations.RenameField('update', 'big_magikarp', 'badge_big_magikarp'),
		migrations.RenameField('update', 'legacy_gym_trained', 'badge_battle_training_won'),
		migrations.RenameField('update', 'tiny_rattata', 'badge_small_rattata'),
		migrations.RenameField('update', 'pikachu_caught', 'badge_pikachu'),
		migrations.RenameField('update', 'gen_2_dex', 'badge_pokedex_entries_gen2'),
		migrations.RenameField('update', 'unown_alphabet', 'badge_unown'),
		migrations.RenameField('update', 'berry_fed', 'badge_berries_fed'),
		migrations.RenameField('update', 'gym_defended', 'badge_hours_defended'),
		migrations.RenameField('update', 'raids_completed', 'badge_raid_battle_won'),
		migrations.RenameField('update', 'leg_raids_completed', 'badge_legendary_battle_won'),
		migrations.RenameField('update', 'gen_3_dex', 'badge_pokedex_entries_gen3'),
		migrations.RenameField('update', 'quests', 'badge_challenge_quests'),
		migrations.RenameField('update', 'max_friends', 'badge_max_level_friends'),
		migrations.RenameField('update', 'trading', 'badge_trading'),
		migrations.RenameField('update', 'trading_distance', 'badge_trading_distance'),
		migrations.RenameField('update', 'gen_4_dex', 'badge_pokedex_entries_gen4'),
		migrations.RenameField('update', 'pkmn_normal', 'badge_type_normal'),
		migrations.RenameField('update', 'pkmn_fighting', 'badge_type_fighting'),
		migrations.RenameField('update', 'pkmn_flying', 'badge_type_flying'),
		migrations.RenameField('update', 'pkmn_poison', 'badge_type_poison'),
		migrations.RenameField('update', 'pkmn_ground', 'badge_type_ground'),
		migrations.RenameField('update', 'pkmn_rock', 'badge_type_rock'),
		migrations.RenameField('update', 'pkmn_bug', 'badge_type_bug'),
		migrations.RenameField('update', 'pkmn_ghost', 'badge_type_ghost'),
		migrations.RenameField('update', 'pkmn_steel', 'badge_type_steel'),
		migrations.RenameField('update', 'pkmn_fire', 'badge_type_fire'),
		migrations.RenameField('update', 'pkmn_water', 'badge_type_water'),
		migrations.RenameField('update', 'pkmn_grass', 'badge_type_grass'),
		migrations.RenameField('update', 'pkmn_electric', 'badge_type_electric'),
		migrations.RenameField('update', 'pkmn_psychic', 'badge_type_psychic'),
		migrations.RenameField('update', 'pkmn_ice', 'badge_type_ice'),
		migrations.RenameField('update', 'pkmn_dragon', 'badge_type_dragon'),
		migrations.RenameField('update', 'pkmn_dark', 'badge_type_dark'),
		migrations.RenameField('update', 'pkmn_fairy', 'badge_type_fairy'),
		migrations.RenameField('update', 'stardust', 'pokemon_info_stardust'),
		migrations.RenameField('update', 'meta_time_created', 'submission_date'),
		migrations.RenameField('update', 'meta_source', 'data_source'),
		migrations.RenameField('update', 'image_proof', 'screenshot'),
    ]
