# Generated by Django 2.1.2 on 2018-10-17 10:43

import django.core.validators
from django.db import migrations, models
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0079_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='double_check_confirmation',
            field=models.BooleanField(default=False, help_text='This will silence some errors.', verbose_name='I have double checked this information and it is correct.'),
        ),
        migrations.AddField(
            model_name='update',
            name='gymbadges_gold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Gold Gym Badges'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_battle_attack_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1000 Gym battles.', null=True, verbose_name='Battle Girl'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_battle_training_won',
            field=models.PositiveIntegerField(blank=True, help_text='Train 1000 times.', null=True, verbose_name='Ace Trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_berries_fed',
            field=models.PositiveIntegerField(blank=True, help_text='Feed 1000 Berries at Gyms.', null=True, verbose_name='Berry Master'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_capture_total',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 2000 Pokémon.', null=True, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_challenge_quests',
            field=models.PositiveIntegerField(blank=True, help_text='Complete 1000 Field Research tasks.', null=True, verbose_name='Pokémon Ranger'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_hours_defended',
            field=models.PositiveIntegerField(blank=True, help_text='Defend Gyms for 1000 hours.', null=True, verbose_name='Gym Leader'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_legendary_battle_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1000 Legendary Raids.', null=True, verbose_name='Battle Legend'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_max_level_friends',
            field=models.PositiveIntegerField(blank=True, help_text='Become Best Friends with 3 Trainers.', null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Idol'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries',
            field=models.PositiveIntegerField(blank=True, help_text='Register 100 Kanto region Pokémon in the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(151)], verbose_name='Kanto'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen2',
            field=models.PositiveIntegerField(blank=True, help_text='Register 70 Pokémon first discovered in the Johto region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Johto'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen3',
            field=models.PositiveIntegerField(blank=True, help_text='Register 90 Pokémon first discovered in the Hoenn region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(126)], verbose_name='Hoenn'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokedex_entries_gen4',
            field=models.PositiveIntegerField(blank=True, help_text='Register 80 Pokémon first discovered in the Sinnoh region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(107)], verbose_name='Sinnoh'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_pokestops_visited',
            field=models.PositiveIntegerField(blank=True, help_text='Visit 2000 PokéStops.', null=True, verbose_name='Backpacker'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_raid_battle_won',
            field=models.PositiveIntegerField(blank=True, help_text='Win 1000 Raids.', null=True, verbose_name='Champion'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_trading',
            field=models.PositiveIntegerField(blank=True, help_text='Trade 1000 Pokémon.', null=True, verbose_name='Gentleman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_trading_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Earn 1000000 km across the distance of all Pokémon trades.', null=True, verbose_name='Pilot'),
        ),
        migrations.AlterField(
            model_name='update',
            name='badge_unown',
            field=models.PositiveIntegerField(blank=True, help_text='Catch 26 Unown.', null=True, validators=[django.core.validators.MaxValueValidator(28)], verbose_name='Unown'),
        ),
        migrations.AlterField(
            model_name='update',
            name='data_source',
            field=models.CharField(choices=[('?', None), ('cs_social_twitter', 'Twitter (Found)'), ('cs_social_facebook', 'Facebook (Found)'), ('cs_social_youtube', 'YouTube (Found)'), ('cs_?', 'Sourced Elsewhere'), ('ts_social_discord', 'Discord'), ('ts_social_twitter', 'Twitter'), ('ts_direct', 'Directly told (via text)'), ('web_quick', 'Quick Update (Web)'), ('web_detailed', 'Detailed Update (Web)'), ('ts_registration', 'Registration'), ('ss_registration', 'Registration w/ Screenshot'), ('ss_generic', 'Generic Screenshot'), ('ss_ocr', 'OCR Screenshot'), ('com.nianticlabs.pokemongo.friends', 'In Game Friends'), ('com.pokeassistant.trainerstats', 'Poké Assistant'), ('com.pokenavbot.profiles', 'PokeNav'), ('tl40datateam.spreadsheet', 'Tl40 Data Team (Legacy)'), ('com.tl40data.website', 'Tl40 Data Team'), ('com.pkmngots.import', 'Third Saturday')], default='?', max_length=256, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gymbadges_total',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Gym Badges'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pokedex_caught',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique Species Caught'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pokedex_seen',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique Species Seen'),
        ),
        migrations.AlterField(
            model_name='update',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to=trainer.models.VerificationUpdateImagePath, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='update',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission Datetime'),
        ),
        migrations.AlterField(
            model_name='update',
            name='total_xp',
            field=models.PositiveIntegerField(null=True, verbose_name='Total XP'),
        ),
    ]
