# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 19:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('enabled', models.BooleanField()),
                ('guard_pokemon_id', models.IntegerField()),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField()),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('team', models.IntegerField(choices=[(0, 'Uncontested'), (1, 'Mystic'), (3, 'Instinct')])),
                ('slots_available', models.IntegerField()),
                ('raid_start', models.DateTimeField(blank=True, null=True)),
                ('raid_end', models.DateTimeField(blank=True, null=True)),
                ('raid_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('raid_pokemon_id', models.PositiveIntegerField(blank=True, null=True)),
                ('raid_pokemon_name', models.CharField(blank=True, max_length=64, null=True)),
                ('raid_pokemon_cp', models.PositiveIntegerField(blank=True, null=True)),
                ('raid_pokemon_move_1', models.PositiveIntegerField(blank=True, null=True)),
                ('raid_pokemon_move_2', models.PositiveIntegerField(blank=True, null=True)),
                ('notification_sent_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.Town'),
        ),
    ]
