# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='discord_webhook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
