# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:50
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_town_discord_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
