# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_town_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='discord_webhook',
            new_name='gym_discord_webhook_url',
        ),
    ]
