# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_auto_20170903_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='last_scanned',
        ),
        migrations.AddField(
            model_name='town',
            name='exclude_pokemon',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='town',
            name='include_pokemon',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='town',
            name='pokemon_discord_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
