# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_auto_20170911_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='guard_pokemon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
