# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_auto_20170911_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='team',
            field=models.IntegerField(choices=[(0, 'Uncontested'), (1, 'Mystic'), (3, 'Instinct'), (2, 'Valor')]),
        ),
    ]
