# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_auto_20170911_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.Faction'),
        ),
    ]
