# Generated by Django 3.0.7 on 2020-07-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0003_auto_20200623_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('verbose_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='update',
            name='comment',
            field=models.TextField(blank=True, max_length=240, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='update',
            name='data_source_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='update',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainerdex.DataSource', verbose_name='Source'),
        ),
    ]
