# Generated by Django 3.2.12 on 2022-03-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0001_squashed_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="update",
            old_name="submission_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="trainer",
            old_name="last_modified",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="update",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="uuid",
            field=models.UUIDField(null=True, verbose_name="UUID"),
        ),
        migrations.AddField(
            model_name="update",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="update",
            name="updated_at",
            field=models.DateTimeField(null=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="update",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
