# Generated by Django 3.2.12 on 2022-03-17 22:05

import uuid

from django.db import migrations
from django.db.models import F


def populate_trainer_fields(apps, schema_editor):
    Trainer = apps.get_model("pokemongo", "Trainer")
    for trainer in Trainer.objects.select_related("owner").all():
        trainer.created_at = trainer.owner.date_joined
        trainer.uuid = uuid.uuid4()
        trainer.save(update_fields=["created_at", "uuid"])


def populate_update_fields(apps, schema_editor):
    Update = apps.get_model("pokemongo", "Update")
    Update.objects.all().update(updated_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0002_add_standard_fields"),
    ]

    operations = [
        migrations.RunPython(populate_trainer_fields, migrations.RunPython.noop),
        migrations.RunPython(populate_update_fields, migrations.RunPython.noop),
    ]
