# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 01:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('enrollment', '0001_initial'), ('enrollment', '0002_auto_20171124_0137')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0008_clear_default_start_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'Interested'), ('G', 'En Route'), ('G-', 'Will be there'), ('GL', 'Running late'), ('A', 'At the gym'), ('D', 'Completed'), ('DC', 'Completed (successful catch)'), ('DR', 'Completed (boss ran)'), ('X', 'Failed to complete raid'), ('/', 'No longer interested in raid')], max_length=2)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.PositiveIntegerField()),
                ('gym', models.CharField(max_length=28)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('raiders', models.ManyToManyField(through='enrollment.Enrollment', to='trainer.Trainer')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='raid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Raid'),
            preserve_default=False,
        ),
    ]
