# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='id',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='discord_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
