# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_clear_default_start_dates'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.PositiveIntegerField()),
                ('gym', models.CharField(max_length=28)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='arrived',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='gym_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('I', 'Interested'), ('G', 'En Route'), ('G-', 'Will be there'), ('GL', 'Running late'), ('A', 'At the gym'), ('D', 'Completed'), ('DC', 'Completed (successful catch)'), ('DR', 'Completed (boss ran)'), ('X', 'Failed to complete raid'), ('/', 'No longer interested in raid')], max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raid',
            name='raiders',
            field=models.ManyToManyField(through='enrollment.Enrollment', to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='raid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Raid'),
            preserve_default=False,
        ),
    ]
