# Generated by Django 2.1.3 on 2018-11-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0001_squashed_0006_remove_trainer_thesilphroad_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="faction",
            table=None,
        ),
        migrations.AlterModelTable(
            name="sponsorship",
            table=None,
        ),
        migrations.AlterModelTable(
            name="update",
            table=None,
        ),
    ]
