# Generated by Django 2.1.2 on 2018-12-04 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0003_update_gen4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt-br', 'Brazilian Portuguese'), ('zh-hant', 'Traditional Chinese')], max_length=12)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
                ('handle', models.SlugField()),
                ('privacy_public', models.BooleanField(default=False)),
                ('memberships_personal', models.ManyToManyField(to='pokemongo.Trainer')),
            ],
        ),
    ]
