# Generated by Django 2.1.3 on 2018-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0006_auto_20181205_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitymembershipdiscord",
            name="auto_import",
            field=models.BooleanField(
                default=True,
                help_text="Members in this Discord are automatically included in the community.",
            ),
        ),
        migrations.RenameField(
            model_name="communitymembershipdiscord",
            old_name="auto_import",
            new_name="sync_members",
        ),
    ]
