# Generated by Django 2.1.4 on 2019-02-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0023_auto_20190210_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='members',
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
    ]
