# Generated by Django 2.1.11 on 2019-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0028_auto_20191003_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="badge_max_level_friends",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Become Best Friends with 3 Trainers.",
                null=True,
                verbose_name="Idol",
            ),
        ),
    ]
