# Generated by Django 2.2.15 on 2020-08-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0031_auto_20200829_1245"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="leaderboard_region",
        ),
    ]
