# Generated by Django 2.2.18.dev20201210025608 on 2020-12-10 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0048_auto_20201210_0255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_battles",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Battles",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_stardust",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Stardust Earned",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_streak",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Longest Streak",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="battle_hub_stats_wins",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the Battle button in your game.",
                null=True,
                verbose_name="Wins",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="gymbadges_gold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the List button under the Gym Badges category on your profile in game, and then counting how many are gold.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(1000)],
                verbose_name="Gold Gym Badges",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="gymbadges_total",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the List button under the Gym Badges category on your profile in game, and then clicking through to your map.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(1000)],
                verbose_name="Gym Badges",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_caught",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the POKÉDEX button in your game. It should then be listed at the top of the screen.",
                null=True,
                verbose_name="Unique Species Caught",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="pokedex_seen",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="You can find this by clicking the POKÉDEX button in your game. It should then be listed at the top of the screen.",
                null=True,
                verbose_name="Unique Species Seen",
            ),
        ),
    ]
