# Generated by Django 2.2.18.dev20201210034232 on 2020-12-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemongo", "0049_update_help_strings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="update",
            name="gymbadges_total",
        ),
        migrations.RemoveField(
            model_name="update",
            name="pokemon_info_stardust",
        ),
    ]
