# Generated by Django 3.2.13 on 2022-05-22 14:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP", "Up"),
                            ("DOWN", "Down"),
                            ("UNSTABLE", "Unstable"),
                            ("MAINTENANCE", "Scheduled Maintenance"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=11,
                        verbose_name="status",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="core.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
