# Generated by Django 3.2.13 on 2022-05-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service_servicestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguild",
            name="members",
            field=models.ManyToManyField(
                related_name="guilds", through="core.DiscordGuildMembership", to="core.DiscordUser"
            ),
        ),
        migrations.AlterField(
            model_name="discordguildmembership",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="core.discordguild",
            ),
        ),
        migrations.AlterField(
            model_name="discordguildmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guild_memberships",
                to="core.discorduser",
            ),
        ),
    ]
