# Generated by Django 4.0.4 on 2022-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_migrate_guild_settings_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguild",
            name="timezone",
            field=models.CharField(default="UTC", max_length=255),
        ),
    ]
