# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 19:11
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('name', models.CharField(max_length=75)),
                ('colour', colorful.fields.RGBColorField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cuppa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sweetener_amt', models.PositiveIntegerField(default=0)),
                ('iswaterhard', models.BooleanField(default=True)),
                ('isbought', models.BooleanField(default=False)),
                ('colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaproject.Colour')),
                ('drinker', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
                'get_latest_by': 'datetime',
            },
        ),
        migrations.CreateModel(
            name='Sweetener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('cube', models.BooleanField(default=False)),
                ('packet', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('green', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cuppa',
            name='sweetener_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaproject.Sweetener'),
        ),
        migrations.AddField(
            model_name='cuppa',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaproject.Tea'),
        ),
    ]
