# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuppa',
            old_name='iswaterhard',
            new_name='hardWater',
        ),
        migrations.RenameField(
            model_name='cuppa',
            old_name='isbought',
            new_name='isBought',
        ),
        migrations.RemoveField(
            model_name='cuppa',
            name='drinker',
        ),
        migrations.AddField(
            model_name='tea',
            name='looseLeaf',
            field=models.BooleanField(default=False),
        ),
    ]
