# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 22:32
from __future__ import unicode_literals
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuppa',
            old_name='iswaterhard',
            new_name='hardWater',
        ),
        migrations.RenameField(
            model_name='cuppa',
            old_name='isbought',
            new_name='isBought',
        ),
        migrations.RemoveField(
            model_name='cuppa',
            name='drinker',
        ),
        migrations.AddField(
            model_name='tea',
            name='looseLeaf',
            field=models.BooleanField(default=False, verbose_name='loose leaf'),
        ),
        migrations.AlterField(
            model_name='cuppa',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='cuppa',
            name='hardWater',
            field=models.BooleanField(default=True, verbose_name='hard water'),
        ),
        migrations.AlterField(
            model_name='cuppa',
            name='isBought',
            field=models.BooleanField(default=False, verbose_name='bought'),
        ),
        migrations.AlterField(
            model_name='cuppa',
            name='sweetener_amt',
            field=models.PositiveIntegerField(default=0, verbose_name='sugars?'),
        ),
        migrations.AlterField(
            model_name='cuppa',
            name='sweetener_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaproject.Sweetener', verbose_name='or sweeteners?'),
        ),
    ]
