name: zapdos Tests, Migrations, & System Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.6
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.6
          cache: "pipenv"
      - name: Install Dependencies from APT
        run: sudo apt-get update && sudo apt-get -y install gettext gdal-bin python3-gdal
      - name: Setting up Python environment
        run: |
          pip install pipenv
          pipenv install --dev --python $(which python3)
      - name: Staring PostGIS (Docker)
        run: docker-compose -f ./docker/docker-compose.yml up -d
      - name: Run Tests
        run: |
          pipenv run python ./zapdos/manage.py test
      - name: Check for uncommited migrations
        run: |
          pipenv run python ./zapdos/manage.py makemigrations --check core pokemongo
      - name: Run Migrations
        run: |
          pipenv run python ./zapdos/manage.py migrate --noinput
      - name: Compile Messages
        run: |
          pipenv run python ./zapdos/manage.py compilemessages
      - name: System Check
        run: |
          pipenv run python ./zapdos/manage.py check
