name: Django Tests, Migrations, & System Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.6
    - name: Remove PostgreSQL 13
      run: |
        sudo apt-get update
        sudo apt-get -y --purge remove postgresql postgresql-13
    - name: Install PostgreSQL 9.6
      run: |
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
        sudo apt-get update
        sudo apt -y install gettext postgresql-9.6 postgresql-9.6-postgis-2.4 gdal-bin python3-gdal
        sudo systemctl start postgresql
    - name: List Packages
      run: apt list --installed
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Setup PostgreSQL
      run: |
        chmod +x ./build_db.sh
        ./build_db.sh
    - name: Run Tests
      run: |
        python manage.py test
    - name: Check for uncommited migrations
      run: |
        python manage.py makemigrations --check core pokemongo
    - name: Run Migrations
      run: |
        python manage.py migrate --noinput
    - name: Compile Messages
      run: |
        python manage.py compilemessages
    - name: System Check
      run: |
        python manage.py check
