name: Django Tests, Migrations, & System Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Install Dependencies from APT
        run: sudo apt-get update && sudo apt-get -y install gettext gdal-bin python3-gdal
      - name: Setting up Python environment
        run: |
          pip install -U pip pipenv
          cd backend
          pipenv install --dev --deploy
      - name: Staring Postgres (Docker)
        run: cd backend && docker-compose up -d
      - name: Run Tests
        run: |
          cd backend && pipenv run python manage.py test
      - name: Check for uncommited migrations
        run: |
          cd backend && pipenv run python manage.py makemigrations --check core pokemongo
      - name: Run Migrations
        run: |
          cd backend && pipenv run python manage.py migrate --noinput
      - name: Compile Messages
        run: |
          cd backend && pipenv run python manage.py compilemessages
      - name: System Check
        run: |
          cd backend && pipenv run python manage.py check
