name: Lint & Style Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
      - run: python -m pip install -U flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --statistics
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
      - run: python -m pip install -U black isort
      - name: Check isort
        run: |
          isort --check .
      - name: Check Black
        run: |
          black --check .
