name: Lint & Style Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
      - run: python -m pip install -U flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
      - run: python -m pip install -U black
      - name: Blacken
        uses: piotrpawlaczek/python-blacken@release/stable
        with:
          path: "."
          line-length: "99"
